### ISSUE TITLE
keywords

### ISSUE THREAD

**Issue by selster** [josh-berry/tab-stash#10]
I see that I can rename a "stash" of bookmarks.  Now I wonder if I could also enter keyworks, and also be able to search my stashes et al by keywords?
Thanks!
SE

**Comment by josh-berry** [comment]
Hi @selster, I think the best way to handle this for now would be to put a keyword in the name itself (e.g. "`My Stash #keyword`"). Unfortunately, Firefox doesn't give add-ons a way to store additional data (like keywords) alongside bookmarks, so there's not much I can do in terms of adding a separate keyword feature.

Right now, Tab Stash doesn't search stash names (just tab names/URLs), but this is something I would like to implement. If you put keywords in your stash names, this should give you a nice way to search in a future release.

I'm going to close this out, but please feel free to re-open this issue or open a new one if you have any more questions. Thanks!
