### ISSUE TITLE
Importing URLs without icons/titles

### ISSUE THREAD

**Issue by Mikhail-M12** [josh-berry/tab-stash#109]
### Problem Statement
Result of importing URLs without Internet connection:
![plp](https://user-images.githubusercontent.com/38190151/107269740-1150ac80-6a5b-11eb-9ad9-0421b89b9383.PNG)

### Preferred Solution(s)
To show URLs instead of "Problem loading page" text.

### Alternative Solution(s)
Ability to show tab URLs instead of titles or URLs in addition to titles.

### Additional Context
(I disabled Internet connection because I do not want to load tens of tabs only for importing them in Tab Stash.)

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, thanks for the feedback—I understand your concern about loading lots of tabs. I'm thinking this could be handled by adding an option to the "Import" dialog to skip loading titles/icons (so that tabs don't have to be opened).

Let me know if you have any more thoughts on what you'd like to see here, and I'll keep this in mind for a future release!

**Comment by Mikhail-M12** [comment]
>adding an option to the "Import" dialog to skip loading titles/icons (so that tabs don't have to be opened).

It is very good idea!
But autochanging title "Server Not Found" to page URL will also be useful for temporarily unavailable sites.

**Comment by josh-berry** [comment]
Two things for the next release:

* There's now an option to skip importing titles and icons for each imported site
* When this option is disabled, Tab Stash will now try to detect titles for sites where possible. It understands OneTab and Markdown formats, and if you give it rich text, it will extract the titles from any links in the text.
