### ISSUE TITLE
lost stashes

### ISSUE THREAD

**Issue by Keith00x** [josh-berry/tab-stash#112]
### System Details

- **OS Version:** [Linux Mint 20
- **Browser Version:** [e.g. Firefox for linux 85.0.2]
- **Tab Stash Version:** [2.8`]

**Installed Browser Extensions:**

- 
- 

### Steps to Reproduce

1. Update Linux Firefox to version 85.0.2
2. Note Tab Stash add-on is gone
3. Reinstall Tab Stash
4. Note stashes are missing

### Additional Details

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, it sounds like perhaps your Firefox update process went awry somehow. Did you notice if any other settings got reset, other extensions went missing, etc.?

Normally Firefox saves all of your browser settings, extensions, bookmarks (which would include your stashes), etc. in something called a "profile". It's possible the upgrade process somehow damaged your profile or mistakenly switched you to a new one.

You can read more about Firefox profiles here: https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles?redirectslug=profile-manager-create-and-remove-firefox-profiles&redirectlocale=en-US

Can you check if you have more than one profile, and if so, does switching profiles bring back your extensions and stashes?

**Comment by josh-berry** [comment]
Hi, wanted to check back in on this—were you able to resolve the issue with your Firefox?

**Comment by Keith00x** [comment]
Thanks Mr. Berry,

I finally found a way to open the old version of Firefox and export my
stashes. I never decided what happened and never investigated other
settings.

Thanks again for your interest in this issue.  Now I export and save my
stashes.

Love this add-on and I have tried a dozen tab managers that can't touch
yours.

**Comment by Keith00x** [comment]
I use Linux rather than Windows. I believe Firefox for Linux asked me to
download and install rather than updating my existing installation. That
would explain why I lost my stashes and would explain why I could launch my
old version.

**Comment by josh-berry** [comment]
Got it, glad you were able to figure out what was going on and recover your old stashes. I'll go ahead and close this issue, but don't hesitate to reach out again if you have trouble!

Best,
Josh
