### ISSUE TITLE
Popup View

### ISSUE THREAD

**Issue by josh-berry** [josh-berry/tab-stash#115]
### Problem Statement
Sometimes it would be nice to only open the Tab Stash UI briefly, e.g. to find and restore a single tab or save the current tab.  Opening the sidebar or full-tab view for these trivial tasks feels a bit heavyweight--one has to explicitly close the sidebar/tab when done, rather than simply clicking away to something else.

### Preferred Solution(s)
It would be nice to offer users the option of showing a popup view when the toolbar button is clicked.  The popup view could have a UI similar to the sidebar, perhaps with some tweaks to make it more streamlined specifically for use as a popup.

### Additional Context
This is a placeholder issue to discuss the experimental popup feature.

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
**Known Issue**: Any in-progress operation (stashing, unstashing, etc.) is abandoned if the popup window is closed before the operation has finished.

This is because the operation is being run from the popup window itself, and not the background worker which is always loaded (even when Tab Stash isn't actively being used). A lot of work still needs to be done to move these operations to the background worker.

**Comment by AdrianSkar** [comment]
Love the feature but its much slower compared to the sidebar (happens with other add-ons too).

**Comment by josh-berry** [comment]
The popup view will be considered fully-supported/working in the next release. Firefox has gotten fast enough that the issue I mentioned earlier about in-progress operations being stopped if the popup is closed really isn't an issue in practice.
