### ISSUE TITLE
Warn before un-stashing a lot of tabs at once

### ISSUE THREAD

**Issue by josh-berry** [josh-berry/tab-stash#117]
### Describe the Bug
Per [user feedback](https://addons.mozilla.org/en-US/firefox/addon/tab-stash/reviews/1686546/), Tab Stash should warn if we're unstashing a lot of tabs at once, as this can cause Firefox to slow down and become unresponsive.

I happened to unstash a lot of tabs at once a little while back, and this unresponsiveness seems to happen even on fast machines—single-thread performance seems to be the issue. Not sure exactly how many tabs are needed to slow things down to the point of unusability.

### Impact
Users may lock up their browsers unintentionally if restoring a large group. Fortunately, if the browser is left alone for long enough, it seems to recover.

### Additional Details
See also: #62

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by deegeebee** [comment]
I had 1400 tabs open in Tree style tab before trying stash tab. I was not able to finish stacking them into different groups in one day. But being new to stash tabs I had accidently hit the "stash tabs" button at the beginning, so I had no unstashed tabs, only many, many stashed tabs left. Trying to unstash more than 500 tabs froze not only FF but my whole system.

**Comment by josh-berry** [comment]
More recent versions of Tab Stash will now limit the number of tabs they try to restore at once, so I think this can safely be closed, as we will no longer overwhelm the user's browser/computer even when restoring hundreds or thousands of tabs.
