### ISSUE TITLE
Search: search group names

### ISSUE THREAD

**Issue by sr105-tm** [josh-berry/tab-stash#118]
### Problem Statement
I would like search to match group names as well as individual stashed tabs. This allows me to put keywords in group names and find all groups related to a topic. Basically this lets me use a poor-man's tagging technique.

### Preferred Solution(s)
It would work just like it does today, except entire groups would also match based on group name.

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
I agree, I've found myself wanting the same thing on occasion, and I'll certainly keep this in mind for a future release!

**Comment by josh-berry** [comment]
This will be available in 2.10, coming soon!
