### ISSUE TITLE
Search: allow to show filtered results in group

### ISSUE THREAD

**Issue by sr105-tm** [josh-berry/tab-stash#119]
### Problem Statement
Search shows matching tabs and the group they reside in. I often want to see all of the tabs in that group, but they are filtered. I can't select the group to view it. All I can do today, is remember the name of the group, clear the search, and then manually go look for that group.  I may not know the title of a page I'm looking for, but I know the title of a page in the same group.

### Preferred Solution(s)
Make it possible to see the filtered results in groups with matches.

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
hm, interesting idea! The way I would envision this working would be something like:

1. Search for something
2. Scroll to find the group you're looking for
3. Click "+N filtered" (or some "clear search" UI element) to be able to show the entire contents of the group (i.e. turn off the search just for that group)
4. Interact with the group normally

Is this what you had in mind?

**Comment by sr105-tm** [comment]
Yes, exactly. I usually click on the "+N filtered" thinking it will show the filtered results for the group.

**Comment by pdcpdc** [comment]
Actually I was looking the way to select all tabs containing some URL parts/keywords and grouping it together. 
Sometimes they get open in different windows and moving into the single window/group would be helpful.
Like searching for "aliexpress" to get the list of all tabs from aliexpress.com

**Comment by josh-berry** [comment]
> Yes, exactly. I usually click on the "+N filtered" thinking it will show the filtered results for the group.

So, I realized just now that I wound up implementing this in 2.10, yet never tied it back to this feature request (since I apparently had forgotten it existed).

Anyway, hope it helps!
