### ISSUE TITLE
Clicking tab stash button from a "New Tab" creates a new stash group

### ISSUE THREAD

**Issue by 0xACE** [josh-berry/tab-stash#122]
# Problem:
When I launch firefox I'm usually greeted by a empty "New tab", I commonly click the `tab stash` icon which stashes the "New tab" in a new stash group. It feels very unneccessary to stash this "empty new tab" as it serves no purpose

# Suggestion:

Introduce a setting to avoid stashing "empty new tabs" or `about:blank` pages...

Btw, is there a way to select multiple tabs to move them to a specific group once they have been stashed?

**Comment by josh-berry** [comment]
Hey, thanks for the bug report—I've noticed this myself and I'll definitely look into it. I agree there's no point to stashing blank tabs. Sorry for the inconvenience!

**Comment by josh-berry** [comment]
This will be fixed in the next release. Sorry again for the inconvenience!

**Comment by josh-berry** [comment]
This will be available in 2.10, coming soon!
