### ISSUE TITLE
Warn new users before first stashing happens

### ISSUE THREAD

**Issue by tntrifonov** [josh-berry/tab-stash#123]
### Problem Statement
As a first-time user, when clicking the extension icon I expected it to open the UI of the add-on in a tab.
Instead, it started stashing 1000+ tabs without asking!
#### Short story
1. Installed Tab Stash
2. Clicked the icon. Nothing happened.
3. Clicked the icon again, 4 seconds later. Nothing still. No info message.
4. Saw that the CPU is being used.
5. Imagine my peril when I saw my tabs disappear one-by-one in the sidebar. Had no idea they were being hidden.
6. After that scare, I had to painfully watch 1000+ tabs getting stashed **twice**. Had no way to pause the process, or stop it.

### Preferred Solution(s)
A warning/confirmation for **first-time** stashing.

The other problem, for stashing a lot of tabs, is in issue #62 but unsolved.

Prevent stashing again if stashing is in progress. (_maybe another issue should be created for this?_)

Related enhancement: Show info message when stashing starts.

### Alternative Solution(s)
Change the default behavior of clicking the add-on icon from stashing to opening the UI.

### Final expected behavior
1. User installs Tab Stash
2. Clicks icon
3. A warning appears: "All tabs will be stashed. [x] Never show this message again | Ok / Cancel |"
4. A warning appears: "You're about to stash 1000+ tabs. Are you sure? | Yes / No |"
5. An info message appears: "Stashing in progress..."
6. An info message appears: "Done"

### Additional Context
Using:

Firefox 89
Tab Stash 2.9
Windows 10

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, sorry for the trouble! To work around this for now, you can change the behavior in Tab Stash's options so this doesn't happen again. From the "Options..." page, under "When the toolbar button is clicked", choose "Don't stash any tabs" from the first drop-down menu.

Going forward, I'm strongly considering changing the default behavior not to stash. When I first wrote Tab Stash, I was thinking it would be a nice way to switch tasks—click the button save everything and get back to a fresh window. But reality is of course messier, and I don't think most people use it this way. I myself prefer to selectively stash most of the time.

Again, sorry for the trouble and thanks for raising the issue. I hope the workaround helps in the meantime. :)

**Comment by FrankySnow** [comment]
As a first-time user, I upvote this since it happened to me today.

**Comment by deegeebee** [comment]
I had 1400 tabs open in Tree style tab before trying stash tab. I was not able to finish stacking them into different groups in one day. But being new to stash tabs I had accidently hit the "stash tabs" button at the beginning, so I had no unstashed tabs, only many, many stashed tabs left. Trying to unstash more than 500 tabs froze not only FF but my whole system.

**Comment by desbest** [comment]
You have to admit it’s a good troll attempt 😂

**Comment by chwpearse** [comment]
I agree with the above users. If it's going to do something so large maybe a warning box along the lines of "You are about to stash 892 tabs, click OK to continue, tick the box below to not show this message again". Mentioning that they will still be runnig in the background might be good too, since the info provided with the extension leads you to believe it's creating a group of bookmarks not hiding the tabs (from the firefox addons page: "Your open tabs will be stashed away in your bookmarks").

Changing the button labelling would help also, it's unclear if the left button stashes every unstashed tab in every window, or just what you have open. Perhaps it could also show the number of tabs that will be stashed on the hover text?
