### ISSUE TITLE
Improve performance of unstashing large numbers of tabs

### ISSUE THREAD

**Issue by deegeebee** [josh-berry/tab-stash#129]
### System Details

Ubuntu Focal Fossa 20.04.1 LTS
Firefox 89.0
Stab stash version 2.9

- **OS Version:** [e.g. Windows 10, or Ubuntu 18.04]
- **Browser Version:** [e.g. Firefox 60.0.2]
- **Tab Stash Version:** [check the Tab Stash entry in `about:addons`]

**Installed Browser Extensions:**

- 
- Extensions:
- FACEBOOK CONTAINER (Yes, I've read it, but I thought... it was a social medias issue? Is my issue caused by it?)
- Auto Tab discard
- Bookmarks clean up
- Enhancer for YouTube
- I don't care about Cookies
- Privacy Possum
- Video Dornload Helper

### Describe the Bug

Being a newbie, I hit the stash tabs button and stashed too many tabs. Now I want to go through them with the book mark editor (because opening the whole stash froze my system).

However, I can't delete any tabs in the bookmark editor (neither with del key nor context menu).
No effect.

### Expected Behavior

Sort this mess out... Edit/delete the bunch of stashed tabs either in stash sidebar (but can't open them without freeze), or edit/delete/sort in bookmark editor.
Tree style tab was able to handle my 1400 tabs on browser start - what was the difference? I assume it did not try to really open them all, maybe favicons only?

### Steps to Reproduce

See above - I can't tell if this happens on my system only.
Testing if using bookmark editor works should be familiar.

### Impact

I used to have 1400 tabs "open" with Tree style tab (I had them sorted, so I could scroll through them and knew the order quite well, only I really would have liked sub-folders).
I am autistic and I have a very specific field of interest which has changing information every week. So I change my tab tree daily, but so far my backup-routine was twice a week.
Now I have to set all my system back to my last back up to get tree style tab side bar plus my old working tabs back if this is not sorted out quicly.

I spent 6 hours sorting 900 tabs yesterday, because marking more than 1 tab in the already stashed side bar did not work.
The 500 I can't sort now are a real mess.

### Additional Details

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by deegeebee** [comment]
Resolved itself upon 2nd re-boot.

After 1st re-boot, Firefox still seemed to have much background work going on when I opened it (no stacked tabs visible in side bar), CPU load without me doing anything was 13%.
I still was not able to edit bookmarks.

I decided to re-boot.

After that, everything was fine.

Thanks to the incident, not only did I get my tabs into folders, but I weeded some out indeed.

Sorry for bothering you.

If possible, I would like to turn this into a features request: to be able to "open" many tabs at once the way tree style tab does (they appear to be open, can be accessed very fast, but neither FF nor my system experienced that much of a CPU/memory load).
So if I open more than 100 bookmarked tabs at once - which I'll still have to test! - things won't collapse again.

**Comment by josh-berry** [comment]
Hi, sorry for the trouble. I'm glad you were able to get things sorted out eventually but certainly using Tab Stash should not cause system instability.

I also hear you on being able to sort large numbers of tabs easily; it's a common feature request (see #57) and one I definitely want to implement, but it may take some time as it can be quite hard to get right.

> If possible, I would like to turn this into a features request: to be able to "open" many tabs at once the way tree style tab does (they appear to be open, can be accessed very fast, but neither FF nor my system experienced that much of a CPU/memory load).

I'll look into how this can be done; certainly it would help with the unstashing problem you had (I saw your other comments on the two "Warn..." issues #117 and #123). Just for ease of tracking I'll go ahead and update the title of this ticket to reflect the issue.

**Comment by deegeebee** [comment]
Thank you, josh-berry

**Comment by deegeebee** [comment]
Hi, I've found a solution that is quite okay for my needs.
I've just changed my bookmarks into a left-sided side-bar view.
This way I can create folders from multiple open tabs using the in-built FF function and I can open bookmarked  tabs needed from folders.
For my purposes, a view of the currently opened (new) tabs in the sidebar is not strictly necessary (would be nice, though).
A view of all bookmarked/stashed tabs in the current window is not necessary either, as long as I can access them quickly through the permanently visible side-bar.
Opening all tabs of one bookmark-folder would create the same issue Tab Stash has).

Moreover, I deactivated Tab stash because it even took up a huge amount of CPU load when I was doing nothing in my browser (just reading an article). My fan was going constantly, which I found distracting, and it stopped whenever I deactivated Tab stash.

So for me some kind of hybrid solution might be good, like having the bookmarks as a view (unloadad) plus having un-bookmarked tabs kind of additionally.

I'm writing this hoping it might give some input how to develop the add-on a bit further (I like it, even if I complain a lot).
Thanks for your work, josh-berry.

**Comment by josh-berry** [comment]
> Moreover, I deactivated Tab stash because it even took up a huge amount of CPU load when I was doing nothing in my browser (just reading an article). My fan was going constantly, which I found distracting, and it stopped whenever I deactivated Tab stash.

I'm really surprised to hear this; performance is something I try to pay pretty close attention to and under normal circumstances, Tab Stash should use background resources very infrequently.

I know you've deactivated Tab Stash, but if you ever decide to come back to it and you'd be willing to spend the time, I'd really appreciate another bug report on this to help narrow down the issue. Here's how to collect error logs (just to see if something is failing when it shouldn't): https://github.com/josh-berry/tab-stash/wiki/Collect-Error-Logs

> So for me some kind of hybrid solution might be good, like having the bookmarks as a view (unloadad) plus having un-bookmarked tabs kind of additionally.

If you do pick up Tab Stash again, you might be interested in trying out #116, which can be enabled in the advanced options. I'd love to hear your thoughts on it.

> I'm writing this hoping it might give some input how to develop the add-on a bit further (I like it, even if I complain a lot).
Thanks for your work, josh-berry.

Definitely, I really appreciate your taking the time to provide constructive feedback. :) Thank you!

**Comment by josh-berry** [comment]
The next release will restore tabs in an unloaded state by default, so that tabs will only be loaded as you actually use them. This should result in a significant performance improvement and avoid causing system slowdowns when restoring large numbers of tabs.
