### ISSUE TITLE
Allow duplicate stashed tabs -- or remove duplicates from older stashed groups only

### ISSUE THREAD

**Issue by blueacorn** [josh-berry/tab-stash#134]
As a user, i view many different web pages/sites and stash them to a new TabStash group when switching contexts mid-task

As a user, i want to be able to save - and get back to - the full "group" of pages/sites i had previously stashed to continue a  task.

As a user, I want to allow duplicate web pages/sites in different TabStash groups, so that i have a complete "group" of all the (most recent) web pages/sites i was working on related to a particular 'stashed task'.

As a user, I never want to _manually_ go back through my TabStash groups, removing duplicates ;)

---
### Notes
 - TabStash used to have an option to allow duplicates -- but now whenever i stash my pages/sites - most of the entries disappear (are de-duplicated) due to a N-months of stashed groups - and i am left with a partial/empty new saved "group" in TabStash.

- An alternative (better) de-duplication  option would be to allow the newest "group" to contain all the stashed web pages/sites -- and remove the duplicates from older stashed groups.

**Comment by josh-berry** [comment]
Which version of Tab Stash are you using, and what other extensions do you have installed?

Tab Stash has not had a de-duplication feature for quite some time (it was removed due to a poor interaction with Firefox Sync), so I wonder if you are on an old version of Tab Stash or if some other extension is de-duplicating your bookmarks for you.

**Comment by blueacorn** [comment]
Latest versions. Ack. My bad. EverSync was deleting the bookmarks moments after they were stashed.  I've used TabStash with EverSync for a long time, and never seen any problem before.  Manual re-sync on EverSync fixed the glitch.

Thanks for the quick response, and sorry for the false positive (but if you do add de-duplication back - option to delete duplicates from the older stashed groups would be awesome :)  TFYH.

**Comment by josh-berry** [comment]
No problem, glad you were able to sort it out!
