### ISSUE TITLE
Extension buttons stopped working in the last Firefox Nightly build.

### ISSUE THREAD

**Issue by dougwl** [josh-berry/tab-stash#137]
### System Details

- **OS Version:** Windows 10
- **Browser Version:** 91.0a1 (2021-06-17)
- **Tab Stash Version:** 2.9

### Describe the Bug

In the last Firefox Nightly version, buttons from the toolbar and address bar have stopped working, since then the only way to interact with the extension is using the sidebar.

### Expected Behavior

The address bar shortcut should stash the tab, and the toolbar button should open the stash.

### Steps to Reproduce

Try to interact with the extension, clicking in any of the shortcuts.

### Impact

This hinder the main ways to interact with the product.

### Additional Details

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by dougwl** [comment]
Debugging the extension, there are two errors being returned:

```
Error: Please use $(ref:runtime.getURL). 21 stash-list.js:2
    p stash.ts:164

Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 	background.js:3007
    send moz-extension://930da2ea-058c-4dc2-8a56-e332d28b6323/background.js:3007

```

**Comment by josh-berry** [comment]
Hi, thanks for the report. Unfortunately Nightly is, well, Nightly, and is prone to all kinds of bugs like these. I took a quick look and from what I can tell, this is not related to Tab Stash but simply a Nightly bug.

For the two errors you mentioned above, one is a deprecation warning and not actually a problem (Firefox is just warning about an older API that Tab Stash uses; even though it says "Error", it's not interfering with anything).

For the second error, it doesn't seem like it's coming from Tab Stash at all (Tab Stash doesn't have a background.js file). For whatever reason, I have seen Firefox sometimes mix errors from different extensions in the same inspector (I have no idea why).

So I'm afraid there's not much I can do to help here other than suggest raising an issue with Mozilla. Sorry about that!
