### ISSUE TITLE
efficient distribution of 655 stashed tabs into groups of which there are 12 so far

### ISSUE THREAD

**Issue by netizenguy** [josh-berry/tab-stash#138]
### Question
This is my first use. I have too many tabs and Tab Stash should help me dramatically reduce the number.
Question #129 was helpful.

I made a pass through the whole collection from one FF window to delete things I did not want to stash. Now I have a main section of stashed tabs I am dispersing and 11 other destination groups. I will add more groups as I am able.
I have 3 more FF windows after this first one.

My current method is to drag and drop: from the main group into the 11+ others.
It would be nice to have copy and paste.
I can stretch a FF Tab display across 2 monitors and have 8 short columns with 4 long columns (including main) beneath.
It would be a help to be able to scroll the main group or copy and paste from it because it is no longer possible to drag and drop except at the highest levels.

Is there a better way to break up the big main?
(You might suggest restoring the stash tabs and then putting them into my groups, but I don't know how to target a stash to a particular group destination.)

### System Details
Tab Stash 2.9
KDE Neon 5.22 based on Ubuntu 
Firefox 89.0

**Comment by josh-berry** [comment]
Hi, each group has its own set of blue "Stash" buttons to save directly to a particular group. Let's say you want to move some tabs from your big "source" group to a smaller "target" group. What you can do is:

1. Open a new window and load Tab Stash in that window
2. Restore and delete (yellow button) just the tabs you want to move from the source group
3. Click the blue "Stash all" button for the target group to save the restored tabs there.

I agree this isn't particularly intuitive and I have some ideas for making it better (e.g. multi-select, context menus, etc.), but for now I hope this helps!

**Comment by netizenguy** [comment]
Thanks for that suggestion. I will give it a try soon.

In the meantime, I notice that when I open a fresh new window, it immediately populates itself with nearly 500 tabs copied from existing windows. That's a problem and there may be more....

So I plan to refresh FF first after backing up all my bookmarks after bookmarking all open tabs as well into temporary collections. I will make screenshots of my addons... as people suggest before doing the refresh.
When I have set up FF again I plan to open up one by one the temporary collections and stash tabs separately.

I have a few more chores to do as well, but I hope it will not be long....

**Comment by netizenguy** [comment]
I found the source of the extra tabs on opening a new window. It is a FF feature where somehow I likely stashed the tabs inadvertently into it. 
I am also turning to FF to see if I can identify where extra memory is being consumed by particular tabs. It involves some study and maybe asking questions.
I will soon try to do what your suggest.

**Comment by josh-berry** [comment]
Sounds good, and good luck in your cleanup efforts. I'll go ahead and close this out but please feel free to reopen/leave another comment here or open a new issue if you have any more questions!
