### ISSUE TITLE
[sub-folders] Add Groups of Stashes

### ISSUE THREAD

**Issue by selster** [josh-berry/tab-stash#14]
I am starting to have a lot of stashes such that I can't see them all, in one glance.  Therefore, I would like to be able to save related stashes into a "group" of stashes.
Thank you for the great add-in.
Steve

**Comment by selster** [comment]
OK. In show all bookmarks, under my stashes, I can create a new folder and drag stash folders into this new folder.  But when I refresh stash (?only by creating a new stash folder), while I can see the newly created folder, in stash, I can't click on it and see the sub-folders.

**Comment by josh-berry** [comment]
Yes, you can organize your bookmarks however you like in Firefox, but for now we only support one level of folders underneath the root "Tab Stash" folder. I've had the same issue myself so this is definitely something I'll keep in mind for a future release. Thanks for the feature request!

**Comment by ejm554** [comment]
Thanks for considering this great idea. I had the same issue. Just something to consider, tho. As a user, I think using the term "group" for this feature would just create more cognitive load. Alternatively, please use terminology that is already commonplace, such as _folder, subfolder,_ or _nested folder._ Maybe even _substash._

**Comment by rjshrjndrn** [comment]
Was checking for groups.. oops stumbled here.. Thank you for this great plugin.

**Comment by josh-berry** [comment]
I'm happy to say this long-awaited feature (nested stashes) will be in the next release. :)

**Comment by alphapapa** [comment]
Great news!  Thank you!

**Comment by Dennismn** [comment]
Awesome, much appreciated!
