### ISSUE TITLE
I guess I have the same question re "Close all stashed tabs" -- does clicking this just close the tabs along the top of the browser (freeing up memory), or does it also delete the bookmarked tabs in the previous Stashed Tabs lists?  Thanks.

### ISSUE THREAD

**Issue by hallsvt** [josh-berry/tab-stash#142]
### System Details

- **OS Version:** [e.g. Windows 10, or Ubuntu 18.04]
- **Browser Version:** [e.g. Firefox 60.0.2]
- **Tab Stash Version:** [check the Tab Stash entry in `about:addons`]

**Comment by josh-berry** [comment]
I think I answered this along with my answer to your question #141, so I'll close this one and we can continue discussion in #141.
