### ISSUE TITLE
new window

### ISSUE THREAD

**Issue by tony4newton** [josh-berry/tab-stash#145]
Can there be an option to open stashed tabs in a new window please. 

### Additional Context

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, can you share some more thoughts on this? I'm not sure I understand what you're looking for here or how this will make things easier for you. I would imagine opening several tabs into new windows would quickly get unmanageable, so I think a bit more description of the context and problem you're trying to solve would help.

Thanks!

**Comment by josh-berry** [comment]
Will close this out since I haven't heard back, but please feel free to leave a follow-up comment here if you're still interested in this. Thanks!
