### ISSUE TITLE
folder path to stash

### ISSUE THREAD

**Issue by selster** [josh-berry/tab-stash#150]
Win 10 64 bit

Hi I can't figure out if I am supposed to be able to get a windows folders path to a given stash?  If so, it doesn't come up in the right click menu for a particular stash.

Thank you,
Steve

**Comment by josh-berry** [comment]
Hi Steve, no, there is no Windows folder path to a particular stash. Stashes are stored in your Firefox bookmarks, not in the filesystem. Firefox has its own way of storing bookmarks—basically they are all stored together in a single file along with your browser history and such.

Hope this answers your question, let me know if you need anything else!

— Josh
