### ISSUE TITLE
url of a stash and its stashees

### ISSUE THREAD

**Issue by selster** [josh-berry/tab-stash#151]
Is there a way to get the url of a stash and/or and we pages stored within a stash?

**Comment by josh-berry** [comment]
There is no URL of the stash itself, but you can get the URLs for pages in the stash either through the Firefox bookmarks manager or by using Tab Stash's export feature. Here's how: https://github.com/josh-berry/tab-stash/wiki/Copying-Bookmarks-Out-of-Firefox

**Comment by josh-berry** [comment]
I'm going to go ahead and close this out, but feel free to leave another comment if you have any more questions!
