### ISSUE TITLE
Stash Groups

### ISSUE THREAD

**Issue by NamesNetworkNic** [josh-berry/tab-stash#154]
The ability to combine stashes into groups for added convenience.

A good example of use case could be for shopping.
Somebody clothes shopping might be looking at all of the options at one store, then at another, then at another, making each of those different shopping sessions a separate stash.

As Tab Stash is, to keep that neat, the stashes need to be named in an organised fashion to make it immediately clear they are meant to be together and then manually placed next to each other; but with groups that person could simply place all of them in the same group and call it a day - no extra work required.

**Comment by NamesNetworkNic** [comment]
Duplicate of #14 
_Sorry!_

**Comment by josh-berry** [comment]
No problem, thanks for the feature request all the same! 😄
