### ISSUE TITLE
Update/replace existing group with tabs from current window

### ISSUE THREAD

**Issue by lucatrv** [josh-berry/tab-stash#157]
### Problem Statement
Currently you can either open a group keeping it (green icon) or deleting it (yellow icon). In both cases, the opened tabs do not remain synced with the original group. In the former case, if you close or browse some of them, there is no easy way to save the updates, apart from stashing a new group, delete the old one, and give the new group the same name. In the latter case, you lose the name of the group, and when you want to stash the group again you need to remember the previous name and write it again.

### Preferred Solution(s)
Add the ability to open a stashed group in a new window keeping them synced. While I browse, all bookmarks in that group would remain synced with the window state, so that at any time if I close the window all bookmarks are already updated. This would behave similarly to [Tabs Outliner](https://chrome.google.com/webstore/detail/tabs-outliner/eggkanocgddhmamlbiijnphhppkpkmkl). I am not sure if this could work across Firefox session though, in this case maybe the alternative solution (see below) would be preferable.

### Alternative Solution(s)
Allow updating an existing group with all the tabs of a window. In this case one could open a group in a new window, browse, and finally save the state of the window on the previous group. This could be implemented together with the popup dialog suggested [here](https://github.com/josh-berry/tab-stash/issues/152#issuecomment-917592781), as an additional dialog which opens when the user clicks on ["Stash all tabs in this window"](https://github.com/josh-berry/tab-stash/issues/98#issuecomment-917601714) and then selects an existing group. The dialog would allow either to "Append the window tabs to the group" or "Sync the group with the window tabs".

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Unfortunately, for a variety of reasons, there is no safe way to automatically keep an open window in sync with a stash, and trying to do so would likely cause problems within the Firefox bookmark subsystem and bookmarks sync itself. See #15 for a more detailed explanation.

Sorry to be the bearer of bad news there!

I'll keep this open as an enhancement for your alternative solution, and update the title accordingly. I agree having some way to say "replace the contents of this group with the tabs in the open window" would be useful, and I think this would be more feasible.

**Comment by josh-berry** [comment]
See also discussion in #206.

**Comment by josh-berry** [comment]
Looks like the alternative solution is actually already filed as a feature request. See #42. I'll go ahead and mark this as a duplicate—don't know why I didn't notice that earlier, my bad!
