### ISSUE TITLE
Hidden tabs are listed in Firefox "Recent tabs" list

### ISSUE THREAD

**Issue by mystiquewolf** [josh-berry/tab-stash#158]
### Question

Please see this bug report, it may be interesting to you and/or provoke some discussion. [Bugzilla Bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1731050)

**Comment by josh-berry** [comment]
Thanks, left a comment. Let's see what the Mozilla folks have to say. :)

**Comment by mystiquewolf** [comment]
Fixed in Firefox 98.
