### ISSUE TITLE
Autocollapse new groups

### ISSUE THREAD

**Issue by AdrianSkar** [josh-berry/tab-stash#163]
### Problem Statement

When  you access TabStash from another device, all new groups appear uncollapsed, making it difficult to navigate previous/other ones, especially if you have a significant amount of tabs on them.
![image](https://user-images.githubusercontent.com/12052430/137583005-a4ccaad9-9099-4cd3-bbb6-ed21121d19de.png)

### Preferred Solution(s)

Sync collapsed/uncollapsed status with other devices.
### Alternative Solution(s)

- Make new groups on other devices appear collapsed by default.
- Add an option to set default state (collapsed/uncollapsed) for new groups?

### Additional Context

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Unfortunately Firefox gives a very limited amount of storage available for add-ons to sync data, so I'm not sure that syncing the collapsed state could be made to work reliably. But I'll keep your "default" suggestion in mind for a future release!
