### ISSUE TITLE
Bulk Close Hidden Tabs

### ISSUE THREAD

**Issue by tps125** [josh-berry/tab-stash#164]
It would be great to have an option to bulk-close stashed tabs that are hidden instead of closed.

**Comment by crypticGator** [comment]
Is this for hidden AND stashed, or hidden OR stashed?

**Comment by crypticGator** [comment]
> Hi, if I understand your question correctly, you can do this today by Option+Clicking or Alt+Clicking on the "Close all open tabs" button in "Unstashed Tabs".
> 
> <img alt="Screen Shot 2021-10-16 at 11 44 16" width="482" src="https://user-images.githubusercontent.com/1203893/137598834-de9688d9-29e6-4a24-b95d-ef7bd4e803cf.png">
> 

Is this for hidden AND stashed, or hidden OR stashed?

**Comment by josh-berry** [comment]
> Is this for hidden AND stashed, or hidden OR stashed?

“And”. Tab Stash won’t touch hidden tabs managed by other extensions.
