### ISSUE TITLE
Tab Stash is unworkable if Firefox's profile is located on ramdisk.

### ISSUE THREAD

**Issue by Mikhail-M12** [josh-berry/tab-stash#166]
**Briefly:** Tab Stash (v2.1+) + Firefox (v79+) + profile on ramdisk (Direct-IO type) = Tab Stash doesn't work.

### System Details

- **OS Version:** Windows 7 SP1 x64.
- **Browser Version:** Firefox v79+ (including v91ESR) or Waterfox G4.
- **Tab Stash Version:** v2.1+ (including v2.9).

**Installed Browser Extensions:** no (clean profile).

### Describe the Bug
I have been using Firefox (Waterfox) with profile on ramdisk (Primo Ramdisk 5.5.0, Windows 7SP1 x64) for years and haven't encountered any problems. Tab Stash used to work normally on Firefox 78ESR (Waterfox G3). But Tab Stash doesn't work on Firefox 79+ (and Waterfox G4) if browser's profile is located on Direct-IO type ramdisk.

It affects Tab Stash v2.1+ (including last version 2.9). Tab Stash v2.0 works.

If SCSI type ramdisk is used (Primo Ramdisk allows to select between Direct-IO (faster) and SCSI ("works like a real physical disk") types ramdisk), then Tab Stash v2.1+ works.

While debugging I can see error: "
```
Can't find profile directory.
    load	resource://gre/modules/XULStore.jsm:66
    XULStore	resource://gre/modules/XULStore.jsm:24
```
"

It must be Firefox's bug. Maybe it could be workarounded (as Tab Stash 2.0 works)?

### Steps to Reproduce
1. Create new profile.
2. Move it to Direct-IO type ramdisk (copy folder and edit profiles.ini).
3. Install TabStash 2.1+.
4. See unworkable Tab Stash.

### Impact
Because of this bug, new users with profile on ramdisk may think that Tab Stash is totally unworkable.

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Since there's not much I can do on the Tab Stash side of things, I'll go ahead and close this, but please do feel free to leave another comment if you have any more questions!

**Comment by Mikhail-M12** [comment]
Option 3 (in addon description warn users that Tab Stash (because of Firefox's bug) doesn't work in Firefox 79+ / Waterfox G4 when profile is located on Direct-IO ramdisk) is very simple. Profile on ramdisk is rare case, but users should be warned about any incompatibilities.
Option 2 also may be relatively simple.

**Comment by josh-berry** [comment]
I'm afraid options 1 and 2 are not possible--I have no way to know if any particular error is due to a ramdisk setup or some other reason (even Firefox itself does not know if the profile is on a ramdisk), nor do I have such a setup myself to be able to troubleshoot further.

I think it's very rare for anyone to run Firefox in a ramdisk (in fact, your issue is the first I've ever heard of such a thing being done). If I do see multiple complaints related to ramdisks, though, I'll keep option 3 in mind.

**Comment by Mikhail-M12** [comment]
>If I do see multiple complaints related to ramdisks, though, I'll keep option 3 in mind.

You won't see. Most users of ramdisks won't look into problem and will just think that Tab Stash is unworkable. Among addon reviews there are some 1-star reviews. Maybe some (for example, "Completely non-functional. Tabs are not saved.") were written by ramdisk users?
