### ISSUE TITLE
Sidebar always shown when Firefox restores a previously closed session

### ISSUE THREAD

**Issue by DavideRossi** [josh-berry/tab-stash#167]
### System Details
- **Linux Mint 20.2**
- **Firefox 93**
- **2.9**

### Describe the Bug
When Firefox restores a session at startup, the tab-stash sidebar in shown, even if it was hidden when closing Firefox. This applies to all the windows in the session.

### Expected Behavior
Not having the sidebar shown in each window.

Not really sure if that's a bug, an expected behavior or something that can be changed from Firefox options, any suggestion is appreciated.

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, were you able to resolve the issue with either of the above suggestions?

**Comment by josh-berry** [comment]
I'm going to go ahead and close this out but if you're still having trouble, let me know!

**Comment by DavideRossi** [comment]
Sorry @josh-berry I missed the notification about your reply. The issue seems that in one of the windows I had the sidebar open when closing Firefox. This is was enough for it to open it in all the restored windows at resume time. If no window has a sidebar open no one will have them at resume time. So it's kind of fixed for me now: I just take care to close all sidebars before exiting Firefox.
