### ISSUE TITLE
Import OneTab Groups

### ISSUE THREAD

**Issue by arandorion** [josh-berry/tab-stash#17]
I have used OneTab for some time and have a total of 1,219 tabs (URLs) saved. OneTab does have the ability to export to a text file containing just the URLs and page titles with each group delimited by a paragraph break.

It would be very cool if I could import these tabs (URLs) into Tab Stash. I don't think OneTab exports group names, but I'd still be okay with importing the tabs even if they lost their custom group names but remained in their proper groupings.

OneTab has over 81,000 users, and I've already heard a few people say they were switching from OneTab to Tab Stash since Tab Stash is a much better add-on. Being able to import from OneTab could help thousands of people switch to Tab Stash.

**Comment by josh-berry** [comment]
Wow, and here I thought my 300 or so tabs was a lot. :) I like the idea; I'll have to think on the best way to do it and maybe play around with OneTab a bit to see what it actually exports. I could also see how this might be useful if, for example, someone sends just a list of URLs via email that the recipient then wants to import.

[See also: #11, which is the feature request to export groups/tabs from Tab Stash.]

**Comment by theunbob** [comment]
I'm also a OneTab user with hundreds of URLs I need to import to Tab Stash. So add me to the list of users wanting this feature!

**Comment by Narga** [comment]
👍 
I used OneTab too, it has 2 groups that included 1200 URLs. I want to transfer them to Tab-Stash beause it is not sync between multi-devices and NOT safe - I've lost them several times because the Firefox's crashes. So, this feature is very useful to make it done.
At this time, I move it manual, it's take a lot of time.

**Comment by josh-berry** [comment]
Import/export will be available in a variety of formats (including OneTab) in the next Tab Stash release. :)

**Comment by eddy-geek** [comment]
I have just tried to import a OneTab export, basically paragraph of one "url | title" per line, and while the import ran for some time opening tabs to fetch icons, it saved nothing for some reason. I don't see any documentation on what would be a guaranteed-to-work format...
