### ISSUE TITLE
⚠️ PLEASE READ ME FIRST: Known issues with 2.10

### ISSUE THREAD

**Issue by josh-berry** [josh-berry/tab-stash#173]
Hi everyone,

I'm aware of a couple significant issues with Tab Stash 2.10, so I've pulled that release for new users. If you're currently using 2.10 and you're happy with it, then there is little/no risk in continuing to use it. **However, if you do hit an issue and you want to downgrade to 2.9, simply uninstall and reinstall Tab Stash from [addons.mozilla.org](https://addons.mozilla.org/en-US/firefox/addon/tab-stash/).** When fixes are available, you'll automatically be upgraded to the fixed release.

Known issues include the following (I'll keep this list up to date as you send me bug reports):
* The Tab Stash UI doesn't track open tabs correctly when they're moved between windows
* The "Open Stashed Tabs in a Tab" option may stop working after you close a window
* ~#172~

### How/Why This Happened
In the 2.10 release, I made some large changes to something called the "model", which is a data structure in Tab Stash that keeps track of your bookmarks and open windows/tabs. These changes were intended to clean up and simplify the model while preparing for some new features I want to do in later releases. As part of making these changes, I added a lot of new test cases intended to catch bugs like these--but evidently there were a few key scenarios which I missed (both in the automated tests and in my own manual testing).

### What's Next
I'm working on a 2.10.1 release with fixes for the known issues and some better "safety nets" so if the model gets into a bad state, it can recover. However, it will take me a bit of time to finish and test these fixes, and for Mozilla to review the new version once it's ready.

In the meantime, **if you're still running 2.10 and you hit an issue *not* on the above list, I'd really appreciate a bug report with as much detail as you can give me.** Here's how to collect error logs: https://github.com/josh-berry/tab-stash/wiki/Collect-Error-Logs 

### Sorry About This... 😿 
Many of you have told me how you rely on Tab Stash for doing your daily work and staying organized, and I know how frustrating it can be to run into issues in a tool that you rely on every day. One of my primary goals for Tab Stash is that it should Just Work when you need it--and stay out of sight and out of mind when you don't. Since 2.10 doesn't live up to this goal, I've decided to pull it until the issues can be solved.

If you've run into/been impacted by these issues, I apologize, and thank you for your patience while I work on the fixes.

-- Josh

**Comment by josh-berry** [comment]
2.10.1 is in the review queue at Mozilla with fixes for the above issues (sans the CPU issue, which turned out to be a performance problem only in very specific situations).

**Comment by josh-berry** [comment]
2.10.1 is now released with fixes for the above. Thanks all for your patience.

**Comment by Yagoth** [comment]
Open Stashed Tabs in a Tab does not work for me period, see posted bug

**Comment by abhijit-hota** [comment]
> Sorry About This...

Josh, this is by far the most amazing tab manager I've used. It fits my workflow perfectly. I've always wanted a "better OneTab" and this hits it.

Please don't apologize for the things that are mildly imperfect. We appreciate your work and the extension a lot! :heart:

**Comment by josh-berry** [comment]
@abhijit-hota Thanks, that means a lot and I'm really glad to hear it! ❤️
