### ISSUE TITLE
[FR] Allow moving tab into collapsed group

### ISSUE THREAD

**Issue by AdrianSkar** [josh-berry/tab-stash#174]
### Problem Statement

It's not possible to drag/move a tab into a collapsed group.

### Preferred Solution(s)

Be able to move them into collapsed groups too.

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
With 2.10 / 2.10.1 it is possible:

1. Select the tab by clicking its icon
2. Hover over the collapsed group. A blue "stash" icon will appear.
3. Click the "stash" icon to move the selected tab into the group
4. Click on any blank space in the UI to de-select the tab.

Hope this helps!

**Comment by AdrianSkar** [comment]
Great! I didn't know about that. Hope to get drag and drop support one day as it's the most intuitive way to do so. Ty!
