### ISSUE TITLE
How many tabs is Tab-Stash reasonably expected to support? 200? 20,000?

### ISSUE THREAD

**Issue by Yagoth** [josh-berry/tab-stash#176]
### Question
How many tabs is TabStash reasonably designed to support 200? 20,000? 
I have it set to closed the tab immediately when stashed, so theoretically they should take up minimal resources. 

I want to use it as a replacement for OneTab which I have 3000+ tabs stored, the import was successful. However tab-stash seems rather slow to react, it regularly fails to open tabs after a click and I am currently unable the tab-stash tab at all, only the sidebar works.
**I am opening separate tickets for the poor behaviors. This is just a question about intended capabilities/use**

### System Details
Computer: 16GB ram, 6 Core Intel Core i7-8750H, GTX 1050ti

Extensions:
Cookie Manager
Feedbro
KeepassXC-Browser
OneTab(Temporarally while I see if Tab-stash works)
Privacy Badger
TinEye Reverse Image Seach
uBlockOrgin
Video Speed Controller
VT4Browsers

- **OS Version:**
Windows 10 20H2
- **Browser Version:**
94.0.2
- **Tab Stash Version:**
2.10.1

**Comment by josh-berry** [comment]
I've tested with thousands of tabs. I myself typically have a few hundred saved, but I know of some users who have thousands and have not run into performance issues. I don't know if anyone's tried tens of thousands though. 3000+ doesn't seem unmanageable.

If you do see performance issues, it's most likely going to be in the form of the UI being slow to load, or in operations like a search slowing down. But dealing with individual groups/tabs (so long as the groups are reasonably-sized) should not show any performance problems even for very large stashes.

Having things outright fail doesn't seem like a performance issue though--seems more like a correctness problem. I see your #177, let's discuss more in detail there.
