### ISSUE TITLE
Global Keyboard Shortcut to toggle Selection State of the active/open browser tab in Tab Stash Group

### ISSUE THREAD

**Issue by WebMechanic** [josh-berry/tab-stash#178]
This is a follow up productivity request of #169 and deals with moving tabs into new or existing stash groups to cleanup the browser tab bar.

The new selection feature in 2.10 simplifies this task esp. cleaning up the **the "Unstahed Tabs" group**, _which is the focus of this request_ and relevant for the workflow described.

> Before 2.10 I had to manually move every single tab into its target group, now I can move them in bulk.

The new feature -- if implemented -- might also be equally useful when dealing with open browser tabs already stashed in other groups in order to quickly select them and then do whatever one can do with such selections.

The issue is likely _less prevalent_ if you want to move _closed tabs_ from one stash group into another; that's what the new selection feature covers perfectly well.

### Problem Statement
Prerequisit: many open unstashed tabs, and the "Unstashed Tabs" group open.

In my regular cleaning up workflow I switch to an **unstashed open tab** in FF using the mouse to then identify it in Tab Stash's "Unstashed Tabs" group (it highlights in bold), then move there (with my mouse of tablet pen) to mark it selected clicking the "favicon", move back up to the tab bar and switch to the next open tab of interest so it gets highlighted in Tab Stash, move back there and mark it, move back to the browser ...
You get the picture.

Do this with a dozend or more tabs and you are on a long journey with your mouse.

### Preferred Solution(s)

Pressing a keyboard shortcut to mark the active open tab in Tab Stash would speed up this process significantly; click tab, press key, click tab, press key ... Your hands can stay where the are.

For this have a **custom keyboard shortcut** to perform the selection in Tab Stash as an equivalent of clicking the tab's favicon (so it turns blue-ish). 
Pressing the same shortcut again would **toggle** the selection/mark. 
It should toggle, because separate shortcuts for select/deselect are literally counter productive.

This shortcut **must be global** so Tab Stash can react to it even if the browser UI, the window or document have focus.

### Alternative Solution(s)
None that would potentially be more efficient (except voice control).

The Tab Stahs context menu is only suitable for this command for accessibility reasons if one works single handed and/or cannot perform keyboard shortcuts. Tab Stash appears at the very bottom of the browser tab context menu, so moving there with the mouse would help with a11y, but it's the opposit of what this feature request attempts to solve: be more productive.

### Additional Context

Should this feature be shipped, **no shortcut should be predefined**. Please make this a custom option in the extension settings. Any predefined, hardcoded shortcut would likely clash with (global) shortcuts from other extensions, the browser locale, the OS.

The keyboard shortcut must be customisable, because developers sometimes have a wrong idea of what users can do with their fingers or simply because users can/must make use of alternative input methods (a11y). 

Something like Ctrl+Alt+Shift+M (Cmd+Opt+Shift+M) is virtually imposible to press with a healthy, single (left) hand, while the other (right) hand is on the mouse waiting to select the next open tab :-) 
Moving the mouse-hand to the keyboard defeats the purpose of having a keyboard shortbut in the first place.

Also _international keyboard layouts_ can differ significantly from english layouts and make some "english centric" shortcuts impractical at best and virtually impossible if special characters are involved (brackets, punctuation).

_The user would know best which shortcut to use._

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, thanks for the feature request and detailed write-up! One part of what you wrote really stood out to me:

> In my regular cleaning up workflow I switch to an **unstashed open tab** in FF using the mouse to then identify it in Tab Stash's "Unstashed Tabs" group (it highlights in bold), ...

If you're going back and forth between the FF tab bar and the Tab Stash UI (sidebar I assume), I can see how this would be a lot of cursor travel.

Would it instead help to be able to switch to the tab directly from the Tab Stash UI (e.g. by clicking on the title)? This seems like it might be even more efficient, since it avoids the back-and-forth between mouse and keyboard.

**Comment by WebMechanic** [comment]
I see, but no :-)
The container tabs are coloured so they are easy to spot in the tab bar for "cleanup". 
Items in a stash don't tell if they belong to a container group and their favicons might be gone or generic, after I resumed a closed browser session.

Using a container colour to "visually filter" the unstashed tabs also avoids unneccesarly reloads of unloaded/sleeping tabs.
Let's say I have 30+ unstashed tabs and 10 are in a container group, that's 10 clicks (+ selection/keystroke). End of. 
Working from the stash side I'd need to click through all items to learn which one belongs to a particular container group -- and trigger many reloads that slow down the process.
(I just noticed, that if I Ctrl+click tabs to multi-select, they don't get highlighted in the stash group.)

Although the unstashed items order matches the order of open tabs, there's always a chance some other tabs are in between from another stash groups, read: unstashed stash item 5 is not neccessarily the 5th tab from the left.

I'm aware that this a very specific scenario, but I believe it'd be also helpful for others to have a keyboard shortcut to perform a quick selection without much mouse travelling.

Then all that's left is for a _closed stash group to open up_ or accept the drop, if a batch of tabs is dragged onto it ;-)

**Comment by WebMechanic** [comment]
and yes, the Stash UI is in the sidebar on the left.

> it avoids the back-and-forth between mouse and keyboard.

there is no back and forth: one hand's on the keyboard and the other on the mouse: steady positions :) That's why a single-handed (custom) keyboard shortcut would be useful; the example I gave is not.

**Comment by josh-berry** [comment]
Ah, I see. So without #125 and/or #169, you'd prefer to use the browser tab bar to choose which tabs to stash.

I think you could actually use the "Stash the active tab" keyboard shortcut (Ctrl+Alt+W or Ctrl+Shift+W on Mac) to good effect here. You can accumulate tabs in a new temporary group using this keyboard shortcut, then open the Tab Stash UI to move them where you want them together as a group.

The selection in the Tab Stash UI is distinct from the browser selection, since it's not possible in some cases to change what is selected in the browser without also switching tabs. Selection is also limited to a specific instance of the Tab Stash UI for a similar reason--it would be possible to select unstashed tabs in one window and then, without realizing it, operate on those tabs from another window. I think either scenario would lead to users feeling surprised and/or frustrated.

So I think the two options here are:

1. Use the "Stash active tab" keyboard shortcut as mentioned above
2. Implement #125 so the Tab Stash UI itself can show which tabs are in which containers

But let me know your thoughts.

**Comment by WebMechanic** [comment]
I believe `Ctrl+Alt+W` could indeed be a workaround. 
I didn't know it exists, 'cos i frankly haven't read the [Tips and Tricks](https://josh-berry.github.io/tab-stash/tips.html) earlier.
Maybe you can include available shortcuts to their menu item so they're no secret from people that don't RTFM 😇 -- and to conform with good UI practice.

It seems like `Ctrl+Alt+T` doesn't work for me (Win10) but would be even more beneficial. Maybe I'm misunderstanding its workings. From a Ctrl+Click multi selection, only one of these (highlighted) FF tabs is stashed in the (new) group, the others simply disappear. I tried FF "Reopen Closed Tab" but that revealed some totally different tabs I x-ed out earlier.
I need to play with this to make sense of it :D never mind.

**Comment by josh-berry** [comment]
I haven't checked this in a while but I think `Ctrl+Alt+T`'s behavior is tied to whatever settings you have configured for the toolbar button. (And this apparently isn't documented on the website... I really need to update it, hah.) So if you've changed the toolbar button to do something other than the default of "stash all tabs and show the sidebar", `Ctrl+Alt+T` will change as well.

Has `Ctrl+Alt+W` been working well for you? Let me know if you have any more questions!

**Comment by WebMechanic** [comment]
> Has `Ctrl+Alt+W` been working well for you? Let me know if you have any more questions!

Hey, sorry for the delay ... and Happy New Year! 😁

Yes, `Ctrl+Alt+W` proved to be useful, thank you. 
I have to click each tab separately which causes it to reloads/refresh, a step I actually wanted to avoid and just stash them as part of a selected group.
I haven't configure anything so I have no idea what `Ctrl+Alt+T` would do. I'm a bit reluctant to try and need to test this in a separate FF session with a few tabs one day.

**Comment by josh-berry** [comment]
Glad to hear it, and Happy New Year to you as well! 🎉 

FWIW, I just checked and `Ctrl+Alt+T` does follow whatever the toolbar button is configured to do (by default, stash all tabs and show the sidebar). Hope that helps and thanks for letting me know `Ctrl+Alt+W` worked for you!
