### ISSUE TITLE
Send Tab to Specific Group

### ISSUE THREAD

**Issue by arandorion** [josh-berry/tab-stash#18]
There's a feature OneTab has that would be excellent in Tab Stash. I used it a lot in OneTab, and now that I've switched to Tab Stash, I miss it.

It would be cool to have the ability to send a tab (or selected tabs) to a specific group. For example, if a few days ago I created a group named "foo" and I now have a tab I would like to add to that group, it would be cool to have a contextual menu option like "Send This Tab to Group >>". When you click on that menu item, it opens a hierarchal menu to the side listing all of your groups. I could select "foo", and it would send that tab to my group named "foo".

**Comment by josh-berry** [comment]
Are you looking specifically for context menu support, or are you just looking for some way to save to a particular group?

If you're looking to save to a particular group, you can do this today using the sidebar. Press Ctrl+Alt+S (or Ctrl+Shift+S on Mac) to open the sidebar, find the group you want in the list, and click one of the "Stash..." buttons underneath the group's name. (These are the buttons with blue backgrounds when you hover over them.)

As of Firefox 64, you can even Shift/Ctrl- (or Cmd-) click multiple tabs in the Firefox tab bar to select which tabs you want to add to the group, and then click the "Stash all (or selected)..." button to save only the selected tabs.

Hope this helps!

**Comment by arandorion** [comment]
That method will work just fine for me. Thanks for the info!
