### ISSUE TITLE
Red X button does not remove tab from tabstash sidebar.  Intermittent :(.

### ISSUE THREAD

**Issue by Yagoth** [josh-berry/tab-stash#181]
### System Details

- **OS Version:**
Windows 10 20H2
- **Browser Version:**
94.0.2
- **Tab Stash Version:**
2.10.1

**Installed Browser Extensions:**
Cookie Manager
Feedbro
KeepassXC-Browser
OneTab(Temporarally while I see if Tab-stash works)
Privacy Badger
TinEye Reverse Image Seach
uBlockOrgin
Video Speed Controller
VT4Browsers

**Computer:**
16GB ram, 6 Core Intel Core i7-8750H, GTX 1050ti

### Describe the Bug
Click thing the red x does not remove the saved tab from the sidebar

### Expected Behavior
The tab should be removed from tabstash

### Steps to Reproduce
tabstash sidebar is open on browser start
left click red x on the tabstash sidebar

### Impact
High, Unable to remove tabs from tab stash

### Additional Details
This is the same system I was having(then resolved) issue #177 on.
Issue is intermittent:(.  Restart Firefox Without Saved Session Data  seems to fix the issue for a while, but then it returns.

![Tab stash close tab issue](https://user-images.githubusercontent.com/8422621/144544852-03da5faa-e71b-4eef-9200-f5a23197b614.PNG)

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, sorry for the trouble and thanks for the bug report and the error logs.

Did these error messages come from the background page or the UI itself? If they came from just the UI itself, are you seeing any error logs in [the background page](https://github.com/josh-berry/tab-stash/wiki/Collect-Error-Logs#to-collect-logs-from-the-background-page-tab-stash-sidebar-or-tab-stash-popup)?

I have seen an issue like this once before, but only in development and a few releases ago (I *thought* I had fixed it at the time...). The issue at the time was that Firefox was closing the connections of ALL open Tab Stash UIs to the Tab Stash background page any time any ONE of the UIs were closed. I'm wondering if this is a recurrence of or similar to that bug, so here are a few questions for you:
* What variants of the Tab Stash UI do you typically use? (Tab? Sidebar? The experimental popup view?)
* Have you ever/do you typically have more than one instance of the UI open at a time?
* Do you use multiple browser windows or do you typically keep everything in the same window?

And here are a couple of things to try to resolve the issue the next time it happens, in order from least to most disruptive. Do any of these help, even temporarily?
1. Reload the Tab Stash tab (if you're using the tab version of the UI)
2. Close and re-open the UI (sidebar/popup)
3. Disable and re-enable the Tab Stash extension
4. Restart the browser (just a normal restart without clearing saved session data)

Let me know what you find and we can take it from there. Thanks!

**Comment by sbn-purchark** [comment]
I'm having the same issue (2.10.1), 'opening tab and delete' doesn't work either (probably anything that requires XHR). Very frequent, pretty much every time I go to remove something it doesn't work.

- Using the sidebar (only)
- Only one browser window (always).
- All it takes now is to close the sidebar and re-open (2.10 required re-enabling extension or restarting browser IIRC)
- I had to downgrade to 2.9 and then I waited extra time before I finally upgraded to 2.10.1.

Last I checked (2.10) the background page was creating errors. I'll open the debugger and check again with 2.10.1...

[tab_stash_console_log.txt](https://github.com/josh-berry/tab-stash/files/7700107/tab_stash_console_log.txt)

The other annoyance going to 2.10 is losing all the favicons. Not a big deal.

Thanks for the best extension! I will be responsive to anything you need to help fix this. I am watching this thread.

**Comment by sbn-purchark** [comment]
Additional logs since it broke again on me. I cleared console each time, first is trying delete, second is the open & unstash action (which does open, but fails to unstash). 

[tab_stash_console_log-broke delete.txt](https://github.com/josh-berry/tab-stash/files/7708042/tab_stash_console_log-broke.delete.txt)
[tab_stash_console_log-broke yellow button.txt](https://github.com/josh-berry/tab-stash/files/7708047/tab_stash_console_log-broke.yellow.button.txt)

**Comment by josh-berry** [comment]
@sbn-purchark Thanks, the logs helped a lot--I can see what's going wrong. It's possible/likely the same issue is causing your favicon problem as well. Does restarting the browser improve things at all or is the problem just as bad as before?

**Comment by sbn-purchark** [comment]
I think maybe it breaks some time after a browser restart, but closing and re-opening the sidebar is enough to get it working for the rest of the day/session. At least my experience so far.

As far as the favicons, they were lost on the 2.9 to 2.10.1 transition, but they are coming back (and being remembered) for anything I re-open. I have way too many stashed tabs to go through opening them all, I need to do some major cleanup.

**Comment by sbn-purchark** [comment]
Experience has changed, it broke several times yesterday in a single session. Each time I just closed/re-opened the sidebar. I'm going to disable some extensions that have some form of tab/link management and see if it makes a difference. I'm down to only tab stash, ublock origin, privicy badger, and bitwarden.

**Comment by josh-berry** [comment]
Got it, thanks for the update. I doubt it’s related to another extension, but if you DO notice a difference with other extensions turned off, that would be useful info.

There are quite a few oddities in how different extension pages (e.g. Tab Stash’s UI and background pages) communicate with each other, so it seems possible that either there’s a bug/weird behavior in Firefox that’s changed recently that is causing this, or there’s something I missed in my own understanding of how all this is supposed to work.

Either way, I have an idea of how to fix it, or at least work around it so it becomes less noticeable/corrects itself. I’ll try to get something in for the next release.

**Comment by sbn-purchark** [comment]
I was about to report that it seemed like it started breaking more with fewer extensions enabled, but it's probably just down to my usage patterns. It was fine the whole time I held onto 2.9, wasn't until I installed 2.10.1 that the problem occurred.

Just found out... disabling/re-enabling the extension won't fix it. I would think re-enabling the extension would be enough to refresh whatever is wrong with it.

I've noticed that it will often not be working after a browser start (in the morning). I have a feeling it was broken BEFORE I shutdown my computer and the problem persisted over a restart just like how it's persisting over a re-enabling of the extension.

Going to test with "open previous windows and tabs" turned off, though the sidebar is staying open across a restart.

**Comment by sbn-purchark** [comment]
Just noticed a (maybe) related thing that also happens sometimes. I looked over and saw an "unstashed" tab that I had closed some time ago. Unlike back in 2.9, I was able to delete it this time, usually needed to restart the browser to get rid of those, there can also be several at once.

Don't forget I don't allow hidden tabs, so stashed or closed tabs are gone (except in the list of recently closed tabs that FF keeps).

I cleared the log before I deleted it...
[Console clog - Orphan tab.txt](https://github.com/josh-berry/tab-stash/files/7740097/Console.clog.-.Orphan.tab.txt)

**Comment by josh-berry** [comment]
> Just noticed a (maybe) related thing that also happens sometimes. I looked over and saw an "unstashed" tab that I had closed some time ago. Unlike back in 2.9, I was able to delete it this time, usually needed to restart the browser to get rid of those, there can also be several at once.

@sbn-purchark This latest log looks like a different (known) issue with Firefox—can you try the procedure here and see if it helps: https://github.com/josh-berry/tab-stash/wiki/Restart-Firefox-Without-Saved-Session-Data

I'll be curious to see if clearing the session data also helps with the open/delete and/or favicon issues. (I doubt it will, but if it does/doesn't, that's useful info as well.)

**Comment by sbn-purchark** [comment]
> Going to test with "open previous windows and tabs" turned off, though the sidebar is staying open across a restart.

Done that (permanently for the time being) before that even happened. You read my 1st reply right? Would it be better if I edit on additional things when close together in time?

So far no issue with it breaking and I've done a couple browser restarts since then.

**Comment by sbn-purchark** [comment]
1. It was still working fine when I shutdown last night.
2. Started-up this morning, forgot to immediately test it, did a small FF update and restarted FF.
3. Broken, but 
4. Restarted FF again
5. Working
6. Restarted FF 3 more times
6. Still working
7. Closed FF
8. Restarted PC
9. Now it's not working. Let me try that again...
10. Same result.

There is an extra bit of delay starting FF on a fresh boot, so maybe that is breaking it. Playing some more I managed to break it a couple more random times simply by restarting only FF.

Stashing tabs actually works fine regardless, what's different with its function?

**Comment by minimalz** [comment]
Also having the same issue, "open tab and delete" or "open all tabs and delete group" doesn't remove the tab or group. I don't use the sidebar, only a new tab.  I'm new to this extension starting with 2.10.1.

**Comment by josh-berry** [comment]
@sbn-purchark 

> >  Going to test with "open previous windows and tabs" turned off, though the sidebar is staying open across a restart.

> Done that (permanently for the time being) before that even happened. You read my 1st reply right? Would it be better if I edit on additional things when close together in time?

No, my bad, I didn't read closely enough.

> Stashing tabs actually works fine regardless, what's different with its function?

Deleting something will save it to the deleted items DB on your local computer, and this is the part that's failing. Basically the Tab Stash UI is trying to tell the Tab Stash background process, "hey, please save this to deleted items" and Firefox is saying to the UI, "actually you're not connected to the background process at all". The UI should ALWAYS be connected to the background process, so exactly why this is happening is still a bit of a mystery to me. 

I actually saw the issue myself last week on a completely fresh install of Firefox and Tab Stash. So I don't think it's related to any particular setup or environment or anything else--just seems like a bug in either Firefox or Tab Stash. (There are a couple of known issues in Firefox itself in this area, but I'm not sure yet if we're hitting one of those.)

Fortunately, the fix is (I hope) fairly simple--teach the UI to automatically reconnect if it notices the connection was lost. But until I can get the fix out, closing/opening the Tab Stash UI should temporarily resolve the issue.

**Comment by josh-berry** [comment]
@minimalz Oops, the above should apply to you too--if closing/opening the UI doesn't help, though, please share error logs and I'll take a look!

**Comment by sbn-purchark** [comment]
For me, having a favicon or not makes no difference. Right now any page that has not been loaded since the 1.10.1 update has the generic tab icon on it.

I just read something about background pages that they can run in a couple modes; one allows the browser to start & stop it, the other where it's always running. Is yours set to allow the browser to stop it whenever it wants?

**Comment by josh-berry** [comment]
> I just read something about background pages that they can run in a couple modes; one allows the browser to start & stop it, the other where it's always running. Is yours set to allow the browser to stop it whenever it wants?

No, for a number of reasons, it is a persistent background page. (One such reason is to keep these connections open...)

**Comment by josh-berry** [comment]
This should be addressed in the next release (or at least, worked around). If the UI determines that it's been disconnected from the background page, it will try to reconnect and refresh its state.

If after the next release, you continue to see this, please do open another bug!
