### ISSUE TITLE
Show number of stashed tabs per group

### ISSUE THREAD

**Issue by bantern** [josh-berry/tab-stash#185]
### Problem Statement

I would like to see the number of stashed tabs contained within a group. 

As the add-on exists now, for groups that contain a large amount of stashed tabs where the number may not be apparent, if I wanted to know how many were in a group I would have to manually count them out. This takes time and is annoying. 
Currently, when the search bar within Tab Stash is empty, it will show the amount of groups and tabs collectively within those groups, which makes sense for a search, but there is no indicator that I've found to show how many tabs are stashed in an individual group.

Ultimately, though, the information would just be nice to have.

### Preferred Solution(s)

My ideal solution would be to have the number of tabs shown on the right end of the title bar of groups. If groups in the sidebar are collapsed, it should reside just inside the carat, if opened just have the number there. Displaying only the number with an on-hover tooltip, which could show additional info, would be great as well i.e. "There are X loaded and Y unloaded tabs stashed within group Z".

### Alternative Solution(s)

An alternative solution, have that same information as provided in the previous example shown just under the title bar of a group as header of sorts, also should be visible from collapsed view.

### Additional Context

N/A

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, thanks for the feature request. I think the tooltip approach is certainly doable. I'll have to see if there's a good place for it in the UI proper though--I want to be really judicious about what gets added to the UI proper so that it doesn't become cluttered/distracting.

In any case, I'll keep this in mind for a future release!

**Comment by unbob** [comment]
Yes, please implement this request!
My preferred solution is to have the number of tabs shown on the right end of the title bar thus: (xx Tabs). This would be neither cluttered or distracting.
I typically have hundreds of open tabs and therefore manually counting them is not an option. I always want know how many tabs I have open.
Maybe I'm wrong, but this seems like a pretty simple enhancement.  Thanks Josh for creating Tab Stash!

**Comment by josh-berry** [comment]
Thanks to @KerfuffleV2's efforts, tab stats (open/stashed tabs, etc.) will be visible in tooltips in the next release!
