### ISSUE TITLE
Color code loaded and unloaded tabs within a stash group.

### ISSUE THREAD

**Issue by bantern** [josh-berry/tab-stash#186]
### Problem Statement

The problem is that I am unable to see which tabs are currently loaded or unloaded within a stash group as per 'Tab and Memory Management' settings, and I would like to know this in an easily understandable and quick way.

### Preferred Solution(s)

As the 'Unstashed Tabs' group is color-coded blue, it would be nice if maybe unloaded tabs were grey/red/yellow/blurple. Hopefully this is the easiest solution. 

### Alternative Solution(s)

Having some sort of icon next to the left of the favicon which indicates what state the tabs are in within a group.

### Additional Context

Submitted alongside feature request #185 as I didn't want to put both in one request, but they're both born of the same desire to have more information readily available the the user.

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Thanks for the feature request. I'll have to put some thought into the best way to present this info since there are a few different combinations that need to be handled. But I'll keep this in mind for a future release!

**Comment by josh-berry** [comment]
I forgot this issue was open when I released 2.11, but in 2.11, unloaded tabs are now dimmed so you can tell them apart from loaded tabs. I hope this helps!
