### ISSUE TITLE
Subfolders

### ISSUE THREAD

**Issue by ejm554** [josh-berry/tab-stash#187]
Hello. It would be nice to have the option of subfolders. Is this feasible?

**Comment by josh-berry** [comment]
Hi, thanks for reaching out! Your issue is already covered/duplicated by another issue, so please take a look at the original (and subscribe if you want updates):

* #14

**Comment by ejm554** [comment]
Oh cool. Thanks! I search for "subfolder" before I posted my issue, but I didn't see (or didn't register) the one you mentioned.
