### ISSUE TITLE
Congrats

### ISSUE THREAD

**Issue by AussieGit** [josh-berry/tab-stash#189]
Tab-stash has always been  in my top 3 MUST install ASAP in any new PCs and now some recognition from MakeUseOf's  Most Innovative Extensions 2021     https://www.makeuseof.com/mozilla-lists-most-innovative-firefox-extensions-2021/

Much deserved recognition

**Comment by josh-berry** [comment]
Awesome, this made my day! Thanks so much for sharing! ❤️
