### ISSUE TITLE
Select and Move Multiple Saved Tabs

### ISSUE THREAD

**Issue by arandorion** [josh-berry/tab-stash#19]
Sometimes I need to move tabs from one group to another. Right now, I'm having to drag and drop them one at a time. It would be helpful to be able to select multiple saved tabs then drag and drop them to another group.

**Comment by arandorion** [comment]
I just learned that the tabs are stored as bookmarks. I just used the bookmark manager to select and movie multiple tabs from one group to another. Will this cause any problems in Tab Stash or is it a good way to accomplish the task?

**Comment by josh-berry** [comment]
Yes, you can safely use Firefox's built-in bookmark manager (or any other extension that interacts with bookmarks)—Tab Stash watches for and is careful to respect any outside changes made to the bookmarks in your stash. More info here: https://github.com/josh-berry/tab-stash#alternate-ways-to-manage-your-stash
