### ISSUE TITLE
FR: Don't close extension tab itself, at least when it pinned

### ISSUE THREAD

**Issue by psydvl** [josh-berry/tab-stash#191]
### Problem Statement
I often open list of stashed tabs to quickly view and reopen some.
For now, if I click stashed URL, `Tab Stash` tab instantly closed even if it pinned.
So I forced to open them by clicking on wheel (also known as third button action).
It's uncomfortable.

### Preferred Solution(s)
Keep open pinned tab for this extension after open URL

### Alternative Solution(s)
Add "Don't close after open URL" option in settings or "Don't close this extension pinned tab after open URL" 

### Additional Context

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Try "Ctrl+Click"ing or "Cmd+Click"ing (if on Mac) the tab instead of just clicking it--this will open the tab in the background behind the Tab Stash tab, so you can open a few at a time and then switch to the one you want. Tab Stash follows the same conventions as your browser in this regard, and Ctrl+Click is hopefully less awkward than middle-clicking.

**Comment by psydvl** [comment]
I'm transferring from OneTab, and it has next behavior:
OneTab tab never closed: it brings focus on fresh restored tabs, but its main tab keeps being open. You can return to it any time.

Stash Tab tab in its turn immediately closed after restore tabs (or tabs group) and to reopen it you need right-click on extension label and then select "Show Stashed Tabs in a Tab".
And I don't really understand part about "follows the same conventions as your browser in this regard"...

**Comment by psydvl** [comment]
Currently, not reproduced.
Not sure for reason, but I'm closing this for now.

**Comment by josh-berry** [comment]
Got it, thanks, if you're able to reproduce it, please feel free to re-open!

> And I don't really understand part about "follows the same conventions as your browser in this regard"...

I meant that tabs in Tab Stash should behave similarly to links in your browser: if you click on a tab, it will open the tab and switch to it (so the opened tab is the active tab). But if you Ctrl+Click or Cmd+Click on it, the tab will be opened in the background (i.e. Tab Stash should stay as the active tab). Sorry for the confusion!
