### ISSUE TITLE
disable sidebar for new windows

### ISSUE THREAD

**Issue by exekutive** [josh-berry/tab-stash#192]
Whenever I click a link which opens a new window, the tabstash sidebar is automatically displayed in it. Is there a way to disable this? It's kind of annoying.

Firefox 95 on Mac

**Comment by josh-berry** [comment]
This is entirely up to Firefox, not Tab Stash--if you have a sidebar open in another window somewhere, Firefox will sometimes decide to open it in whatever new windows you create. So I would suggest double-checking if the sidebar is already open in some other window and closing it there.

Let me know if this helps!

**Comment by exekutive** [comment]
No. I don't have the sidebar open anywhere else. 
It happens every single time I right-click Firefox in the dock, and choose "New Window"

**Comment by josh-berry** [comment]
Please give the following a try:

1. Open a new window
2. Close the sidebar in that window
3. Completely quit Firefox — on Windows/Linux, choose “Exit” or “Quit” from the Firefox menu in the upper-right corner of the window; on Mac, choose “Quit” from the “Firefox” menu in the Mac menu bar
4. Restart Firefox and see if the sidebar stays closed
5. If it still opens automatically, try [restarting Firefox without saved session data](https://github.com/josh-berry/tab-stash/wiki/Restart-Firefox-Without-Saved-Session-Data).

If none of the above helps, then I suggest reaching out to Mozilla for help—Firefox only allows extensions to open/close the sidebar under very very limited circumstances, and opening/closing windows is not one of them, so there’s not really anything Tab Stash can do here.

But I hope this helps, let me know how it goes!

**Comment by exekutive** [comment]
That did it.
I shut down Firefox, then restarted it.
The sidebar opened. I closed the sidebar and shut down FF again.
The next time I restarted the sidebar stopped opening automatically.
I guess it true ... when in doubt ...  turn it off and then back on ... and then off and back on, again. LOL
Thanks.
