### ISSUE TITLE
Tab Stash does not save Firefox Multi-Containers tab assignment

### ISSUE THREAD

**Issue by ISO-JH** [josh-berry/tab-stash#195]
### Problem Statement
I use Firefox multi-containers extension to browse in the same Firefox window my different tabs and I have different containers opened for each of my clients (generally 3 to 4 tabs assigned to 3 to 4 containers).
Tab Stash can allow me to save all my tabs for the weekend, so that I use Firefox during my time off without seeing my work tasks/new requests until monday, and then restore my stash on monday morning.
But the fact that Tab Stash does not save containers assignment does not allow me to do this.

### Preferred Solution(s)
Just keep each tab assignment to its container.

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, thanks for the feature request! I'll keep this in mind for a future release.

This is closely related to #125, so you might want to read through some of the discussion there as well. (The short version is, Firefox doesn't provide a way to store container info for a bookmark, and Tab Stash would need to ask for more permissions to be able to use containers, but there are some workarounds that might work.)

**Comment by ISO-JH** [comment]
Thanks Josh for your reply.
I think you can close my feature request as it is indeed related to the #125 ! ;)

Thanks for your work on this extension.
Best Regards !

**Comment by gshpychka** [comment]
@josh-berry this is not a duplicate, though, since this issue talks about restoring to the appropriate container, not just displaying a visual container indicator. Is there a tracking issue for thr former?

**Comment by josh-berry** [comment]
@gshpychka Yes, see #104. Remembering a container along with the site unfortunately isn't possible because there is no way for Tab Stash to attach any additional information to a bookmark beyond its URL.

**Comment by FabianoLothor** [comment]
Hey guys, any update on this?

Tabs Aside does a good job with containers.

I saw that Tab Stash sometimes loads the stashed tabs in the right container, but the behavior is lost, I wasn't able to identify what makes the behavior lost the reference for the right container.

Do you know what happens?
