### ISSUE TITLE
Change name link                                                                                         

### ISSUE THREAD

**Issue by Tetsuya00X** [josh-berry/tab-stash#198]
I'm using Tab Stash for bookmark manager. But If I want to save a image link, my problem is how can I seach. For example, I saved this image from Star Trek recently:

https://i.pinimg.com/originals/82/a7/3e/82a73e9b0d9632d23866c1e36a3f9778.jpg

It's impossible to remember it.

Is it possible put a name in a link to better save/management/search?

**Comment by josh-berry** [comment]
Hi, it's not possible directly in Tab Stash at the moment, but you can edit the bookmark created by Tab Stash in the Firefox bookmarks editor, and Tab Stash will remember/respect whatever name you chose.

There is a feature request #168 open for this, feel free to upvote if you'd like to see this implemented and add any additional comments you have over there!
