### ISSUE TITLE
Conflict with "Default Bookmark Folder" extension

### ISSUE THREAD

**Issue by cronco** [josh-berry/tab-stash#199]
### System Details

- **OS Version:** Mac OS Monterey
- **Browser Version:** Firefox Nightly 98
- **Tab Stash Version:** 2.10.1

**Installed Browser Extensions:**

- 
- 

### Describe the Bug

This might be obvious, as that extension is doing what it is supposed to do, but I forgot I had it installed. TL;DR: [Default Bookmark Folder](https://github.com/teddy-gustiaux/default-bookmark-folder) is an extension that allows you to modify the behaviour of the bookmarking system so that either you use the same folder to bookmark, or default to the last folder used. This is the option that I had selected, and when I tried to stash anything, the UI would show tabs quickly appearing in the stash before being moved to the previously used bookmark folder. 

### Expected Behavior

I would not expect stashed tabs to disappear, or to appear in the last used stash rather than the one I clicked in the UI.

### Steps to Reproduce

1. Install [Default Bookmark Folder](https://addons.mozilla.org/en-US/firefox/addon/default-bookmark-folder/)
2. Set to default to "last used folder"
3. Try to stash a tab (or a selection)
4. See tabs quickly appearing in the folder before being moved to the previously used bookmark folder.

### Impact

I had forgotten about installing this bookmark and it took me a while to track down the source of the error. I remembered about it literally as I was coming to Github to write this issue. I think adding it to the conflicting addons wiki is enough of a resolution for this.

### Additional Details

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Thanks for the heads-up! I updated the wiki as you suggested.

**Comment by madeupname** [comment]
I just got hit with this and didn't realize this was a conflict. It just looked like all my tabs were closed and lost with nothing stashed. Through #123 I learned they are hidden, which is a relief, if a slight pain to bring back.

But is it possible to detect if any conflicting add-ons are installed and throw an error? Understand I may be in the minority here.

**Comment by josh-berry** [comment]
> I just got hit with this and didn't realize this was a conflict. It just looked like all my tabs were closed and lost with nothing stashed. Through https://github.com/josh-berry/tab-stash/issues/123 I learned they are hidden, which is a relief, if a slight pain to bring back.

Sorry to hear that! An alternate way to bring back tabs that go missing due to being moved is to go into the Firefox bookmark editor, and drag the bookmarks back to a sub-folder underneath the "Tab Stash" folder. This is probably faster/less annoying than restoring hidden tabs one by one. But I'm glad you were able to get everything back in any case!

> But is it possible to detect if any conflicting add-ons are installed and throw an error?

Unfortunately there's not a good way to do this without requesting some (rather powerful) permissions from the browser to manage other installed extensions—permissions that, honestly, Tab Stash probably shouldn't have.
