### ISSUE TITLE
Move Unstashed Tabs to bottom.

### ISSUE THREAD

**Issue by Narga** [josh-berry/tab-stash#2]
Because the unstashed tabs are current tabs in browser. So when I open the Tab Stash on the sidebar, it displays as a long list, I must collape it by click on the right arrow.
Can you allow me move it to the bottom in the next update?

**Comment by josh-berry** [comment]
One thing I am considering for a future release would be to make Tab Stash remember which groups are collapsed and which aren't. If it remembers that the "Unstashed Tabs" group is collapsed, would this address your concern?

**Comment by Narga** [comment]
That is good solution.

**Comment by iPaulis** [comment]
That would be a good solution for me too, as I have so many unstashed tabs that the list is too long, so I can't see my stashed tabs without scrolling. 
Or let reorganize the unstashed tabs group the same way as the other groups to move it to the bottom. Ideally both options would be great.

Thanks for the addon, it is awesome.

**Comment by josh-berry** [comment]
Tab Stash 2.4 (just released) will now remember when you have collapsed individual groups, including the Unstashed Tabs group. Hopefully this makes your stash list easier to view. :)

**Comment by iPaulis** [comment]
Im in Version 2.10.1 and this solution stopped working. I mean, it still remembers the collapse state of all my custom groups, but it stopped remembering the "Unstashed Tabs" group's collapse state. Now it is uncollapsed by default every time I open the browser. Then if I collapse it and refresh the tab, it remembers, but if restart firefox it goes to default uncollapsed again.

It is creating the original problem this feature was introduced to solve, the unstashed tabs list is so long that the stashed tabs are unconfortable to use.
Any idea on how to solve this?

**Comment by josh-berry** [comment]
Can you please open a new issue rather than leaving a comment on an old issue? Otherwise it becomes impossible for me to track what still needs attention. Thanks!
