### ISSUE TITLE
Ask for confirmation before deleting a tab stash

### ISSUE THREAD

**Issue by GithubUser5462** [josh-berry/tab-stash#20]
If you delete a tab stash the tabs are gone forever with no option to undo the action.
So i think it would be sensible to have a confirmation prompt before deleting a tab stash in order to avoid any unintentional loss of data.

**Comment by josh-berry** [comment]
I agree, although I think having some type of trash-can mechanism would be helpful because it would be less obtrusive while still providing people a way to get back something accidentally deleted. I'll keep this in mind for a future release!

**Comment by ipalmieri** [comment]
I second this. Just lost 20+ saved tabs with an accidental click.

**Comment by ipalmieri** [comment]
I second this. Just lost 20+ stashed tabs after an accidental click.

**Comment by ochen1** [comment]
I agree, though personally I'd prefer a overlay on top of the stack with a button to confirm the deletion, rather than a popup that appears in the middle of the screen.

**Comment by mwrsa** [comment]
Same result as ipalmieri - that's why I ended up here.
First I hit the wrong button by accident to stash all open tabs and then ofc. I wanted to delete the group I just created by accident. What a shame that I only realized all tabs were closed after I deleted the whole group -.-

I think I did a whole backup only yesterday, which might save my day (and all of 56 tabs) :-(

**Comment by josh-berry** [comment]
This is at the top of my list, don't worry. :) I too have deleted things by mistake (it seems to happen about once a month for me >:/), and I understand how frustrating it can be.

I've prototyped a few different approaches to this over the last few months, and the latest attempt is finally shaping up into something I think will work nicely. I can't promise any specific timing, but I hope to have it ready for you soon!

<img width="223" alt="Screenshot 2020-10-23 235736" src="https://user-images.githubusercontent.com/1203893/97070227-a2267980-158b-11eb-83a6-e0db95c2feb2.png">

**Comment by josh-berry** [comment]
In the next release of Tab Stash, deleted items will be saved locally on your computer. Unfortunately they cannot be synced between browsers due to the limited amount of storage that Firefox Sync offers to extensions (but I can't complain, since they give it to everyone for free).

When you delete an item, an unobtrusive "Undo" notification will be shown which you can use if you make a mistake, and you will be able to use the new "Deleted Items" page to search and recover things that may have been deleted a while ago.

Enjoy!

**Comment by mwrsa** [comment]
Closed maybe, but still worth a massive **thank you**! Will check it out as soon as it's out.

**Comment by jsuprock-netspi** [comment]
> In the next release of Tab Stash, deleted items will be saved locally on your computer. Unfortunately they cannot be synced between browsers due to the limited amount of storage that Firefox Sync offers to extensions (but I can't complain, since they give it to everyone for free).
> 
> When you delete an item, an unobtrusive "Undo" notification will be shown which you can use if you make a mistake, and you will be able to use the new "Deleted Items" page to search and recover things that may have been deleted a while ago.
> 
> Enjoy!

Where is the "Deleted Items" page you are speaking of? I'm using Firefox and I can't find it. Thanks.

**Comment by josh-berry** [comment]
@jsuprock-netspi It's in the Tab Stash menu—open the Tab Stash UI and click the menu icon next to the search bar at the top of the sidebar/page, then choose "Deleted Items...".

<img width="162" alt="Screenshot 2023-09-13 at 11 44 07" src="https://github.com/josh-berry/tab-stash/assets/1203893/ed352470-b1b0-4bf3-8113-32ca294f5c37">

**Comment by jsuprock-netspi** [comment]
Josh, thanks so much! I really needed it.

From: Josh Berry ***@***.***>
Date: Wednesday, September 13, 2023 at 2:44 PM
To: josh-berry/tab-stash ***@***.***>
Cc: John Suprock ***@***.***>, Mention ***@***.***>
Subject: Re: [josh-berry/tab-stash] Ask for confirmation before deleting a tab stash (#20)

@jsuprock-netspi<https://github.com/jsuprock-netspi> It's in the Tab Stash menu—open the Tab Stash UI and click the menu icon next to the search bar at the top of the sidebar/page, then choose "Deleted Items...".
[Image removed by sender. Screenshot 2023-09-13 at 11 44 07]<https://user-images.githubusercontent.com/1203893/267757425-ed352470-b1b0-4bf3-8113-32ca294f5c37.png>
