### ISSUE TITLE
High CPU usage - invalid Firefox saved session data

### ISSUE THREAD

**Issue by josh-berry** [josh-berry/tab-stash#201]
### Describe the Bug

There are a few bugs within Firefox which can lead to inconsistencies in what Firefox reports to Tab Stash through the extension APIs. (For example, #188.)

When Tab Stash detects such an inconsistency, it will try to refresh its information from the browser. However, if inconsistencies are happening consistently (ha) and repeatedly, Tab Stash may repeatedly refresh itself, resulting in high CPU usage.

This can sometimes happen even if a user isn't doing anything (e.g. it could happen in one of Tab Stash's background tasks).

### Expected Behavior
Tab Stash shouldn't use excessive CPU for refreshing its state. Alternatives could involve limiting the number of retries, showing an error to the user, etc.

### Workaround
Following the steps here will usually resolve the issue (at least temporarily): https://github.com/josh-berry/tab-stash/wiki/Restart-Firefox-Without-Saved-Session-Data

### See also
* #172 - another reason for high CPU usage unrelated to this issue

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by svandragt** [comment]
> When Tab Stash detects such an inconsistency

How can it be verified this is what's happening? via `about:performance`?

**Comment by josh-berry** [comment]
At the moment, there's not a great way to verify which of the two issues is causing high CPU, but `about:performance` will certainly tell you if Tab Stash is the cause of high CPU (for any reason). If you really want to dig into Tab Stash's inner workings, you could profile whichever page it is (background or UI) and look at which functions are taking up the most CPU time. (But I expect people who are not already web developers won't want to go down that path / would find it difficult.)

The next release will warn the user about inconsistencies and suggest next steps, and it will also retry less and less frequently if the problem repeats (so the high CPU should go away in the first place). So this should become more clear.

**Comment by naugtur** [comment]
I ran perf on it today and the only function I was able to find in all perf traces was `gc()` https://github.com/josh-berry/tab-stash/blob/7670feb1b1be99e34cb42d13d4157b36b4d0b7bc/src/model/bookmark-metadata.ts#L33

It seems it's being called all the time. It might be related to cleaning up deleted items, but I've not been deleting any new items and the only bulky action I did was stashing a few hundred tabs all at once and closing their tabs. 
Tried the reinstall trick but doesn't seem to have helped.
Anything else I can do, I'm happy to help. (this is the most promising tab manager ever, I want to keep using it)

**Comment by josh-berry** [comment]
> I ran perf on it today and the only function I was able to find in all perf traces was `gc()`

Ohhh yikes, this sounds like a new one. That particular `gc()` function actually isn't related to deleted items at all. Did you happen to save the perf traces, and if so would you mind opening a new bug and attaching them?

**Comment by josh-berry** [comment]
hm... I may have spoken too soon, it might be related to #172 (deleted items) after all. I just double-checked and both bookmark metadata cleanup and deleted-item cleanup are triggered in the same code path. So you can attach traces to #172 instead.

Still, this is a good find. It's very odd that code which is supposed to execute only once a day and on browser restart is causing such high load.

**Comment by naugtur** [comment]
I didn't save the trace after I concluded it's the same issue ;( 
It was full invocations with callstacks starting at this function. I'll attach saved perf traces as soon as I reproduce again.

**Comment by josh-berry** [comment]
The above commit, along with some additional work to raise errors and provide troubleshooting info to users, should help to reduce the CPU usage and let users know when Firefox gets into a bad state.

This will go out in the next bugfix release, so I’ll go ahead and close this one out. (Of course, the other high-CPU issue #172 still remains, I’ll work on that one separately.)
