### ISSUE TITLE
The URL http://about:blank causes the import process to end prematurely

### ISSUE THREAD

**Issue by desbest** [josh-berry/tab-stash#204]
### System Details

- **OS Version:** Windows 10
- **Browser Version:** Firefox 96.0.1
- **Tab Stash Version:** 2.10.1

**Installed Browser Extensions:**

- Optional
- 

### Describe the Bug

Importing a batch of URL's where one of them is `http://about:blank` causes the importing process to end prematurely.

### Steps to Reproduce

Try to import this

```
# Group 1
http://google.co.uk
http://bing.co.uk
http://about:blank

# Group 2
http://amazon.co.uk
http://ebay.co.uk

```
### Impact

This bug might seem trivial but for a Onetab user who is switching over to Tab Stash, if Firefox has bugs then sometimes tabs don't load properly when opened which will make the user's desired web page not opened with Firefox. When the user then brings their tabs to Onetab the `http://about:blank` URL will be saved to Onetab instead of the web page they were originally on. This will cause a problem in Tab Stash when dealing with exports in the Onetab format when the user is importing their onetab formatted export into Tab Stash.

### Additional Details
Optional

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Thanks for the bug report--I can see what you mean. It looks like Firefox itself is rejecting the bookmark creation (perhaps unsurprisingly, since it's not a valid URL).

For now the workaround is to remove the invalid URLs before importing, but Tab Stash really should be skipping over these URLs.

**Comment by josh-berry** [comment]
[note to self] Debug console output from repro:

```
Uncaught (in promise) Error: Invalid bookmark: {"title":"Importing...","type":1,"url":"http://about:blank","index":0,"parentGuid":"IwK3wBB9UKkk"} undefined

>>> new URL("http://about:blank")
Uncaught TypeError: URL constructor: http://about:blank is not a valid URL.
    <anonymous> debugger eval code:1
debugger eval code:1:1
```

**Comment by josh-berry** [comment]
This will be fixed in the next release!
