### ISSUE TITLE
Options to change behavior of toolbar buttons

### ISSUE THREAD

**Issue by RandomClaim** [josh-berry/tab-stash#21]
**Is your feature request related to a problem? Please describe.**
I would like to get more customization for the different buttons.

**Describe the solution you'd like**
Give options to:
- disable the button in the context menu and/or the url bar (this would be a nice solution about what I wrote in #16, at least for me )
- choose what the individual buttons should do on left/right-click (basically the options from the dialog menu and allowing to show the menu itself on click)

**Describe alternatives you've considered**
I don't know if stuff like that is achievable by CSS, but I think it would be nicer to have it easily available for anyone :)

**Comment by josh-berry** [comment]
Hi, thanks for the feature request! You can get rid of the URL bar button by right-clicking on it and choosing "Remove from Address Bar". It will then move to the little "..." menu nearby. (And if you later change your mind, you can right-click on the "Stash this tab" entry in the "..." menu to add it back.)

Regarding the behavior of the toolbar button, you can control whether it opens the sidebar, tab, or nothing (and just stashes your tabs). To change this setting, right-click the toolbar button and choose "Manage Extension" (Firefox's wording, not mine :/). This will get you to all the Tab Stash options (including the setting to change its behavior). If there are additional options you'd like for controlling this button, let me know.

There's not currently a way to get rid of (some of) the context menus, but I'll keep that in mind for a future release.

**Comment by RandomHam** [comment]
Hey, I didn't know some of that stuff is already possible. Sorry for the redundant requests and thanks for your patient answer!

I think I didn't made myself clear enough about the toolbar button tough. What I meant was options to only open the sidebar menu for example, without stashing any tabs.
Maybe this is just me but I prefer getting an overview first before I stash anything ^^'

**Comment by josh-berry** [comment]
My pleasure, and I'm glad you're enjoying it!

That is a great point about being able to get an overview before stashing anything. The way I personally have handled this is by customizing my Firefox toolbar to put the Sidebar button right next to the Tab Stash button, so if I want the overview I just click the sidebar button, and if I want to stash, I click the Tab Stash button.

But not everyone wants to have two buttons, and this is a very easy option to add to Tab Stash itself, so I'll keep this issue open to track it as an enhancement for a future release.

**Comment by AnttiBoman** [comment]
I definitely support the idea of an option in påreferences to make the toolbar button to open the menu instead of stashing all tabs. Today, once again, I meant to stash one tab but stashed all my tabs, and returning them wasn't fun, especially as some of them belonged to other multi-account containers. Otherwise, thanks a lot for a great extension!

**Comment by josh-berry** [comment]
Hi, thanks for the note—I definitely hear you that it's frustrating, and I've heard the same from others as well. If you could give a thumbs-up to the original post, that will help me keep track of how many people think this is important so I can prioritize accordingly. This is absolutely something I want to get to in a future release, it's just a question of when. :)

**Comment by josh-berry** [comment]
The next release of Tab Stash will give you the option to change the behavior of the toolbar button (choose what to stash, and which UI to open). Unfortunately there are some limitations in Firefox itself which make it hard for extensions to customize the icon in the address bar in a way that's easy for users to understand, but I hope having the toolbar button options will help.
