### ISSUE TITLE
"Unstashed Tabs" group is uncollapsed every time the browser launches

### ISSUE THREAD

**Issue by iPaulis** [josh-berry/tab-stash#210]
### System Details
- **OS Version:** Windows 10 21H2
- **Browser Version:** Firefox 96.0.1 .2 and .3 (64-bit) the bug persists in any latest browser version
- **Tab Stash Version:** 2.10.1

**Installed Browser Extensions:**
Many others, but the extension works fine in general, it is just the collapse state of the unstashed tabs.

### Describe the Bug
I'm in version 2.10.1 and the "Unstashed Tabs" group is uncollapsed every time the browser launches, I collapse it every time, and then forgets its state for the next time the browser launches. The extension still remembers the collapse state of all my custom groups, but it stopped remembering the "Unstashed Tabs" group's collapse state. It seems that the default state is uncollapsed every time I open the browser. Then if I collapse it and refresh the tab, it remembers, but if I restart firefox it goes to default uncollapsed again.

Being uncollapsed, the unstashed tabs list is so long that the stashed tabs are unconfortable to use.
Any idea on how to solve this?

### Steps to Reproduce
1. Open Firefox with a bunch of tabs or restore the tabs from a previous session
2. Show the stashed tabs in a tab
3. The unstashed tabs appear uncollapsed, collapse them
4. Restart firefox
5. Check the extension tab, the unstashed tabs appear uncollapsed

### Expected Behavior
To remember the collapsed state and stop uncollapsing on its own at every firefox session.

### Impact

I have tried collapsing the group from the tab view, from the sidebar view, refreshing the tabs, reopening the sidebar, etc.
It always remember correctly as long as the browser is opened, but if I close it and open Firefox again, the unstashed tabs are uncollapsed, and will keep that way unless I collapse them, but only during this firefox session, the next time it will default to uncollapsed again.

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Sorry about that! I was able to reproduce this on my local system as well, and I think I have an idea why this is happening. (Tab Stash tries to clean up metadata it doesn't need anymore once a day or on browser restart, and it seems like this process might be a bit overzealous. :/)

I'll see what I can do to fix it in the next release. Thanks for letting me know!

**Comment by josh-berry** [comment]
This will be fixed in the next release!
