### ISSUE TITLE
Error while fetching an original source: NetworkError when attempting to fetch resource.

### ISSUE THREAD

**Issue by desbest** [josh-berry/tab-stash#214]
### Crash Details

I'm using Firefox 97. 

The crash happened after upgrading from Tab Stash 2.10.1 to 2.10.2

See the atttached images.

>  NanoTimeoutError: favicons: Request "vmi5NA" timed out: `{"$type":"get","keys":["https://www.instagram.com/hazelmay38j/","https://www.instagram.com/ms.sethii/","https://www.instagram.com/xoxokayla.elizabeth/","https://www.instagram.com/babi.g0r3/","https://www.squarejawedwomen.com/jaw-shapes-types-and-classifications/","https://www.researchgate.net/figure/Diagram-of-facial-markings-used-to-isolate-the-jowl-treatment-area-A-Lateral-canthus_fig1_338492450","https://www.youtube.com/watch?v=IIKjKUz4lmw","https://archive.is/9QO3n","https://archive.is/eR5xt","https://archive.is/rXVb9","https://archive.is/Fyjad","https://www.ajournalofmusicalthings.com/drake-has-dropped-1-6-million-on-super-bowl-bets/","https://www.ajournalofmusicalthings.com/a-journal-of-musical-things-riaa-takes-swift-action-against-hitpiece-warns-any-potential-copycats-to-reconsider/?utm_source=dlvr.it&utm_medium=twitter","https://fluence.io/","https://www.ajournalofmusicalthings.com/about_alan_cross/","https://www.blogto.com/music/2022/02/…

> l index.ts:63

---

> 20:00:35.382 Uncaught (in promise) NanoTimeoutError: favicons: Request "vmi5NA" timed out: `{"$type":"get","keys":["https://www.instagram.com/hazelmay38j/","https://www.instagram.com/ms.sethii/","https://www.instagram.com/xoxokayla.elizabeth/","https://www.instagram.com/babi.g0r3/","https://www.squarejawedwomen.com/jaw-shapes-types-and-classifications/","https://www.researchgate.net/figure/Diagram-of-facial-markings-used-to-isolate-the-jowl-treatment-area-A-Lateral-canthus_fig1_338492450","https://www.youtube.com/watch?v=IIKjKUz4lmw","https://archive.is/9QO3n","https://archive.is/eR5xt","https://archive.is/rXVb9","https://archive.is/Fyjad","https://www.ajournalofmusicalthings.com/drake-has-dropped-1-6-million-on-super-bowl-bets/","https://www.ajournalofmusicalthings.com/a-journal-of-musical-things-riaa-takes-swift-action-against-hitpiece-warns-any-potential-copycats-to-reconsider/?utm_source=dlvr.it&utm_medium=twitter","https://fluence.io/","https://www.ajournalofmusicalthings.com/about_alan_cross/","https://www.blogto.com/music/2022/02/…

> l index.ts:63

---

> NanoTimeoutError: favicons: Request "PQopYA" timed out: `{"$type":"set","entries":[{"key":"about:devtools-toolbox?id=tab-stash%40condordes.net&type=extension","value":{"favIconUrl":"chrome://browser/skin/window.svg"}},{"key":"moz-extension://cad9cf7c-227e-43e0-a0ff-3a4f3e49e6e9/stash-list.html","value":{"favIconUrl":"data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxzdmcKICAgeG1sbnM6ZGM9Imh0dHA6Ly9wdXJsLm9yZy9kYy9lbGVtZW50cy8xLjEvIgogICB4bWxuczpjYz0iaHR0cDovL2NyZWF0aXZlY29tbW9ucy5vcmcvbnMjIgogICB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiCiAgIHhtbG5zOnN2Zz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciCiAgIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICAgeG1sbnM6c29kaXBvZGk9Imh0dHA6Ly9zb2RpcG9kaS5zb3VyY2Vmb3JnZS5uZXQvRFREL3NvZGlwb2RpLTAuZHRkIgogICB4bWxuczppbmtzY2FwZT0iaHR0cDovL3d3dy5pbmtzY2FwZS5vcmcvbmFtZXNwYWNlcy9pbmtzY2FwZSIKICAgaWQ9InN2ZzEwIgogICB2ZXJzaW9uPSIxLjEiCiAgIHZpZXdCb3g9IjAgMCA5NiA5NiIKICAgaGVpZ2h0PSI5NiIKICAgd2lkdGg9Ijk2IgogICBzb2RpcG9kaTpkb2NuYW1lPSJsb2dvLnN2ZyIKICAgaW5rc2NhcGU6dmVyc2lvbj0iMC45Mi4yIDVjM2U4MGQsIDIwMTctMDgtMDYiCiAgIGlua3NjYXBlOmV4cG9ydC1maWxlbmFtZT0iL1VzZXJzL2Rlcy9zcmMvdGFiLXN0YXNoL2Rpc3QvaWNvbnMvbG9nby02NC5wbmciCiAgIGlua3NjYXBlOmV4cG9ydC14ZHBpPSI2NCIKICAgaW5rc2NhcGU6ZXhwb3J0LXlkcGk9IjY0Ij4KICA8c29kaXBvZGk6bmFtZWR2aWV3CiAgICAgcGFnZWNvbG9yPSIjZmZmZmZmIgogICAgIGJvcmRlcmNvbG9yPSIjNjY2NjY2IgogICAgIGJvcmRlcm9wYWNpdHk9IjEiCiAgICAgb2JqZWN0dG9sZXJhbmNlPSIxMCIKICAgICBncmlkdG9sZXJhbmNlPSIxMCIKICAgICBndWlkZXRvbGVyYW5jZT0iMTAiCiAgICAgaW5rc2NhcGU6cGFnZW9wYWNpdHk9IjAiCiAgICAgaW5rc2NhcGU6cGFnZXNoYWRvdz0iMiIKICAgICBpbmtzY2FwZTp3aW5kb3ctd2lkdGg9IjE0NjYiCiAgICAgaW5rc2NhcGU6d2luZG93LWhlaWdodD0iOTc3IgogICAgIGlkPSJuYW1lZHZpZXc5IgogICAgIHNob3dncmlkPSJ0cnVlIgogICAgIGlua3NjYXBlOnpvb209IjguMDIwODMzMyIKICAgICBpbmtzY2FwZTpjeD0iMjUuNTU4NDQxIgogICAgIGlua3NjYXBlOmN5PSI0OCIKICAgICBpbmtzY2FwZTp3aW5kb3cteD0iMCIKICAgICBpbmtzY2FwZTp3aW5kb3cteT0iMCIKICAgICBpbmtzY2FwZTp3aW5kb3ctbWF4aW1pemVkPSIwIgogICAgIGlua3NjYXBlOmN1cnJlbnQtbGF5ZXI9InN2ZzEwIj4KICAgIDxpbmtzY2FwZTpncmlkCiAgICAgICB0eXBlPSJ4eWdyaWQiCiAgICAgICBpZD0iZ3JpZDgxNyIKICAgICAgIGVtcHNwYWNpbmc9IjIiCiAgICAgICBzcGFjaW5neD0iMyIKICAgICAgIHNwYWNpbmd5PSIzIiAvPgogIDwvc29kaXBvZGk6bmFtZWR2aWV3PgogIDxtZXRhZGF0YQogICAgIGlkPSJtZXRhZGF0YTE2Ij4KICAgIDxyZGY6UkRGPgogICAgICA8Y2M6V29yawogICAgICAgICByZGY6YWJvdXQ9IiI+CiAgICAgICAgPGRjOmZvcm1hdD5pbWFnZS9zdmcreG1sPC9kYzpmb3JtYXQ+CiAgICAgICAgPGRjOnR5cGUKICAgICAgICAgICByZGY6cmVzb3VyY2U9Imh0dHA6Ly9wdXJsLm9yZy9kYy9kY21pdHlwZS9TdGlsbEltYWdlIiAvPgogICAgICAgIDxkYzp0aXRsZT48L2RjOnRpdGxlPgogICAgICA8L2NjOldvcms+CiAgICA8L3JkZjpSREY+CiAgPC9tZXRhZGF0YT4KICA8ZGVmcwogICAgIGlkPSJkZWZzMTQiIC8+CiAgPHBhdGgKICAgICBkPSJNIDc0LjI1LDI0IEggNzAuNSBWIDYgQSA3LjUsNiAwIDAgMCA2MywwIEggMzMgYSA3LjUsNiAwIDAgMCAtNy41LDYgdiAxOCBoIC0zLjc1IGEgMy43NSwzIDAgMCAwIDAsNiBoIDUyLjUgYSAzLjc1LDMgMCAxIDAgMCwtNiB6IgogICAgIGlkPSJwYXRoNSIKICAgICBpbmtzY2FwZTpjb25uZWN0b3ItY3VydmF0dXJlPSIwIgogICAgIGZpbGw9ImNvbnRleHQtZmlsbCIKICAgICBzdHlsZT0iZmlsbDojODA4MDgwIiAvPgogIDxwYXRoCiAgICAgaWQ9InBhdGg4IgogICAgIGQ9Im0gMjcsNTQgYSAzLDMgMCAxIDAgMCw2IGggNDIgYSAzLDMgMCAxIDAgMCwtNiB6IgogICAgIGlua3NjYXBlOmNvbm5lY3Rvci1jdXJ2YXR1cmU9IjAiCiAgICAgZmlsbD0iY29udGV4dC1maWxsIgogICAgIHN0eWxlPSJmaWxsOiM4MDgwODAiIC8+CiAgPHBhdGgKICAgICBpZD0icGF0aDEwIgogICAgIGQ9Im0gNiw0MiB2IDMwIGMgMCwxMiA2LDE4IDE4LDE4IEggNzIgQyA4NCw5MCA5MCw4NCA5MCw3MiBWIDQyIGMgMCwwIDAsLTYgLTYsLTYgLTYsMCAtNiw2IC02LDYgViA3OCBIIDE4IFYgNDIgYyAwLDAgMCwtNiAtNiwtNiAtNiwwIC02LDYgLTYsNiB6IgogICAgIGlua3NjYXBlOmNvbm5lY3Rvci1jdXJ2YXR1cmU9IjAiCiAgICAgc29kaXBvZGk6bm9kZXR5cGVzPSJjc3Nzc2NzY2NjY3NjIgogICAgIGZpbGw9ImNvbnRleHQtZmlsbCIKICAgICBzdHlsZT0iZmlsbDojODA4MDgwIiAvPgogIDxwYXRoCiAgICAgZD0ibSAyNyw2NiBhIDMsMyAwIDEgMCAwLDYgaCA0MiBhIDMsMyAwIDEgMCAwLC02IHoiCiAgICAgaWQ9InBhdGgzNzAyIgogICAgIGlua3NjYXBlOmNvbm5lY3Rvci1jdXJ2YXR1cmU9IjAiCiAgICAgZmlsbD0iY29udGV4dC1maWxsIgogICAgIHN0eWxlPSJmaWxsOiM4MDgwODAiIC8+CiAgPHBhdGgKICAgICBkPSJtIDI3LDQyIGEgMywzIDAgMSAwIDAsNiBoIDQyIGEgMywzIDAgMSAwIDAsLTYgeiIKICAgICBpZD0icGF0aDgzMiIKICAgICBpbmtzY2FwZTpjb25uZWN0b3ItY3VydmF0dXJlPSIwIgogICAgIGZpbGw9ImNvbnRleHQtZmlsbCIKICAgICBzdHlsZT0iZmlsbDojODA4MDgwIiAvPgo8L3N2Zz4K"}}]}`

> l index.ts:63

### Installed Extensions

- None

### Describe the Crash

All I did is open Tab Stash

### Expected Behavior

The screen still appears normally but I just see the error.

### Impact

I can still use the extension but it's just slower and sometimes sending tabs to Tab Stash doesn't work. I've now disabled it as it was causing performance problems when multiple tabs was open.

### Additional Details

![tab stash crash part 3](https://user-images.githubusercontent.com/1139316/154141245-419dc1b1-9428-4607-a033-b183db154253.png)
![tab stash crash part 2](https://user-images.githubusercontent.com/1139316/154141252-4b3cb1d4-a293-4288-8082-a829ecb073e6.png)
![tab stash crash part 1](https://user-images.githubusercontent.com/1139316/154141254-2bc70a65-906b-4945-a615-e43ffe2a72df.png)

**Comment by mystiquewolf** [comment]
Also experience this error.

Browser: Mozilla Firefox 97.0 20220207201222 (linux x86-64)
Extension: Tab Stash 2.10.2 (normal)

**Comment by Xiazee** [comment]
I also get this error sometimes when opening the stash tab sidebar. It seems to be related to whether the favicons are able to load properly. Either it loads (almost) all available favicons properly, or it fails to load more than a couple and gives me a similar error.

It doesn't appear to happen often below 1k tabs, but above 2k it happens somewhat reliably. Doesn't matter if the groups are collapsed.

**Comment by mystiquewolf** [comment]
My tabs are 521 grouped into 19 groups. Happens sometimes.

**Comment by josh-berry** [comment]
hah, I was going to increase this timeout before releasing, and I just plain forgot. Sorry about that!

What's happening is, the UI is trying to load the favicons from the cache, and it's loading them all at once (which is the fastest way to do it, when it works...). However, if your browser/computer happens to be doing a lot of stuff at that moment, or if you have a lot of tabs, then loading might take too long and this timeout error happens.

> It doesn't appear to happen often below 1k tabs, but above 2k it happens somewhat reliably. Doesn't matter if the groups are collapsed.

@Xiazee Thanks, this is useful info. I'm realizing that in addition to increasing the timeout, I also need to load icons in smaller batches.

> I can still use the extension but it's just slower and sometimes sending tabs to Tab Stash doesn't work. I've now disabled it as it was causing performance problems when multiple tabs was open.

@desbest When did you notice things get slower? Was it after 2.10.2 or even before then? The performance/sending tabs to Tab Stash failures sound like a different issue from what I see in the crash you reported; if you're seeing new performance problems, would you mind opening a separate bug for those? Thanks!

**Comment by desbest** [comment]
One minute there was no errors with Tab Stash 2.10.1, then the next minute I upgraded to Tab Stash 2.10.2 then the error happened

**Comment by josh-berry** [comment]
> I cannot be sure that the performance issues started with 2.10.2 because I very quickly soon disabled the extension after seeing the above error every time I opened the extension. So I never tried to reproduce any actions I previously did, to even confirm whether any performance issues exist with any certainty.

@desbest Got it, thanks for clarifying. If it helps, you can disable the crash messages for up to a week at a time (the next time it happens, click "Hide Crash Reports", then "for 1 week"), so you can continue to use Tab Stash in peace. In general, these crashes should be harmless, even if they are noisy. 😞

Since you're seeing this all the time, I'll see what I can do to get a release out quickly. Mozilla has been pretty responsive when it comes to reviewing new versions so hopefully you won't have to wait long.

**Comment by josh-berry** [comment]
@desbest A couple more questions--how many tabs/groups do you have? And what do you have as far as CPU/RAM? Knowing those things will help me with performance testing.

**Comment by desbest** [comment]
645 tab groups with 4112 tabs

**Comment by josh-berry** [comment]
OK, so I have a fix for this (the two commits noted above), but some of your stashes put my paltry ~900 or so to shame. 🤣 So even though I’m pretty confident in the fix, I want to do a bit more testing before I get it into a release. (Since this is a performance issue, “works on my machine” doesn’t always mean “works on your machine”…)

In the meantime, as mentioned above, if you’re seeing this crash super frequently, you can turn off crash reports by clicking “Hide Crash Reports” the next time one happens, and then choosing how long to hide them for (up to a week). And hopefully that will give you some peace and quiet in the meantime.

**Comment by DraganNSDK** [comment]
thx Josh for your work here - this little extension is a life saver for heavy 'tab users' :) - I have the same issue (favicons timeout) - I have around 4K tabs (Firefox, arch, fast, lot of RAM etc.) - I pretty much use it like bookmarks, I export/backup regularly, I'm planning on trimming it (via export/import I guess) but didn't get the chance.
What I was trying to say, 900 is peanuts :) cheers

**Comment by josh-berry** [comment]
@desbest Got it; once you've had a chance to test with the next version, do feel free to open another issue if you're still seeing performance problems.

**Comment by ericjs** [comment]
It seems to be the bigger issue here is why is a timeout presented to the user as a "Crash report"?
Alternately if the timeout really does cause the extension to crash, then it seems to me that a timeout can cause a crash should be a bigger concern than the timeout being too short.

**Comment by josh-berry** [comment]
> It seems to be the bigger issue here is why is a timeout presented to the user as a "Crash report"?

Because the timeout should not have happened in the first place—the fact that it happened IS the bug here (which has long since been fixed and released).
