### ISSUE TITLE
Allow middle click to close open tabs.

### ISSUE THREAD

**Issue by KerfuffleV2** [josh-berry/tab-stash#215]
### Problem Statement

Tab Stash's behavior when middle clicking an open tab (or bookmark with open tabs) is surprising compared to other vertical tab extensions as well as the default behavior for tabs in Firefox. Currently a middle click will open another copy of the tab.

### Preferred Solution(s)

Middle click should close the tab. For bookmarks, it seems logical that middle clicking a bookmark with open tabs would close the related open tabs.

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hm, I didn't know this middle-click behavior was a thing until you told me about it. TIL!

Thanks for sending over the PR; will leave more comments there.

**Comment by CouldBeThis** [comment]
Hello, I have Tab Stash version 2.10.3 installed on Firefox 100.0 and am mistakenly opening new tabs by middle clicking all the time. Is there a preference I can set to have them close instead?

**Comment by KerfuffleV2** [comment]
@CouldBeThis The version with this change hasn't been released yet. Unfortunately, the only way to get that behavior right now would be to build the extension from source yourself.

**Comment by josh-berry** [comment]
> The version with this change hasn't been released yet.

Coming soon! There's one more feature in the pipeline I want to see if I can get in to 2.11, then I'll kick it out the door. :)

**Comment by CouldBeThis** [comment]
thank you!

**Comment by safetycar** [comment]
:/ now I don't see any way of making copies of tabs. Maybe allow some ctrl+click or ctrl+drag?

**Comment by josh-berry** [comment]
Tab duplication is built in to Firefox itself—right-click on the tab you want to copy and click "Duplicate Tab". Hope this helps!

**Comment by safetycar** [comment]
Not helpful for my case, but I guess it's not Tab Stash fault.
It's a weird case. I have a link that loads random pages, If I duplicate the tab I don't get a new random.
I thought I could use tab stash more like a bookmark managing tool but it looks like I need to rethink some things.

**Comment by josh-berry** [comment]
Ah, I see. One other way to open duplicate tabs is to right-click the tab in Tab Stash and choose "Open Link in New Window". This will likely give you the behavior you expect.
