### ISSUE TITLE
stashes

### ISSUE THREAD

**Issue by selster** [josh-berry/tab-stash#22]
I upgraded to firefox 67.0.1 quantuum 64 bit windows 7 a few days ago, after a system restore.   the stash inferface will no longer come up, but stash is still stashing my open tabs.  but I miss the stash interface.  But my stashes are still there.
Thanks,
Steve

**Comment by josh-berry** [comment]
Hi Steve, sorry to hear that. I don't have a Windows 7 system to test with, but I tried it on my Windows 10 machine just now (also with Firefox 67.0.1 64bit), and unfortunately wasn't able to reproduce this.

Can you do the following to collect some debugging info:

1. Right-click on the Tab Stash icon in the toolbar.
2. Choose "Show Stashed Tabs in a Tab". This will open a new tab.
3. Even if the tab remains blank (doesn't show the stash interface), right-click anywhere in the tab and choose "Inspect Element". This will open the Firefox developer tools.
4. Choose the "Console" tab in the developer tools.
5. Copy all the messages you see (if any) into a comment on this issue.

Just to confirm, you can still see and use all your stashes in the Firefox bookmarks manager?

Thanks,
Josh

**Comment by selster** [comment]
My stashes are in bookmarks manager









On Sat, Jun 8, 2019 at 2:39 PM -0700, "Josh Berry" <notifications@github.com> wrote:












Hi Steve, sorry to hear that. I don't have a Windows 7 system to test with, but I tried it on my Windows 10 machine just now (also with Firefox 67.0.1 64bit), and unfortunately wasn't able to reproduce this.


Can you do the following to collect some debugging info:

Right-click on the Tab Stash icon in the toolbar.
Choose "Show Stashed Tabs in a Tab". This will open a new tab.
Even if the tab remains blank (doesn't show the stash interface), right-click anywhere in the tab and choose "Inspect Element". This will open the Firefox developer tools.
Choose the "Console" tab in the developer tools.
Copy all the messages you see (if any) into a comment on this issue.



Just to confirm, you can still see and use all your stashes in the Firefox bookmarks manager?


Thanks,

Josh

**Comment by selster** [comment]
Josh
1. This works and shows my stashes: 
--Right-click on the Tab Stash icon in the toolbar. Choose "Show Stashed Tabs in a Tab". This will open a new tab. 
2. There is no inspect element when I click in the tab area.  If I click on the firefox main page, there are no comments under console: 
--Even if the tab remains blank (doesn't show the stash interface), right-click anywhere in the tab and choose "Inspect Element". This will open the Firefox developer tools. Choose the "Console" tab in the developer tools. Copy all the messages you see (if any) into a comment on this issue.

**Comment by selster** [comment]
Ok. now, if I click on the stashes incons, unpredictable things happen.  Often, all tabs are closed, for instance, including the sidebar showing the stashes.  and a message opens over the stash icon, stating that an addon has hidden my bookmarks ...  The console has no comments.  If I right click: showed stashes in sidebar, it works.

**Comment by josh-berry** [comment]
It's very strange that the sidebar would be closed along with all of your stashed tabs. However, the "an add-on has hidden your tabs" message is normal and should only appear the first time you use Tab Stash—if you tell the browser to keep your tabs hidden, you won't see that message again.

Specifically related to the sidebar issue, let's try one more thing and take the sidebar out of the picture entirely:

1. Right-click the Tab Stash toolbar icon
2. Choose "Manage Extension", and scroll down to the Tab Stash settings (below the add-on description, rating, etc.)
3. Select the setting to "Automatically show your stashed tabs in a tab"
4. Try stashing and restoring a few sets of tabs with this setting enabled (you can change it back to your preferred setting after the test).

With this setting enabled, I have a few questions about what happens in step 4:
* Does Tab Stash automatically show your stashes (by opening or switching to the Tab Stash tab) reliably every time?
* Do the open tabs get closed/hidden every time?
* Do the saved tabs appear correctly in your stash/bookmarks every time?

If the unpredictability you mentioned occurs only with the "Automatically show ... in the sidebar" setting, it may be a bug in the Tab Stash sidebar setting and not related to your Firefox at all. But let me know if the above is working in your setup and we can go from there.

**Comment by selster** [comment]
ok -- With this setting enabled, I have a few questions about what happens in step 4:

1. Does Tab Stash automatically show your stashes (by opening or switching to the Tab Stash tab) reliably every time?  YES
2. Do the open tabs get closed/hidden every time?  NO
3. Do the saved tabs appear correctly in your stash/bookmarks every time?

**Comment by selster** [comment]
now that I see my stashes on one big page, since each one is labeled, I wish there was a way to minimize them so that each stash became a tile, one that I drag around on the page to organize them

**Comment by selster** [comment]
once I minimize the stashes, I can drag them around but I am not sure stash remembers the order I left them in, will check

**Comment by selster** [comment]
it does remember the order, if I make the stash page into google.com, the first time I hit the stash icon, bookmarks are hidden box comes up but no stashes, the next time, the stash page comes up.

**Comment by josh-berry** [comment]
Interesting—while I was taking another look at the code, I did find a bug related to opening the sidebar in the recent 2.3 release, but I'm not sure it's the same as your bug, since you also seem to be having problems opening the stash list in a tab (and you mentioned the open tabs do not get closed/hidden every time). Let me do some more experiments on my Windows system and see if I can narrow it down any further.

In the meantime, if you happen to do any more experiments on your end, can you list out the exact set of steps you followed and what you observed (or didn't observe but expected to see) at each step, for example:

1. Clicked the stash toolbar button
2. The Tab Stash tab opened but was blank
3. The list of stashes loaded after a few seconds
4. I expected all my other tabs to be closed, but they stayed open

(or whatever the case may be)

The more data/details you can give, the better.

**If you're technically-inclined** and want to look through logs for more error messages and such, you can open a new tab, go to `about:debugging`, turn on the `Enable add-on debugging` option, find Tab Stash in the list and click `Debug`. This will give you a new console window with more error logs (be warned, though—there may be stuff in there not related to Tab Stash at all).

**Comment by josh-berry** [comment]
I've just released v2.3.1 with a fix for the sidebar issue. Your browser should hopefully pick it up in the next day or so (if your updates are enabled). I'm not sure if this will completely resolve your issue, but once you get 2.3.1, let me know if it helps?

Thanks!

**Comment by josh-berry** [comment]
Hi Steve, Tab Stash 2.3.1 should have hit your browser by now, can you let me know if you're still seeing this problem?

Thanks!

**Comment by josh-berry** [comment]
Haven't heard back so I'm assuming this issue is resolved. Please feel free to re-open or file a new issue if you're still having problems. Thanks!
