### ISSUE TITLE
Disconnect crash

### ISSUE THREAD

**Issue by naugtur** [josh-berry/tab-stash#223]
### Crash Details

```text
Browser: Mozilla Firefox 97.0 20220202182137 (linux x86-64)
Extension: Tab Stash 2.10.2 (normal)

Disconnected
_flushPendingOnDisconnect@moz-extension://e3a8b3ae-5175-429d-bcbd-9bccc57f1e36/stash-list.js:1:175723
3197/u/<@moz-extension://e3a8b3ae-5175-429d-bcbd-9bccc57f1e36/stash-list.js:1:174413

Disconnected
_flushPendingOnDisconnect@moz-extension://e3a8b3ae-5175-429d-bcbd-9bccc57f1e36/stash-list.js:1:175723
3197/u/<@moz-extension://e3a8b3ae-5175-429d-bcbd-9bccc57f1e36/stash-list.js:1:174413

Disconnected
_flushPendingOnDisconnect@moz-extension://e3a8b3ae-5175-429d-bcbd-9bccc57f1e36/stash-list.js:1:175723
3197/u/<@moz-extension://e3a8b3ae-5175-429d-bcbd-9bccc57f1e36/stash-list.js:1:174413

Disconnected
_flushPendingOnDisconnect@moz-extension://e3a8b3ae-5175-429d-bcbd-9bccc57f1e36/stash-list.js:1:175723
3197/u/<@moz-extension://e3a8b3ae-5175-429d-bcbd-9bccc57f1e36/stash-list.js:1:174413

Disconnected
_flushPendingOnDisconnect@moz-extension://e3a8b3ae-5175-429d-bcbd-9bccc57f1e36/stash-list.js:1:175723
3197/u/<@moz-extension://e3a8b3ae-5175-429d-bcbd-9bccc57f1e36/stash-list.js:1:174413

Disconnected
_flushPendingOnDisconnect@moz-extension://e3a8b3ae-5175-429d-bcbd-9bccc57f1e36/stash-list.js:1:175723
3197/u/<@moz-extension://e3a8b3ae-5175-429d-bcbd-9bccc57f1e36/stash-list.js:1:174413

Disconnected
_flushPendingOnDisconnect@moz-extension://e3a8b3ae-5175-429d-bcbd-9bccc57f1e36/stash-list.js:1:175723
3197/u/<@moz-extension://e3a8b3ae-5175-429d-bcbd-9bccc57f1e36/stash-list.js:1:174413

Disconnected
_flushPendingOnDisconnect@moz-extension://e3a8b3ae-5175-429d-bcbd-9bccc57f1e36/stash-list.js:1:175723
3197/u/<@moz-extension://e3a8b3ae-5175-429d-bcbd-9bccc57f1e36/stash-list.js:1:174413

Disconnected
_flushPendingOnDisconnect@moz-extension://e3a8b3ae-5175-429d-bcbd-9bccc57f1e36/stash-list.js:1:175723
3197/u/<@moz-extension://e3a8b3ae-5175-429d-bcbd-9bccc57f1e36/stash-list.js:1:174413

Disconnected
_flushPendingOnDisconnect@moz-extension://e3a8b3ae-5175-429d-bcbd-9bccc57f1e36/stash-list.js:1:175723
3197/u/<@moz-extension://e3a8b3ae-5175-429d-bcbd-9bccc57f1e36/stash-list.js:1:174413
```

### Describe the Crash

Tabstash was hogging CPU so I killed the process to restart it and now I'm getting this crash report all the time. When I click x the same (or identical) report pops back up

### Expected Behavior

No expectations, my bad for killing it at the wrong time. Reporting because it could help identify edge-cases

### Impact

My restart attempt was a bad idea, because now it consumes more CPU on crashing ;) 
Firefox won't spawn devtools for tabstash now, I don't know why. Ill keep trying and add the perf trace file to this when I succeed.

**Comment by naugtur** [comment]
It seems to have recovered a while after I closed the sidebar. 
CPU is up again but devtools won't work :(

**Comment by unixpro** [comment]
+1

Name 	Firefox
Version 	91.6.0esr
Build ID 	20220602070101
Distribution ID 	
Update Directory 	
/home/username/tor-browser/Browser/TorBrowser/UpdateInfo
Update History 	
Update Channel 	release
User Agent 	Mozilla/5.0 (Windows NT 10.0; rv:91.0) Gecko/20100101 Firefox/91.0
OS 	Linux 5.15.19-051519-generic #202202011232 SMP Tue Feb 1 17:53:41 UTC 2022
Application Binary 	/home/username/tor-browser/Browser/firefox.real
Profile Directory 	
/home/username/tor-browser/Browser/TorBrowser/Data/Browser/profile.default 
Add-ons
Name 	Type 	Version 	Enabled 	ID
British English Dictionary (Marco Pinto)	dictionary	3.0.5	true	marcoagpinto@mail.telepac.pt
Blockchair	extension	1.0	true	blockchair@search.mozilla.org
DuckDuckGo	extension	1.1	true	ddg@search.mozilla.org
DuckDuckGoOnion	extension	1.0	true	ddg-onion@search.mozilla.org
Google	extension	1.1	true	google@search.mozilla.org
HTTPS Everywhere	extension	2021.7.13	true	https-everywhere-eff@eff.org
NoScript	extension	11.3.4	true	{73a6fe31-595d-460b-a920-fcc0f8843232}
Startpage	extension	1.0	true	startpage@search.mozilla.org
Tab Stash	extension	2.10.2	true	tab-stash@condordes.net
Twitter	extension	1.0	true	twitter@search.mozilla.org
Wikipedia (en)	extension	1.1	true	wikipedia@search.mozilla.org
Yahoo	extension	1.0	true	yahoo@search.mozilla.org
YouTube	extension	1.0	true	youtube@search.mozilla.org
English (GB) Language Pack	locale	91.0buildid20210823123856	true	langpack-en-GB@firefox.mozilla.org

Seeing completely normal CPU usage here.

**Comment by Btrfs-zz** [comment]
+1 
"Oops! Something went wrong tab Stash will try to recover automatically" in loop, 
but normal CPU usage, tabs of the previous session can't be recovered after closing the browser (last tab group correctly saved and shown 2/21/2022)

Name 	Firefox
Version 	97.0.1-1
Build ID 	20220217220106
Distribution ID 	
User Agent 	Mozilla/5.0 (Windows NT 10.0; rv:91.0) Gecko/20100101 Firefox/91.0
OS 	Windows_NT 10.0 19043
Application Binary 	C:\Program Files\LibreWolf\librewolf.exe
Profile Folder 	
C:\Users\mnp\AppData\Roaming\LibreWolf\Profiles\40p8pdrg.dev-edition-default

Browser: LibreWolf Firefox 97.0.1-1 20220217220106 (win x86-64)
Extension: Tab Stash 2.10.2 (normal)

Add-ons Search Detection	extension	2.0.0	true	addons-search-detection@mozilla.com
Dark Reader	extension	4.9.45	true	addon@darkreader.org
DuckDuckGo	extension	1.1	true	ddg@search.mozilla.org
Hive Keychain	extension	1.14.2	true	{b6bd7e35-0762-42a2-a283-95a94635047d}
LocalCDN	extension	2.6.23	true	{b86e4813-687a-43e6-ab65-0bde4ab75758}
MetaMask	extension	10.10.1	true	webextension@metamask.io
Sidebery	extension	4.10.0	true	{3c078156-979c-498b-8990-85f7987dd929}
Startpage.com — Private Search Engine	extension	1.3.0	true	{20fc2e06-e3e4-4b2b-812b-ab431220cada}
Tab Stash	extension	2.10.2	true	tab-stash@condordes.net
Tree Style Tab	extension	3.8.21	true	treestyletab@piro.sakura.ne.jp
uBlock Origin	extension	1.41.8	true	uBlock0@raymondhill.net
uMatrix	extension	1.4.4	true	uMatrix@raymondhill.net
Wikipedia (en)	extension	1.1	true	wikipedia@search.mozilla.org

```
Disconnected
_flushPendingOnDisconnect@moz-extension://a3f4157c-e097-4a70-bef1-328af9e6feed/stash-list.js:1:175723
3197/u/<@moz-extension://a3f4157c-e097-4a70-bef1-328af9e6feed/stash-list.js:1:174413

Disconnected
_flushPendingOnDisconnect@moz-extension://a3f4157c-e097-4a70-bef1-328af9e6feed/stash-list.js:1:175723
3197/u/<@moz-extension://a3f4157c-e097-4a70-bef1-328af9e6feed/stash-list.js:1:174413

Disconnected
_flushPendingOnDisconnect@moz-extension://a3f4157c-e097-4a70-bef1-328af9e6feed/stash-list.js:1:175723
3197/u/<@moz-extension://a3f4157c-e097-4a70-bef1-328af9e6feed/stash-list.js:1:174413

Disconnected
_flushPendingOnDisconnect@moz-extension://a3f4157c-e097-4a70-bef1-328af9e6feed/stash-list.js:1:175723
3197/u/<@moz-extension://a3f4157c-e097-4a70-bef1-328af9e6feed/stash-list.js:1:174413

Disconnected
_flushPendingOnDisconnect@moz-extension://a3f4157c-e097-4a70-bef1-328af9e6feed/stash-list.js:1:175723
3197/u/<@moz-extension://a3f4157c-e097-4a70-bef1-328af9e6feed/stash-list.js:1:174413

Disconnected
_flushPendingOnDisconnect@moz-extension://a3f4157c-e097-4a70-bef1-328af9e6feed/stash-list.js:1:175723
3197/u/<@moz-extension://a3f4157c-e097-4a70-bef1-328af9e6feed/stash-list.js:1:174413

Disconnected
_flushPendingOnDisconnect@moz-extension://a3f4157c-e097-4a70-bef1-328af9e6feed/stash-list.js:1:175723
3197/u/<@moz-extension://a3f4157c-e097-4a70-bef1-328af9e6feed/stash-list.js:1:174413

Disconnected
_flushPendingOnDisconnect@moz-extension://a3f4157c-e097-4a70-bef1-328af9e6feed/stash-list.js:1:175723
3197/u/<@moz-extension://a3f4157c-e097-4a70-bef1-328af9e6feed/stash-list.js:1:174413

Disconnected
_flushPendingOnDisconnect@moz-extension://a3f4157c-e097-4a70-bef1-328af9e6feed/stash-list.js:1:175723
3197/u/<@moz-extension://a3f4157c-e097-4a70-bef1-328af9e6feed/stash-list.js:1:174413

Disconnected
_flushPendingOnDisconnect@moz-extension://a3f4157c-e097-4a70-bef1-328af9e6feed/stash-list.js:1:175723
3197/u/<@moz-extension://a3f4157c-e097-4a70-bef1-328af9e6feed/stash-list.js:1:174413
```

**Comment by josh-berry** [comment]
Hi folks, if you're seeing this crash repeatedly, can you try the following in order and let me know which (if anything) helps to stop the crashes (even temporarily):

1. Close and open the sidebar (or Tab Stash tab)
2. Restart your browser
3. Restart your browser, discarding any saved session data. ([Here’s how.](https://github.com/josh-berry/tab-stash/wiki/Restart-Firefox-Without-Saved-Session-Data))

If none of the above works, it would be good to know if you have any security settings in Preferences, in `about:config` or other places. I am wondering if there's some Firefox setting or similar that is causing this to happen for you repeatedly when it doesn't seem to happen for others at all.

Like I said above, it seems like a Firefox issue, but the more info we can collect to narrow it down, the more help I'll be able to offer others in future, and it might also help me in exploring possible workarounds.

Thanks!

**Comment by josh-berry** [comment]
OK, so I have some changes for 2.10.3 to mitigate/work around the issue (so far as I understand it). It's unfortunately a bit hard to know for sure how much they will help, but without knowing *why* Firefox is triggering disconnections, it's going to be hard to say for sure if it's fully resolved.

But, my hope is you should stop seeing crashes in the vast majority of cases, and if they *do* continue, they shouldn't occur repeatedly. So I'll go ahead and close this, but feel free to leave any more replies to the questions above, or if this happens again in 2.10.3, let me know and I can reopen the issue.
