### ISSUE TITLE
Option to deselect marked items once moved to another stash group

### ISSUE THREAD

**Issue by WebMechanic** [josh-berry/tab-stash#228]
### Problem Statement
If multiple tabs entries are selected (blue icon with tab symbol) and moved to another group using the blue command button at the top, the items all remain selected inside their target group. If that target group was collapsed (or at the very bottom of the list) it's tedious to scroll there and open the target group and un-mark all items again.

### Preferred Solution(s)
Remove selected status once the items have been moved. 

I can't think of any follow up action that would required them to remain selected.

### Alternative Solution(s)
Provide an option in the "blue" command menu to deselect these items.

The only option in that menu is "Delete and close". I have no idea what that's supposed to mean or what it refers to. It sounds not like something I want to do with the items I have just decided to move someplace else.

### Additional Context

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by KerfuffleV2** [comment]
It's a little clunky, but control-click seems to clear selection and then toggle selection of one item. So a workaround would be to  control-click a visible tab/bookmark twice after stashing a set of selected tabs and you'll end up with nothing selected.

**Comment by WebMechanic** [comment]
ah, okay. Thank you!
I thought I tried ctrl-clicking 🤔
since it's mainly items from the unstashed or open tabs group which is at the top as well as the popup menu I can just ctrl-click-clickedy one of these and it's all clear.

**Comment by WebMechanic** [comment]
> You should be able to click anywhere on the background to clear the selection

It's all tightly packed there... 
once an item is marked blue, clicking anyways adds a new item to the selection.
In my mental model I ctrl+click to **create and expand** discontinuous selections in the first place, not to clear the whole bunch - at least on Windows.
The desktop metaphor doesn't work either: there isn't really a neutral "background" to click on once an item is marked, but ctrl+click anywhere does the trick and deselects all but the newly clicked item, click that single one too and it's all set. 
Neither intuitive nor straight forward, but easy done.

**Comment by josh-berry** [comment]
Yeah that's fair. I'll look at what can be done here.

**Comment by josh-berry** [comment]
Thanks to @KerfuffleV2 for sending in a PR to address this; starting with the next release, items will be deselected after they're moved.
