### ISSUE TITLE
Problems with dark theme

### ISSUE THREAD

**Issue by happysurf** [josh-berry/tab-stash#23]
**Describe the bug**
The icon in address bar is impossible to view.

**To Reproduce**
1.Install a dark theme like this:
https://addons.mozilla.org/en-US/firefox/addon/solarize-fox/ 
2. Problems also for see the Tab Stash options in new dark internal pages of Firefox 68 if allow in config:
browser.in-content.dark-mode.

**Expected behavior**
The icon must be light on dark background.

**Screenshots**
![Arrow1](https://user-images.githubusercontent.com/13637587/59248406-99e1ce80-8c22-11e9-8c3f-50116834b319.png)
![Options](https://user-images.githubusercontent.com/13637587/59249128-58522300-8c24-11e9-8d4e-9a0a3c2bfeb7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Firefox Browser Version: 68 beta8

**Comment by josh-berry** [comment]
Thanks for the report! This is a known issue which needs some support from Firefox to fix—see #16.

**Comment by cobrabr** [comment]
Sorry to necro this issue, but as an alternative, couldn't there be a settings option to choose a dark- or light-coloured icon for the address bar button? That way we could manually control which icon to use.
