### ISSUE TITLE
Sub-Groups Within Groups

### ISSUE THREAD

**Issue by PhoRamSo** [josh-berry/tab-stash#236]
### Problem Statement
I have too many groups, each representing a certain category, and I feel like it is too much time to go through because some of my groups are similar. Plus, there comes the point where you have too many tabs in one group and would find it best to subcategorize them into smaller groups within the parent group.

### Preferred Solution(s)
Have a sub-group feature to create sub-groups/child groups within a parent group. And this can go on within groups within groups, and so on to keep things organized.

When searching for groups, whatever search method/keyword you use, not only will parent groups show, but subgroups based on those methods/keywords will appear, no matter what group hierarchy they're in. The result would show based on what hierarchies opened.

### Additional Context

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button. You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, thanks for reaching out! Your issue is already covered/duplicated by another issue, so please take a look at the original (and subscribe if you want updates):

* #14
