### ISSUE TITLE
Can't stash tabs while in Reading mode

### ISSUE THREAD

**Issue by RandomHam** [josh-berry/tab-stash#24]
**Describe the bug**
Tabs which are in the built-in reading mode of Firefox can't be stashed. They also don't show up in the "unstashed tabs" group, but do once reader mode is disabled

**To Reproduce**
1. load random page
2. activate reader view (F9)
3. try to stash the tab

**Expected behavior**
Not sure how the reader view works on a technical side and if anything can be done about this, but it would b e nice if that tab can be stashed as well.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Firefox Browser Version: 68.0b10 (64-bit) -> Firefox Beta

**Additional context**
Alternative suggestions for solutions (if possible):
- stash the tab outside of reader view
- notify if tabs didn't get stashed/are in reader view when stashing the current session

This bug could get especially frustrating if one hasn't enabled session restore, stashes his current session and mindlessly closes Firefox without noticing that some tabs stayed opened (because they are in reader view and therefore not recognized). As a result the tabs would be lost.

**Comment by josh-berry** [comment]
Thanks for the report, and sorry for the frustration! I have to confess I forgot that Firefox even offered a reader mode, so I hadn't tested it with Tab Stash until now.

Based on your description, I think I have an idea what's going on—Tab Stash tries to ignore "system" tabs like the Firefox settings tab, tabs opened by other extensions, etc. I did a quick test on my system just now, and it seems these reader-mode tabs appear as system tabs (Firefox reports they all have URLs like `about:reader?url=...`).

I'll have to do a little more investigation to make sure I haven't missed something, but from what I can tell right now, this should be pretty easy to fix.

**Comment by josh-berry** [comment]
The fix for this will be in the next release.

**Comment by RandomHam** [comment]
Thanks a lot!
