### ISSUE TITLE
Suggest to add a feature to move or merge tabs to another group

### ISSUE THREAD

**Issue by dspjm** [josh-berry/tab-stash#248]
### Problem Statement

Sometimes we stash tabs that are of one topic and since they are stashed at different times, they are in different groups. We have to drag them one by one to merge the groups. When there are many tabs or many groups, it's laborious.

### Preferred Solution(s)

A menu item on a group to merge the group with another group.

### Alternative Solution(s)

Directly drag the group to another group to merge groups. Multiselect tabs (one button to select all tabs) and drag them to another group.

### Additional Context

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, Tab Stash already has a multi-select feature. You can click on each tab's icon to select it, or Shift+Click (etc.) to select a range of tabs. Then you can drag-and-drop or use the blue menu that appears at the top to move the tabs to your desired group.

<img width="325" alt="Screen Shot 2022-04-22 at 21 03 23" src="https://user-images.githubusercontent.com/1203893/164874507-4686e52f-32e3-4c0e-a42d-1d4e6fe65f41.png">

Is this what you were looking for?

**Comment by dspjm** [comment]
> Hi, Tab Stash already has a multi-select feature. You can click on each tab's icon to select it, or Shift+Click (etc.) to select a range of tabs. Then you can drag-and-drop or use the blue menu that appears at the top to move the tabs to your desired group.
> 
> <img alt="Screen Shot 2022-04-22 at 21 03 23" width="325" src="https://user-images.githubusercontent.com/1203893/164874507-4686e52f-32e3-4c0e-a42d-1d4e6fe65f41.png">
> 
> Is this what you were looking for?

Wow, this is great. I never knew it. It looks like this basically does what I want and I will come back to this if I have further suggestions. Thanks.

**Comment by josh-berry** [comment]
Glad to hear it!
