### ISSUE TITLE
Opening tabs too quickly causes some to be closed

### ISSUE THREAD

**Issue by joaomsa** [josh-berry/tab-stash#25]
**Describe the bug**
Opening tabs too quickly causes some to be closed

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Try to open 2 or more tabs from stash by clicking on tab entries from the sidebar really fast (while some in early loading stages)
2. Any tabs in an early loading stage will be closed by one of the later clicks

**Expected behavior**
All tabs that where clicked on should be opened

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Firefox Browser Version: 67.0.3

**Additional context**
I took a brief look at the tab opening code and my guess it's due to this:

https://github.com/josh-berry/tab-stash/blob/490a5e4a058eba9f3a05d4f8c808c95d119f6833/src/stash.ts#L521

I think you also want to take into consideration the curtab.status, so it doesn't close a loading tab.

**Comment by josh-berry** [comment]
Oh wow, I'm surprised I haven't hit this one myself yet, but I was able to reproduce it just now. Thanks for the report and for taking the time to dig through the code—much appreciated!

I'll look into this as soon as I can, but I suspect you're probably right about that `remove()` call. I'm thinking there might be other places I need to take the loading status into account as well, but will check once I get a chance to dig into this further.

**Comment by josh-berry** [comment]
The fix for this will be in the next release.
