### ISSUE TITLE
Additional system sidebar style

### ISSUE THREAD

**Issue by mforkel** [josh-berry/tab-stash#252]
### Problem Statement

Even with the "Compact" style for spacing and fonts, the sidebar's appearance jumps out visually. The TS sidebar does not have the look & feel of the native FF sidbars. 

### Preferred Solution(s)

I would like to suggest adding a system style option for the sidebar. It would try to mimic the look & feel of the native FF sidebars, e.g. the bookmark or history sidbars. In particular, that would mean (at least on my instance of FF) a smaller, lighter font, the > (or ⌵) placed on the left, no horizontal lines between stash name and tabs, and the tab lines indented to the right.

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, thanks for the suggestion. Tab Stash was originally designed to follow Firefox's native style to the extent possible (especially on Mac, there are some effects—e.g. the translucent background—the native sidebars use which are not available to extensions). However, Firefox then did a complete re-design of the browser, so while Tab Stash fits reasonably well with the old design, it does clash a bit with the new one.

It's definitely something that's on my radar for a future release, but to be honest, I've been focusing more on implementing some of the most-needed features, so I haven't had time to refresh the style yet. I'll definitely keep your comments in mind when I do, though!

**Comment by mforkel** [comment]
I understand. Functionality is more important than looks. At least it should be :-)

**Comment by josh-berry** [comment]
The next release of Tab Stash should fit in much better with the Firefox design. Hope you like it!
