### ISSUE TITLE
Support sets of tab groups

### ISSUE THREAD

**Issue by mforkel** [josh-berry/tab-stash#254]
### Problem Statement

The functionality and implementation of Tab Stash is just what I was looking for. Tab Stash allows me to concentrate on (the contents of) one or two ideas / topics / projects and to stow away all other stuff for later. The use of bookmarks, an already well-supported, portable concept, avoids introducing an additional database. So I am pretty happy.

But: For bigger projects, I usually open more than one window, each with a set of related tabs.  Since there is no support for groups of groups of tabs in Tab Stash, I stash the tabs of each window in a separate group, use the same name for all groups, and append a running number, e.g. #1, #2, ...  This has a couple of disadvantages, e.g.
- There are no operations for a group of groups, e.g. moving it in the list, renaming it, deleting it, or opening windows for all the tabs of all its groups
- I can't assign a name to a group that characterizes that specific subset of tabs because I have to use the same name for all groups 
- The list of groups is crowed with multiple entries while one would be enough

### Preferred Solution(s)

There a many open questions, starting with what the name for the concept of a group of groups of tabs should be. Project might be one.

Also, I don't have a convincing suggestion for how a user interface might look like that supports both the current two-level hierarchy of groups and tabs as well as a three level hierarchy of projects, groups, and tabs.  But I hope that an open discussion here would result in a good solution. 

Internally, I think projects might be represented as an intermediate level of folders between the root folder and the group folders.

### Additional Context

I realize, this would be a big change that requires many changes to the user interface and the extension internals.

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by mforkel** [comment]
First of all: Obviously I forgot to set a title when I created the issue. I'm sorry. If there is a way to edit the title, at least  I can't find it. I hope @josh-berry can fix the title, maybe something like "Support sets of tab groups".

After thinking about the idea for while (both consciously and unconsciously), here are a couple of remarks:

It is probably better to use a neutral name like "Set" instead of a name like "Project".

In a system-style sidebar (#252) with a context menu (#253), it might not be too hard to support sets:
 - There could be a default set for all groups not (yet) assigned to a set.
 - Sets and groups would have different icons and different context menus.
 - Groups would be indented from set, tabs would be indented from group.
 - Drag and drop could be used to move groups between sets.
 - The sidebar context menu for sets would include commands like 'Open all groups' to open windows for each of its groups or 'Delete group'.
 - The sidebar context menu for groups would include commands like 'Move to new set' and  'Move to set >''. 
 - The page context menu would include additional commands to stash tabs to a new or an existing set. 

The settings should probably include an option to toggle the use and display of sets on and off.

**Comment by josh-berry** [comment]
Hi, thanks for the suggestion! This is already covered/duplicated by another issue, so please take a look at the original (and subscribe if you want updates):

* #14 

As you can tell from #14, there's quite a lot of interest in this (it's one of the earliest feature requests and has quite a few other duplicates). It's also something I find myself wanting as well—one common example that comes up semi-regularly for me is researching/comparing different products and collecting reviews from different places about each option.

Thanks for all the thoughtful suggestions—I do have some ideas about how this could be done, but haven't had time to get to it yet. Do keep an eye on #14 and feel free to chime in there as well!
