### ISSUE TITLE
Pressing shortcuts while RUS keyboard layout is used does nothing

### ISSUE THREAD

**Issue by restonich** [josh-berry/tab-stash#256]
### Problem Statement
When I press a shortcut (Ctrl+Alt+S, Ctrl+Alt+T, Ctrl+Alt+W) while RUS (Russian Cyrillic) keyboard layout is used shortcuts aren't working. I'm pressing the same key where English character would be, of course, there are just different characters in Russian:
Ctrl+Alt+S --> Ctrl+Alt+Ы
Ctrl+Alt+T --> Ctrl+Alt+Е
Ctrl+Alt+W --> Ctrl+Alt+Ц
Other extensions register shortcut regardless of keyboard layout used (e.g. Bitwarden). It's also not a problem for shortcuts in any app that I use (e.g. Firefox, MS Office Word) and for Windows shortcuts.

### Preferred Solution(s)
Register shortcut by the key (where these English characters should be) being pressed instead of the character input. I'm not sure how it's implemented currently though, I'm judging by the problem.

### Additional Context
I can't check other layouts that don't use English characters, but I suppose behavior is the same for those.

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, sorry to hear you're having trouble—I did some research on this, and unfortunately it looks like this is a limitation in Firefox itself. I can specify different default keyboard shortcuts per operating system, but not per keyboard layout/language setting.

Fortunately, there's a way to work around this, which is to set custom keyboard shortcuts. You can find instructions here: https://github.com/josh-berry/tab-stash/wiki/Changing-Keyboard-Shortcuts

Hope this helps!

**Comment by restonich** [comment]
Well, it's somehow works if I set a Ctrl+Shift+<> shortcut, but don't work for anything that starts with Ctrl+Alt+<> (well except for numbers). That is indeed some weird Firefox problem. Thanks for your help, I guess I can close it as solved.
