### ISSUE TITLE
Add option to hide context menu

### ISSUE THREAD

**Issue by lyaaz** [josh-berry/tab-stash#262]
<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Afraid I have no idea what you mean here. The context menu is always hidden until you ask for it (e.g. by right-clicking), and this is something controlled by Firefox in any case.

**Comment by lyaaz** [comment]
Sorry, I mean this
![Screenshot_20220529-020102_firefox](https://user-images.githubusercontent.com/45838887/170837563-4b5668e8-95f1-412c-b52f-208a8d09ef34.png)

**Comment by josh-berry** [comment]
Ah I see. I'm curious why it's causing a problem for you?

**Comment by lyaaz** [comment]
> Ah I see. I'm curious why it's causing a problem for you?

Not a big deal, just because I want to keep the menu clean as I never use this item. So if you think this is redundant, you can just keep this issue close.

**Comment by Quenz** [comment]
I would also like to disable the item to keep things tidy.
