### ISSUE TITLE
unstash tabs of a group to a brand new window

### ISSUE THREAD

**Issue by overtomanu** [josh-berry/tab-stash#264]
### Problem Statement
need to unstash tabs to a new browser window

### Preferred Solution(s)
Provide option (button) to unstash tabs of a group to a brand new window, similar to how "restore all" of onetab extension does it.

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, thanks for reaching out! Your issue is already covered/duplicated by another issue, so please take a look at the original (and subscribe if you want updates):

* #107
