### ISSUE TITLE
Tabs remain selected after stashing

### ISSUE THREAD

**Issue by vic-t** [josh-berry/tab-stash#267]
### Question
Since I only just started using tab stash today, I'm a bit hesitant to report a bug, could be I'm doing something wrong. 

In order to stash several tabs, in the sidebar, I click left of each tab, this way selecting several tabs at once. It doesn't even seem necessary to have SHIFT or CTRL pressed for that. 

So, I select several tabs and then, using the blue button on top of the sidebar, I stash them. 

This works fine but the stashed tabs remain selected. In order to deselect them, I have to CTRL+Click another element, then click on that same element one more time without having a key pressed, only then nothing is selected. 

It confuses me that stashing the tabs does not automatically deselect them. Is this a problem with me, the user, or the software? 

### System Details

- **OS Version:** Win 10
- **Browser Version:** 101.0.1 x64
- **Tab Stash Version:** 2.10.3

**Comment by josh-berry** [comment]
Sorry for the delay in replying—nope, you're not doing anything wrong, it's a problem in the software. Fortunately, a fix is already in for the next release, so you won't have to live with it for too much longer. :)

Sorry for the trouble!

[fix is in #237]

**Comment by vic-t** [comment]
Much appreciated, thanks!
