### ISSUE TITLE
Stashed tab count for each tab group

### ISSUE THREAD

**Issue by embamba** [josh-berry/tab-stash#269]
I had too many open tabs, maybe 600 of them. Tab Stash looks like it might become a big help for people like me who suffer from this syndrome. :)

Excuse me if this feature already exists or has been requested. I didn't see it after doing a search for a few terms. I'd like to see a count of all the tabs in each tab group. In other words, how many URLs are stored in each group. I realize that I can determine this by opening Firefox's Bookmarks window and selecting all the bookmarked URLs in each corresponding folder. But it would be quite a bit more convenient to have quicker access to that number.

### Preferred Solution(s)

- A tooltip on rollover of the tab group title would work for me. 
- Or something like a subheader below the title with the number of URLs within. 
- The number in parentheses after the tab group title.
- Anything that would provide quick access to that number

Thanks for the nice work on this. Much appreciated.

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
My pleasure, I'm glad you've found Tab Stash useful!

This feature hasn't been requested yet, but you're in luck, because someone else was interested in this feature and implemented it for the next release. So you shouldn't have too much longer to wait! :)

See #221
