### ISSUE TITLE
Select multiple tabs when Stash tab managing 

### ISSUE THREAD

**Issue by rayman89** [josh-berry/tab-stash#273]
Could we get the option to easily an quickly select multiple tabs (maybe using control and shift ) on a stash to manage them?  (Aka close, open, delete, move to another stash, re arrange order on same stash etc)

**Comment by josh-berry** [comment]
Hi, thanks for reaching out! This feature was already asked for and is already available in Tab Stash, so I'm going to close your issue as a duplicate. You can find the original issue and feature discussion here:

* #57
