### ISSUE TITLE
Question: What is the purpose of this addon hiding tabs?

### ISSUE THREAD

**Issue by rayman89** [josh-berry/tab-stash#275]
I understand that the first time you are using it maybe scary for the addon to close all the tabs but once we are past that point I dont understand why keeping tabs hidden. Also there is no way now on the addon to see or deal with those hidden tabs you just need to use another addon or vanilla firefox all tab list which is hard to deal with if you have a ton of hidden tabs.

**Comment by josh-berry** [comment]
We keep hidden tabs around by default so they are much quicker to restore and you don't lose anything you are doing on the page when you stash the tab.

If you don't want to keep hidden tabs around, there is an option in Tab Stash's settings to completely disable the behavior:
1. Open the Tab Stash menu (the button to the left of the search bar)
2. Choose "Options..."
3. Under "Tab and Memory Management", choose "Close the tab immediately"

Note that by default, if you accumulate too many hidden tabs, Tab Stash will automatically unload the older ones to avoid consuming too many resources. You can adjust how aggressive the unloading is by tuning some of the advanced options. However, the defaults should work well even on lower-powered systems (Tab Stash is pretty aggressive at unloading by default).

Hope this helps! Let me know if you have any follow-up questions.
