### ISSUE TITLE
When un-stashing multiple tabs suspend them all.

### ISSUE THREAD

**Issue by rayman89** [josh-berry/tab-stash#276]
When un stashing a big stash the ram and cpu goes crazy I think it will help if the addon suspends the tabs as they open or opens them already suspended if that´s possible like for example the addon "tab session manager" does. This also makes the process of opening a bunch of tabs (100+) be a lot faster.

**Comment by josh-berry** [comment]
Hi, thanks for reaching out! Your issue is already covered/duplicated by another issue, so please take a look at the original (and subscribe if you want updates):

* #129
