### ISSUE TITLE
Switching windows while opening tabs causes some (rest?) to open in new window

### ISSUE THREAD

**Issue by junkblocker** [josh-berry/tab-stash#28]
**Describe the bug**
If I open a stash with a few hundred tabs and switch browser windows while the tabs are being opened, some of the tabs get opened in the newly focused window. They should open in the original window when the open all tabs button was clicked.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Have two, (preferably empty to see the problem easily) browser windows available.
2. Have a stash with a couple of hundred or so tabs.
3. Click 'Open all tabs in this group' button in the sidebar
4. Quickly switch to the other window while tabs are still being opened.
5. Notice that some tabs got opened in the new window we just switched to.

**Expected behavior**
All tabs should open in the original window the "Open all tabs" button was clicked in.

**Screenshots**
.

**Desktop (please complete the following information):**
 - OS: Mac
 - Firefox Browser Version: 68.0

**Additional context**
.

**Comment by josh-berry** [comment]
Hi, thanks for the report and sorry for the inconvenience! And especially thanks for the detailed steps; they made it quite easy to reproduce the problem on my end.

I think I've figured out why this is happening. There was one place in the code where we open new tabs (if we can't find any hidden/recently-closed tabs), and we don't tell Firefox which window they're for, so Firefox just puts them in whatever window is active.

I have a fix ready to go and will include it in the next release.

**Comment by josh-berry** [comment]
This should be fixed in (just-released) Tab Stash 2.4. Thanks again for the report!
