### ISSUE TITLE
is there anyway of recovering previous tabs stashed?

### ISSUE THREAD

**Issue by bear1701** [josh-berry/tab-stash#280]
### System Details

- **OS Version:** [e.g. Windows 10, or Ubuntu 18.04]
- **Browser Version:** [e.g. Firefox 60.0.2]
- **Tab Stash Version:** [check the Tab Stash entry in `about:addons`]

**Comment by bear1701** [comment]
to make things clearer i had to uninstall and reinstall my browser .... and appear to have lost all my stashed tabs

**Comment by josh-berry** [comment]
Tab Stash stores everything in your browser bookmarks, so if you've uninstalled/reinstalled your browser and you deleted your browser profile, then I'm afraid there's no way to restore.

The only thing I can say is if you were signed in to Firefox Sync before, signing in again should restore your bookmarks, settings, extensions, etc. Or if you happened to save a backup of your profile, you might be able to extract your bookmarks from that.
