### ISSUE TITLE
Do not put saved with tabstash tabs into hidden section

### ISSUE THREAD

**Issue by KM017** [josh-berry/tab-stash#283]
### Problem Statement
right now, when i save tabs using tabstash, tabs a) moved into other bookmars (expected) b) being moved into hidden tabs section (not expected); while using sycn b/w my devices i still see this tabs as opened, i d like to prevent it, otherwise (now) i have to manually go thru the hidden tabs and close them.

### Preferred Solution(s)
when tab is hidden into tabstash, it should not apperar in hidden tabs (should be considered as closed)

### Additional Context

<img width="663" alt="show hidden" src="https://user-images.githubusercontent.com/77667151/183867304-cc91e4d8-930c-46a3-bba4-fc924264f15c.png">

<img width="664" alt="inside hidden" src="https://user-images.githubusercontent.com/77667151/183867341-c0554892-b89d-4ba7-a77e-dbe67a81b029.png">

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
You can turn this behavior off in the Tab Stash options by choosing the option to "Close the tab immediately".

<img width="656" alt="Screen Shot 2022-08-12 at 19 34 41" src="https://user-images.githubusercontent.com/1203893/184465291-5e8612fd-02de-4e75-9695-b397121f73f8.png">

Hope this helps, let me know if you have any more questions!
