### ISSUE TITLE
Feature/button to close tabs belonging to a group

### ISSUE THREAD

**Issue by NicoForce** [josh-berry/tab-stash#284]
### Problem Statement

I'm able to open multiple groups, but I'm unable to close those groups just as easily (the only option I see is to "delete this group" but that wouldn't close open tabs related to that group)

### Preferred Solution(s)

There's a button to "Open all tabs in this group", could there be a button that's "Close all tabs in this group"?

### Additional Context

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Sorry for the delayed response here—this is a good idea and I'll definitely keep it in mind! I'm thinking an Alt+Click (/ Option+Click) on the "delete group" icon would work for this—I'm a little hesitant to add more buttons to the UI because I don't want people to get overwhelmed.

**Comment by kamil-cy** [comment]
Hi, this button would be also very useful to me. And... I have an idea how to not overwhelm people, just allow new buttons to be show/hide on in add-on option's. So for current users nothing will be changed, but if someone wants an additional `button to close tabs belonging to a group`, then this button can be enabled in options, everybody will be happy. You've created a great and handy add-on, so with this new button it would useful even more.

**Comment by tavareshugo** [comment]
+1 for this feature.

From a UI perspective, I would also add that using `x` as the icon to delete a group is confusing - when I started using the extension I thought this was to close all the tabs in the group (as an `x` is the usual icon in our windows used to do this). 
I think a trash bin icon would be more intuitive as "delete a group" and the cross could be used as "close all tabs belonging to this group". 
I know that's not as backward-compatible, but just a thought/suggestion. 

(and thanks for the work on this extension, quite enjoying it so far)

**Comment by tavareshugo** [comment]
I just noticed #207, which I guess would implement this 🎉

**Comment by cognitiaclaeves** [comment]
It looks like #207 is a year out of date. Also, in that PR, @josh-berry mentions using an alt- kind of key to click on the 'delete group' button. ... I wanted to point out that I wouldn't want to overload that button at all, mostly due to the fact that there is no confirmation before the group is deleted. Quite the opposite, I wanted to take that button off the groups because of that reason. I don't believe that the tooltip changes when you hold down the modifier button, either. So it will just look like you are deleting a group, and you won't have confirmation until it's done. There is a popup to undo, but I'd rather not make the mistake than make it and trust that I'll be able to undo it.

**Comment by tavareshugo** [comment]
👍 @cognitiaclaeves 

Another possibility: 

- Change the default behaviour of this button to be "close all tabs belonging to this group". 
- The `Alt + click` behaviour would then be "delete this group". If possible, the icon could even change to a trash bin when the `Alt` key is pressed over the icon. 

That is maybe a compromise between the two: the default behaviour becomes "safer" but the original behaviour is still available to users. 

(unfortunately I have zero experience with TypeScript/JavaScript, so not much help in terms of suggesting a PR)

**Comment by josh-berry** [comment]
I happened to pick this up as part of some other feature work I was doing. In the next release, there will be an option inside a menu to close/hide all the open tabs in a particular group. Hope this helps!
