### ISSUE TITLE
Unstashing by drag drop deletes tabs

### ISSUE THREAD

**Issue by safetycar** [josh-berry/tab-stash#293]
### System Details

- **OS Version:** Windows 10
- **Browser Version:** Firefox 105.0.1
- **Tab Stash Version:**  2.11.0.1

**Installed Browser Extensions:**

- Tried without extensions.

### Describe the Bug

I've been seeing unreliable behaviors about drag and drop to unstash.
Previously it was possible to move from a group to unstash but now I get deleted tab messages.
Most of the times they are really deleted. Other times the message appears but the tab still opens.

### Steps to Reproduce

1. Stash a tab.
2. Drag and drop it from the group to the unstashed tabs section.
3. See the floating message about the deleted tab.

### Expected Behavior

Move the tab back to the firefox tab bar.

### Impact

It's more comfortable for managing with tab stash in full page mode.

### Additional Details

Possibly behaving differently with a single tab as opposed to multi-selections?
And I have some doubts if the tab having been open recently is affecting it too.

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Yikes, thanks for pointing this out!

I played around with it a bit myself, and I see exactly what you mean. As a workaround, you can select the tab (click its icon) before dragging and dropping and then it seems to do the right thing.

Let me see what I can do to get a fix out quickly.

**Comment by josh-berry** [comment]
Should be fixed in the next release.

**Comment by safetycar** [comment]
Thanks for the quick reply.
Since I'm not able to test the fix I wonder if you could make sure that by moving with one selected item (like you explained) the message of the deleted tab no longer appears? Without the fix I'm seeing the tab opening but also a (false) message saying that it is deleted. And I'm not sure if the fix covers that issue.

**Comment by safetycar** [comment]
Just to add a bit to the conversation. Even if it's "technically correct", the normal user still sees an existing tab, as opposed to what happens when you click the X button, making it disappear.
But no problem with leaving it to be considered for future.
