### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by whysthatso** [josh-berry/tab-stash#294]
### Crash Details

```text
i've just had tab stash crash on me for the first time.

and i must say i rarely have seen such a graceful handling of extension crashes. the popup telling me about the crash with the 'information about this crash' section telling me exactly what went wrong in which tab, so i could discard the tab and go on with my life.

so wholesome :)

thank you for your work.

this is just general feedback, feel free to close this issue.
```

### Installed Extensions

- 

### Describe the Crash

n/a

**Comment by josh-berry** [comment]
haha, I think this is the most wholesome crash report I have ever received. :) You're quite welcome, and I'm glad the crash notification was a good experience!

That said, I try very hard to make sure you never have to see it to begin with—so if the crash happens again, please do send the details my way and I'll be happy to look into it!
