### ISSUE TITLE
Option to immediately load restored tabs

### ISSUE THREAD

**Issue by JffLcrx** [josh-berry/tab-stash#298]
### Question
 Hello,
I've been using Tab Stash for quite some time now, but since the last update (or was it 2..?!) when I click on "Open all tabs in this group (hold Ctrl to open in background)"  the tabs open but none but the last one actually load. Before all of the tabs would open and load.

It could be some config in Firefox, but I've been searching through both Tab Stash and Firefox settings and could not find why this happen. I could not find anything on google or here. So, sorry if that has been asked before.

Thank you for your time.

### System Details

- **OS Version:** Windows 10 Home
- **Browser Version:** Firefox 106.0.1 (64-bit)
- **Tab Stash Version:** 2.11.1

**Comment by josh-berry** [comment]
Yes, this is a recent change in behavior in 2.11. The reason for the change is that opening large numbers of tabs at once can sometimes cause hangs/freezes and instability—if Firefox tries to load lots of tabs at once, it can sometimes use so many resources that it brings your entire system (not just Firefox) to a complete standstill, and it can take a long time to recover from this situation. (See #129 for an example of this.)

So now tabs are only loaded "on demand" (i.e. once you actually switch to the tab). You do have to click on each and every tab to get it to load, but doing so spaces things out a bit and reduces the overall load on your system.

I'm curious if the old behavior is something you depended on / found useful? If it's important to have tabs loaded immediately, I can look into adding an option to restore the old behavior (though it would stay off by default for the aforementioned reason).

**Comment by JffLcrx** [comment]
Thank you for the answer.
I have about 20 groups of 8 to 15 tabs each that I open in different Firefox windows, all depending on the type of work I'll be doing at the moment and then replace/remove tabs as I need/don't need them anymore. As I need to close and open Firefox several times during the day, I found that loading all tabs of selected groups/windows is an advantage, as opposed to clicking every tabs individually. 
If you're able to add an option to choose to load all tabs or not, that'll be great.
If not, no worries, you don't need to lose your time for just one guy :)

**Comment by josh-berry** [comment]
Got it, thanks for explaining. I'll keep this in mind!

**Comment by AdrianSkar** [comment]
Yes please, add this option!! I also relied much on this behavior as I'd restore several tabs and check the first while the other ones loaded. Now I have to cycle over them or wait for them to load individually as I reach them.

**Comment by josh-berry** [comment]
I think I have a good default "happy medium" now, which is to load only a few tabs at a time until they're all loaded. This should avoid overloading your system, but still get everything loaded without you having to click anything.

The current behavior (create tabs but don't load them until clicked) is still going to be available as an option, but the default in the next release will be to load tabs proactively once again. (Just more slowly this time!)

**Comment by JffLcrx** [comment]
Thank again Josh!
