### ISSUE TITLE
Button to Clear Filtered/Searched items

### ISSUE THREAD

**Issue by ece81807306** [josh-berry/tab-stash#299]
### Problem Statement

After completing a search required to select and delete the text. 

### Preferred Solution(s)

an **X** next to the Caret that allows the search to be cleared  

### Additional Context

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
I agree such a button would be useful, I just haven't gotten around to adding one yet. :)

In the meantime, while the cursor is inside the search field, you can press "Esc" to clear it. Hope this helps!

**Comment by josh-berry** [comment]
This will be in the next release!

**Comment by kamesen99** [comment]
Thank you for this!
