### ISSUE TITLE
Tab icon not visible 

### ISSUE THREAD

**Issue by kstev99** [josh-berry/tab-stash#308]
### System Details

Windows 11 (Insider 22623.1020)
Firefox 107.01
TAB STASH 2.12.0.1

- **OS Version:** [e.g. Windows 10, or Ubuntu 18.04]
- **Browser Version:** [e.g. Firefox 60.0.2]
- **Tab Stash Version:** [check the Tab Stash entry in `about:addons`]

**Installed Browser Extensions:**

Proton Dark Theme
System Default (Dark) theme
BlackRed theme
-
-

### Describe the Bug

After the last update, the icon on the tab is too dark to see when using a dark theme in firefox.  I keep Tab Stash pinned to the left side along with my email, and it is just a Black hole with no visible icon

### Expected Behavior

I would like to see an icon
l

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Sorry about that; when I make style changes, I always test in both dark mode and light mode, but I guess I missed this.

It looks like this happened not even due to a style change, but a change to how Tab Stash is built. That somehow changed which icon was being referred to for the UI page. I'll make sure this is fixed for the next release.

**Comment by kstev99** [comment]
Thanks!  At least I know that it's not just me

**Comment by kstev99** [comment]
Is there any workaround for this?  I keep accidentally closing my Tab Stash (Pinned) because it looks like a blank space.

**Comment by josh-berry** [comment]
Sadly, not right now—if you're technically-inclined, you could run a dev build of Tab Stash, but that has its own annoyances (Firefox will remove unsigned developer extensions on every restart). There are instructions in [the contributor guidelines](https://github.com/josh-berry/tab-stash/blob/master/docs/contributing.md#getting-started).

**Comment by josh-berry** [comment]
2.12.1 should be released soon, with a fix for the icon color. Hope this helps!
