### ISSUE TITLE
Randomly stashing tabs

### ISSUE THREAD

**Issue by ahyou-mug** [josh-berry/tab-stash#312]
### System Details

- **OS Version:** [Ubuntu 20.04]
- **Browser Version:** [Firefox 108]
- **Tab Stash Version:** [2.12.0.1]

**Installed Browser Extensions:**
N/a - no known conflicts. No other extensions active

### Steps to Reproduce

- Open some tabs from tab stash (sidebar?)
- click tab stash icon in menu bar
- all tabs are closed and saved to dated folder (even when they already belong to a folder - what are the consequences of repeated duplication of bookmarks)

### Additional Details

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
I'm afraid I don't understand what your concern here is?

* Can you explain exactly what happened that was not expected? Was it creating duplicates or something else?
* What did you expect to happen instead?

**Comment by ahyou-mug** [comment]
Sorry dude, not sure what happened there - I swear I filled that bit in..
When clicking the icon in the menubar it closes/stashes all tabs to a new folder and then opens the tabstash menu. It's a bit of a weird thing because I wouldn't expect it to function that way. Would typically expect it to open in a new tab and to not close the tabs that are open in the current window. It also runs the cpu usage on at least one core up to 102%. It actually did that a couple of times last night so I've since uninstalled it. It also threw 4 erros which I also included in the error report but which are now not there??? wth?

**Comment by josh-berry** [comment]
> When clicking the icon in the menubar it closes/stashes all tabs to a new folder and then opens the tabstash menu. It's a bit of a weird thing because I wouldn't expect it to function that way. Would typically expect it to open in a new tab and to not close the tabs that are open in the current window.

You can change this behavior in the settings if you want—I agree it's not a great default (and I'm planning to change it), but it's a holdover from the very early days when there was only a sidebar view. Sounds like the options you want are:

<img width="495" alt="Screenshot 2022-12-19 at 09 41 46" src="https://user-images.githubusercontent.com/1203893/208487028-b1fbd661-80a2-4b5d-9fdb-e24100e3c058.png">

> It also runs the cpu usage on at least one core up to 102%. It actually did that a couple of times last night so I've since uninstalled it.

That definitely should not be happening, even if you have a very large stash or lots of open windows/tabs.  A few questions for you:

* How many windows/tabs would you guess you have open?
* How many bookmarks in total do you have? (Again, rough guess is fine)
* How many groups/tabs did you have in Tab Stash?
* How long have you been using Tab Stash? (just started / days / months / years?)

I occasionally get reports of high CPU, but it's never happened for me and I've never been able to narrow it down.

> It also threw 4 erros which I also included in the error report but which are now not there??? wth?

Do you remember anything about the errors? Were they complaining about timeouts or something else?

**Comment by josh-berry** [comment]
Hi @ahyou-mug, I'm going to close this since you mentioned you uninstalled Tab Stash, but if you have any answers to my questions above, please do leave a comment—it would be really helpful for me to narrow things down in case other users hit the same issues you did. Thanks!
