### ISSUE TITLE
Chose stash group target

### ISSUE THREAD

**Issue by dreamflasher** [josh-berry/tab-stash#315]
Currently tabs are stashed to new groups. It would be great if it were possible in the tab context menu (single and multiple tabs) to chose the target group where the tabs are going to be stashed into. 

This is different from https://github.com/josh-berry/tab-stash/issues/110 – which is a great request as well, this request here allows for different contexts (GTD style).

**Comment by josh-berry** [comment]
Hi, thanks for reaching out! Your issue is already covered/duplicated by another issue, so please take a look at the original (and subscribe if you want updates):

* #30

**Comment by dreamflasher** [comment]
I searched for dups but didn't find it, yes absolutely a dupe, thanks!
