### ISSUE TITLE
Keyboard shortcut to stash selected tabs

### ISSUE THREAD

**Issue by iPaulis** [josh-berry/tab-stash#32]
**Is your feature request related to a problem? Please describe.**
I would like to stash selected tabs with a shortcut. Right now, we can either stash all tabs, or only the active tab, there is no way to stash several selected tabs with a shortcut.

**Describe the solution you'd like**
I think a shortcut for this would be very useful. It would be more convenient and time saving to have this option than having to right click and select from the menu.

**Comment by josh-berry** [comment]
Hi, the Ctrl+Alt+T (or Ctrl+Shift+T on Mac) shortcut will stash only the selected tabs if multiple tabs are selected. You can always use the Ctrl+Alt+W / Ctrl+Shift+W (Mac) shortcut to stash the currently-active tab.

I realized from looking at the documentation that this isn't necessarily obvious, so I will try to clarify it. I missed adding a note about the multi-selection behavior for keyboard shortcuts when that feature was added to the menus/toolbar button—but it's all the same code and so works the same regardless of using the menu vs. the toolbar vs. the keyboard.

Does this address your concern?

**Comment by iPaulis** [comment]
Yes, that works perfectly fine. Thank you.
