### ISSUE TITLE
Scrolling while dragging does not work

### ISSUE THREAD

**Issue by EmmanuelMess** [josh-berry/tab-stash#320]
### System Details

- **OS Version:** Ubuntu 20.04
- **Browser Version:** Waterfox G5.1.1
- **Tab Stash Version:** 2.12.0.1

### Describe the Bug

On the TabStash tab, dragging a stash breaks the scroll wheel

### Steps to Reproduce

1. Go to the TabStash tab
2. Drag a stash
3. Scroll with the mouse wheel

### Expected Behavior

You should be able to scroll the page while dragging

### Impact

Very small

### Additional Details

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Thanks for letting me know; I wasn't able to reproduce this on my Mac, so I'm suspecting it might be a Firefox issue on Linux. I don't have a Linux setup handy at the moment but I'll try to look into it further when I get a chance!

**Comment by josh-berry** [comment]
So I checked both Windows and Linux, as well as some other non-Tab Stash web apps that do drag and drop, and this appears to be an issue with Firefox—none of the examples I tried in either OS allow for scrolling using the scroll wheel while a drag operation is in progress.

There's nothing Tab Stash can do here, unfortunately—I would suggest raising the issue with Firefox.
