### ISSUE TITLE
Memory Usage

### ISSUE THREAD

**Issue by AussieGit** [josh-berry/tab-stash#322]
This is more of a back up/memory usage but I am trying to find what the bottle neck is when I open more than one Firefox tab simultaneously and Firefox slows to a crawl & doing any other tasks within Firefox does nothing until the tabs are fully loaded. I have about 2k tabs stashed with approx 50 unstashed tabs. 

Hoping it isnt as Tabstash is in my top 5 extensions (too hard having a best one) and I couldnt work without TabStash

My question if I disable TabStash to see if it is the culprit, will I lose all my stashed tabs when I re-enable it? IF so, can they be resored from Bookmarks backup?

-Win 10 Pro
-Firefox 108.0.2
-TabStash 2.12.0.1

**Comment by josh-berry** [comment]
Hi @AussieGit, nice to hear from you again. :)

No, disabling Tab Stash will not cause you to lose anything. Everything is saved in your bookmarks so even if you uninstall Tab Stash entirely, your stashed tabs will still be there for Tab Stash to pick up once it's enabled again. (Though uninstalling Tab Stash entirely will cause you to lose Tab Stash's record of previously-deleted items, since those are NOT saved in your bookmarks.)

If you DO find that disabling Tab Stash helps with the memory and CPU usage, I'd really love to hear more about exactly what situations are causing slowdowns and/or high memory usage. I've heard a few complaints from others, but nobody's given me enough information to narrow it down, and it's something I'd like to fix quickly.

Anyway, let me know what you find!

**Comment by josh-berry** [comment]
I'll go ahead and close this out, but do let me know if Tab Stash was the source of the high memory/CPU usage and we can reopen it. Thanks!

**Comment by philippjbauer** [comment]
Sorry to wake the dead (issue) here. I just realized that tab stash used about 500 MB of RAM by disabling the extension. I have relatively few tabs stashed (low 100s). I restarted the browser within the last 24 hours. I'm not well versed in FF extension development and the tools you could use to get an accurate picture. If you let me know how I can help debugging this, I'll try to find a bit of time for it.

**Comment by josh-berry** [comment]
Hi @philippjbauer, please go ahead and open a new issue for this. When you do, it would be helpful to know roughly how many bookmarks (in total, inside and outside of Tab Stash) and how many open tabs you typically have, just to get a baseline.

If you're familiar with JS/web development, you can use the "Memory" tab in Firefox's developer tools to take a heap snapshot and dig into what's happening (at least for that particular page). Regardless, I can troubleshoot with you further on the new issue. Thanks!

**Comment by johnnieo** [comment]
Added tab stash to my system last night and began experimenting
This morning, Firefox is lagging badly, emails are loading slowly,
links are loading slowly, fans are ramping up and down constantly
and temperatures have climbed about 15 degrees into caution and above
zone. 

My machine runs 28gb ram, with LMDE 5 (Elsie) installed and Firefox ESR 115.7 (oesr) 64 bit. 
Have five FF windows open, with total of 200-300 tabs. Three to four links stashed. Prior
to TS install system ran clear and clean. Open to discussing this is detail if it will help
to diagnose and provide details for members. Thx.  Below are a few quick vitals:
17-23% CPU usage??
MemTotal: 24,476,516
MemFree: 728,100
Swap: 3.5gb (44% of 8.2gb)

**Comment by josh-berry** [comment]
Hi @johnnieo, please open a new issue and I'd be happy to help you troubleshoot further.

Firefox provides `about:processes` and `about:memory` to help you get a detailed breakdown of what is using CPU/RAM in your browser; this is probably the best place to start to dig into what might be going on. Hope this helps as a starting place!

**Comment by josh-berry** [comment]
I'm going to lock this issue now just to encourage folks with new problems to open new GitHub issues.
