### ISSUE TITLE
Oops! Something went wrong - "NanoPortError"

### ISSUE THREAD

**Issue by junkblocker** [josh-berry/tab-stash#335]
### Crash Details

```text
Browser: Mozilla Firefox 110.0 20230214102510 (linux x86-64)
Extension: Tab Stash 2.12.0.1 (normal)

favicons: Request timed out
NanoPortError@moz-extension://24caa676-472a-49f1-bbf3-0e0dcf32286f/assets/menu.js:2339:1
NanoTimeoutError@moz-extension://24caa676-472a-49f1-bbf3-0e0dcf32286f/assets/menu.js:2343:5
request/</<.timeout_id<@moz-extension://24caa676-472a-49f1-bbf3-0e0dcf32286f/assets/menu.js:2245:18
```

### Installed Extensions

- uBlock Origin
- AdBlocker Ultimate
- Video DownloadHelper
- I don't care about cookies
- SponsorBlock - Skip Sponsorships on YouTube
- Tab Session Manager
- User-Agent Switcher and Manager
- SingleFile
- Dictionary Anywhere
- Tab Stash
- CanvasBlocker
- Snap Links Plus
- Forget Me Not - Forget cookies & other data
- Private Bookmarks
- Firefox Relay
- Firefox Color
- KeePassXC-Browser
- Violentmonkey
- Firefox Translations
- Plasma Integration
- No Coin
- Temporary Containers
- Offline QR Code Generator
- Add custom search engine
- Bookmark Dupes
- Tab Counter
- Duplicate Tabs Closer
- Redirect AMP to HTML
- SCDL SoundCloud Downloader
- MarkDownload - Markdown Web Clipper
- LibRedirect
- Neat URL
- Merge Windows
- First Party Isolation
- weAutoPagerize
- Extension source viewer
- Containerise
- Display \#Anchors
- ff2mpv
- JavaScript Errors Notifier
- Behave!
- Firenvim
- Lovely forks
- Go to random tab
- Opt Out - automated GDPR and CCPA requests
- Open in Sourcegraph
- Lizard
- Long Press New Tab
- What Hacker News Says
- Peekier search engine
- tabclip
- Module Linker
- Daily Tabs with delay and sync
- Default Container Cleaner

Disabled:

- cliget
- Virtual Json Viewer

### Describe the Crash

1. I was just opening a few links by hand.

### Expected Behavior

Didn't expect to see the addon crash message.

### Impact

None

**Comment by junkblocker** [comment]
Note: In your bug template, a way for users to get complete addons list will be helpful. I found this online that I used for Linux with modifications

``` bash
 grep -oP '(?<=\},\"name\":\")([^"]*)' ~/.mozilla/firefox/*.default/addons.json
```

**Comment by junkblocker** [comment]
Happened again. I think this is happening with me opening a bunch of tabs with 0 delay using the 'Daily Tabs with delay and sync' option.

**Comment by josh-berry** [comment]
> Happened again. I think this is happening with me opening a bunch of tabs with 0 delay using the 'Daily Tabs with delay and sync' option.

That would make sense—if your system is so overloaded that Firefox never gives Tab Stash a chance to run, you might hit this error. This crash will happen whenever the Tab Stash UI isn't getting a response from Tab Stash's background page/service in a set amount of time (10 seconds by default).

Does the crash stop happening if you open a fewer number of tabs at once?

**Comment by junkblocker** [comment]
The crash doesn't happen consistently even with the same number of tabs. To me this sounds like something tab-stash handles fine via self recovery automatically and shouldn't even be shown to the user. It's a warning the user can do nothing about and just be tempted to file bugs.

**Comment by junkblocker** [comment]
And just now it happened when I was doing nothing with the browser. Switched to it and saw the error. Since I don't even care about favicons I am now going to hide all crash reports for a week.

**Comment by josh-berry** [comment]
If requests don't complete in a timely fashion (or at all), there are often other symptoms that will crop up even if a crash isn't triggered—for example, deleted items not being recorded (which would break the undo functionality), the UI not updating correctly or getting stuck, and so on.

So I actually want bug reports like these because they tell me where Tab Stash isn't performing well, and I can work on fixing the performance problems before they become bigger problems (especially since I expect peoples' stashes to grow over time as they save more things).

I do understand it can be a nuisance, though, which is why turning off crash reports is a thing.

For the next release, I'll decrease the number of favicons that get fetched in the same request—let's see if that stops the crashes. (You're also welcome to pull from `master` once the commit shows up, if you don't want to wait for the next release—though the standard caveats apply for running dev/unreleased versions of any software.)

Hope this helps and sorry for the trouble!

**Comment by junkblocker** [comment]
Well, my experience with this is a forever temporary needing to disable this without it getting resolved. And it won't because of the way I browse. So I'd really like to just be able to forever disable this. If you don't want to lose others' reports on this you could allow permanent disabling after this has been hit a number of times. But as it stands, it is now at a severely irritating stage for me and and the next time I see this I'll just have to accept defeat and move on from the addon.

**Comment by josh-berry** [comment]
Sorry to hear that. Given that you keep hitting it and it's so irritating, I'll try to push out a bugfix release as soon as I can.

**Comment by josh-berry** [comment]
2.12.1 will be released soon, which should hopefully stop the crashes from happening. Hope this helps!
