### ISSUE TITLE
Even smaller SideBar 

### ISSUE THREAD

**Issue by choxer** [josh-berry/tab-stash#336]
### Problem Statement

Tab Stash and the Sidebar-View is perfect for my use, but there seems to be a minimum width and it's too large (even in "compact"-setting). 

### Preferred Solution(s)

I'd love to be able to minimise the sidebar as far as I want. 

### Alternative Solution(s)

For my needs, an icon view would even suffice.

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Thanks for your feature request! Unfortunately, the width of the sidebar itself is something that is dictated entirely by the browser, so Tab Stash (and extensions in general) can't control it. Sorry to be the bearer of bad news!
