### ISSUE TITLE
Dark icon

### ISSUE THREAD

**Issue by happysurf** [josh-berry/tab-stash#34]
In the Firefox addons dark page, the tab-stash icon is hard to see, will be great make a medium gray or something like that.
For apply the dark theme set **browser.in-content.dark-mode** to **true** (default in Firefox 70 beta).

![Icons3](https://user-images.githubusercontent.com/13637587/66895182-7248ab80-eff2-11e9-8cd3-d3c7d6c66922.png)

**Comment by josh-berry** [comment]
I have Firefox Dev Edition (71.0b2), with the setting you mentioned applied (as you say, it's the default), and don't see a dark page like what you show in your screenshot. This is with the preinstalled "Dark" theme.

Are you sure you're not using some other custom theme/extension that might be causing this?

**Comment by happysurf** [comment]
Some tests show that this is related to the Windows 10 system's theme. If the system's theme is not dark, an additional pref ui.systemUsesDarkTheme=1 is required.

**Comment by josh-berry** [comment]
The next release will have a more neutral icon that should hopefully be easy to see in both light and dark modes.
