### ISSUE TITLE
Add support for sub folder for better organizing

### ISSUE THREAD

**Issue by bonnjalal** [josh-berry/tab-stash#351]
### Problem Statement
When I want to organize my slashed tabs, for example: I slashed tabs under name **Linux** and I want to move some already slashed tabs on linux to sub folder **fedora**.

even when I organize tabs from firefox bookmarks manager, the sub folder does not show up on the slashed tabs, like it does not exists.

### Preferred Solution(s)

Add support for organizing and creating sub folder from the extension itself

### Alternative Solution(s)

At least when we organize the tabs from bookmark manager the sub folders and its content shows up on the slash tas extension

### Additional Context

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, thanks for reaching out! Your issue is already covered/duplicated by another issue, so please take a look at the original (and subscribe if you want updates):

* #14
