### ISSUE TITLE
Contianer Expansion

### ISSUE THREAD

**Issue by ccap86** [josh-berry/tab-stash#352]
### Problem Statement

The quantity of containers available is limited to only four.

I just downloaded the this  app, and plan to use it across work and personal use(@home not at work). The capability to create containers for specific projects, courses, hobbies, etc...., would keep the organization more manageable (e.g., one stash for project A, one stash for project B etc, would become an origizational nightmare overtime.) 

### Preferred Solution(s)

1. Increase the number of of containers (unlimited??)
2. Capability to give specific names (categories)
3. Capability to create "child" stashes (see below for alt)
4.  Drag and drop (I believe this is already built in)

### Alternative Solution(s)

 child Stash (Project A)
     |
     -----> tab a
     -----> tab b
----> child Stash (Project B)
     |
     -----> tab a
     -----> tab b
Parent Stash (Personal)
|
---->child Stash (Class Underwater Basket Weaving)
       |
       ----> class 1 
              |
              ----- Stash (tab)
              ------Stash (tab)
      |
      ----> class 2
              |
              ----- Stash (tab)
              ------Stash (tab)

............. And so on.

### Additional Context

Thank you, and I apologize if this is already a feature, but I could not find any specifics about containers.

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, I'm a bit confused about what you're asking—if you're asking about Firefox's containers feature (which gives you different identities for different tabs), or Tab Stash's groups feature (where you save specific tabs into different groups).

Regarding Tab Stash groups, you can create as many as you want—Tab Stash allows you to create groups by clicking the "Create a new group" icon in the "Unstashed Tabs" / "Open Tabs" section. You can select tabs by clicking on their icons, and use drag-and-drop to keep things organized.

Regarding Firefox containers, Tab Stash doesn't actually manage containers at all, but Mozilla offers an official extension called [Firefox Multi-Account Containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/) which you can use to manage Firefox's containers. You can similarly create as many containers as you want—create, rename, change colors, etc. through that extension.

Hope this helps, let me know if I answered your question?

**Comment by ccap86** [comment]
Hi Josh, sorry, I just started using firefox (been using chrome) and thought 'container' was part of your app. I will look into container info more, but for your app, I am using the group functionality, I was basically looking for sub-stashes. 

For example, I'd like to have a stash for work, and have the option to have, in addition to "tabs" within a stash, is to have a sub-stash with its own stash group. 

Currently, I have a project at work that I have about twenty tabs in one stash or group. However, I would like to organize those tabs into specific groups within one, parent, stash instead of one large group of twenty tabs; i don't always work with all the tab, but I open a group of three or four so it would be convenient to be able to just select the sub-stash to open instead of having to select each tab individually and open it. Currently, i just physically organized them so they are next to each other in the list. 

I'm not sure if you are familiar with Obsidian but it is a powerful note taking software (https://obsidian.md/) and I keep the groups (stash group) as a node (I use your export function to select all>copy but it would be nice to export specific groups) so it would help with that use as well if each stash group/sub-stash group had its own url. I will make a separate ticket for that once I can articulate what I'm requesting on this one.
![stash_sub-stash_example](https://user-images.githubusercontent.com/85033044/229293567-0b30a3da-5687-4cf1-a827-27aadafe222c.png)


Thanks for reviewing,
chris

**Comment by josh-berry** [comment]
Hi Chris, got it, thanks for clarifying!

The workflow you're describing makes sense—I have heard of Obsidian but haven't used it myself. But I definitely understand juggling multiple projects and wanting to sub-divide within a project.

There are a couple open feature requests that might already cover some of what you're talking about:
* #14 
* #120 

Feel free to have a look at those and add your thoughts in those tickets. Or if there's something that's not covered by those two, do let me know here!

Thanks,
Josh

**Comment by ccap86** [comment]
Hi Josh,

Yes, those would satisfy my needs. Sorry, should have caught these. 

Again, thanks for taking the time to respond and for this great app!
-chris

**Comment by josh-berry** [comment]
No problem, I'll go ahead and mark this as a duplicate. Thanks for your input!
