### ISSUE TITLE
how do i undo my deleted stash ?

### ISSUE THREAD

**Issue by A-W0lf** [josh-berry/tab-stash#361]
### Question

 
how do i undo my deleted stash ?

### System Details

- **OS Version:** [e.g. Windows 10, or Ubuntu 18.04]
- **Browser Version:** [e.g. Firefox 60.0.2]
- **Tab Stash Version:** [check the Tab Stash entry in `about:addons`]

**Comment by A-W0lf** [comment]
how do i undo my deleted stash ?

**Comment by josh-berry** [comment]
To the left of the search box in the Tab Stash UI, there is a button that opens a menu. Open the menu and choose "Deleted Items...". This will take you to the deleted-items page, which will show everything you've deleted recently. Find the items you want to restore and click the blue "Stash" button to restore them.

Hope this helps!
