### ISSUE TITLE
[Multi-Selection] Move Multiple Tabs into Existing Group

### ISSUE THREAD

**Issue by ShynnSup** [josh-berry/tab-stash#363]
### Problem Statement

Organizing existing tabs into existing stash groups: When selecting tabs only options available are: stash this tab to a new group. I don't want it to be a new group, I want to be one of the existing. 

Also, I can't select multiple tabs from 'Open Tabs' stash and move them into a new Group. 

### Preferred Solution(s)

Add option in right click menu containing existing stash group names
Allow multiple selection of tabs to move them into another group

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, you can do all of this today through the Tab Stash UI. When you open the UI, you can select one or more tabs by clicking on their icons (shift+click is also supported):

![Screenshot 2023-05-06 at 17 24 12](https://user-images.githubusercontent.com/1203893/236651658-d2be1dca-95d0-49dc-8db3-1f43dbc091a6.png)

![Screenshot 2023-05-06 at 17 25 09](https://user-images.githubusercontent.com/1203893/236651678-bc83eb5e-e594-4c98-97e0-7c00e9403af9.png)

Then you can use drag-and-drop, the toolbar buttons on each stash group, or the selection menu at the top (shown below) to move selected tabs where you want them to go:

![Screenshot 2023-05-06 at 17 26 41](https://user-images.githubusercontent.com/1203893/236651710-5e2f5749-5f20-4077-a26c-6a99f66ddc3b.png)

Hope this helps!

**Comment by YousufSSyed** [comment]
@josh-berry Can you add a setting to allow selecting multiple tabs without clicking their favicons?
