### ISSUE TITLE
Ability to have folders in stashed tabs.

### ISSUE THREAD

**Issue by Dennismn** [josh-berry/tab-stash#364]
### Problem Statement

I have a lot of bookmarks which I've organised with subfolders. Eg, I have a folder called Clothing which contains the folders: Apparel, Shoes, Accessories, Stores etc. However, since installing Tab Stash and making it my homepage, I've been migrating all of my bookmarks into Tab Stash for easier access, but I'm only able to put single tabs into a stash box. This means that I would have to create a stash box for each sub category listed and it takes up too much screen real estate and makes it more difficult to organise/keep track my tabs/bookmarks. Because it's much easier to have one box with folders in it, than 5 individual boxes.

### Preferred Solution

To solve this problem I would like to request the ability to have sub folders within a single stashbox. Much like how normal folders work, so I can have all my bookmarks as my homepage without any clutter and because I use Tab Stash as my homepage. 

I tried to search for it, but I'm not sure if this feature has been requested before, so thanks for making Tab Stash nonetheless.

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, thanks for reaching out! It actually has already been requested—here’s a link to the original request (and do subscribe if you want updates):

* #14
