### ISSUE TITLE
Request ability to pin stash box to fixed position.

### ISSUE THREAD

**Issue by Dennismn** [josh-berry/tab-stash#365]
### Problem Statement

I have a stash box that I use as my main stash box, however as you make more boxes, it moves further down the list and its position is replaced by the latest stash box.

### Preferred Solution(s)

I think having the option to pin a stash box to the top left position of the screen, or if possible, for any boxes to be pinned anywhere would be cool.

### Additional Context

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, thanks for reaching out! Your issue is already covered/duplicated by another issue, so please take a look at the original (and subscribe if you want updates):

* #124
