### ISSUE TITLE
Contention for a sidebar on firefox start between extensions

### ISSUE THREAD

**Issue by andrhua** [josh-berry/tab-stash#367]
### System Details

- **OS Version:** Arch Linux 6.3.3
- **Browser Version:** Firefox 113.0.1
- **Tab Stash Version:** 2.12.1

**Installed Browser Extensions:**

- [Sidebery](https://github.com/mbnuqw/sidebery)

### Describe the Bug

I noticed that for one profile firefox starts without sidebar, and I have to manually launch sidebery. However for another profile with tab stash and sidebery installed, there wasn't any problem, so I figured problem was in startup order.

### Steps to Reproduce

1. Install tab stash, enable it
2. Install sidebery, enable it
3. Close and start browser
4. Firefox starts without sidebar opened

### Expected Behavior

Sidebery is opened in sidebar on firefox start

### Possible workaround

In my case I was able to get rid of this problem by disabling and re-enabling tab stash in extensions menu. My uneducated guess is that startup order of extensions is registered in last-enabled fashion. It's possible that for other extensions you have to re-enable them, not tab stash.
![image](https://github.com/josh-berry/tab-stash/assets/15843809/7963eca4-231f-48f3-ba94-24346dfdf882) 
Perhaps it's worth adding it to "incompatible extensions" wiki page?

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi,

Whether the sidebar is opened or not on startup seems to be based entirely on whether it was open before Firefox was closed. You can also switch between sidebars (e.g. Sidebery or Tab Stash) using the dropdown at the top of the sidebar, and Firefox will remember which sidebar you had open last time.

Hope this helps to explain what you're seeing, let me know if you have any more questions!
