### ISSUE TITLE
Open&delete in tab view closes the tab itself

### ISSUE THREAD

**Issue by AnttiBoman** [josh-berry/tab-stash#37]
If I use "Show Stashed Tabs in a Tab" and click the yellow open&delete button in either a group or an individual item, the Tab Stash tab closes after the tab has (tabs have) been opened and deleted.

**Expected behavior**
Tab Stash tab should definitely stay open, and preferably as the active tab.

**Desktop:**
 - OS: Linux, Ubuntu 18.04
 - Firefox Browser Version: 70.0.1 (64-bit)

**Comment by josh-berry** [comment]
Hi, thanks for your suggestion. To get this behavior today, you can just pin the Tab Stash tab, and then it won't be closed when you un-stash something.

That said, you may not want to keep Tab Stash open as a pinned tab all the time. My own experience over time has been that sometimes I want Tab Stash to go away, and sometimes I don't—so this is something that I think is worth adding as a preference. I'll keep it in mind for a future release.

**Comment by josh-berry** [comment]
I've changed this behavior for the next release of Tab Stash (coming very soon, barring any serious bugs). Clicking on a tab (or the yellow open/delete button) will no longer close the Tab Stash tab.

If you'd like to restore a tab in the background, you can hold Ctrl (or Cmd on a Mac) while clicking the tab, just as you would if you're trying to open a link in a new background tab.

**Comment by josh-berry** [comment]
Tab Stash 2.5 was just released with this change. Hope you like it!

**Comment by AnttiBoman** [comment]
Thanks for the great work again! I'm glad we have your extension available and updated frequently!
