### ISSUE TITLE
Crash while Importing

### ISSUE THREAD

**Issue by gliptak** [josh-berry/tab-stash#371]
### Crash Details

```text
Will attach crash windows screenshot as I cannot seem to copy text or access other details
```

### Installed Extensions

- 

### Describe the Crash

Click Import
Paste into import field

```
<li><a href="https://github.com/" time_added="13202740" tags="">https://github.com</a></li>
```

Select Nothing [all in one group]
Unclick Fetch Icons
Click "Import"

### Expected Behavior

Doesn't crash

### Impact

While browser is somewhat functioning, have to restart to fully reset.

**Comment by gliptak** [comment]
![image](https://github.com/josh-berry/tab-stash/assets/50109/bfbfe5ab-ae88-451b-b103-4fd87bd2b26f)

**Comment by josh-berry** [comment]
Hi, thanks for reporting! I'm able to reproduce this on my side. The importer doesn't generally expect to be fed raw HTML, so it's choking on the fact that you have a URL followed by a closing tag:

```
<li><a href="https://github.com/" time_added="13202740" tags="">https://github.com</a></li>
it barfs here --------------------------------------------------------------------^
```

For now, you can work around this by inserting a space or similar so it's clear the `<` in `</a>` is not part of the URL.

I'll look into fixing this for the next release.

**Comment by gliptak** [comment]
thank you for the workaround (and fix) @josh-berry
