### ISSUE TITLE
Ability to sync somewhere, to allow opening of tab stash page on other browser / device

### ISSUE THREAD

**Issue by L1nkus** [josh-berry/tab-stash#383]
Basically, on on iPad (with no browser extensions possible), it would be cool if I could open a list of my tabs on pc’s firefox, and then pop / add some.

**Comment by josh-berry** [comment]
Tab Stash saves all your stash tabs in your bookmarks, so this is already possible. Make sure Firefox Sync is turned on, and go to the "Other Bookmarks" > "Tab Stash" folder on your iPad. Hope this helps!
