### ISSUE TITLE
How I can make it create backup automatically ?

### ISSUE THREAD

**Issue by izac3d** [josh-berry/tab-stash#386]
How I can make it create backup automatically in certain path ?

**Comment by josh-berry** [comment]
That is not something that Tab Stash can do, unfortunately. However, you're free to use other bookmarking extensions or Firefox's built-in bookmark backup feature to back up your stash. Hope this helps, let me know if you have any follow-up questions!

**Comment by izac3d** [comment]
I googled alot I can not find any. in Firefox forum they say no auto backup to specific folder only bookmark html in profile folder
