### ISSUE TITLE
Allow adding multiple tabs to existing stashes through either the context menu and with hotkeys.

### ISSUE THREAD

**Issue by YousufSSyed** [josh-berry/tab-stash#387]
### Problem Statement
Sometimes I have tabs for a related topic scattered in my window, and want to add a bunch of tabs to a stash incrementally. 

### Preferred Solution(s)
There should be a context menu option when you select multiple tabs, to add all those tabs to an existing stash. 

Another way to do so would be to set a hotkey in the preferences page, where if you press it, it shows a vertical list of all stashes, you can click on one to add the tabs to the stash, or you can navigate the list with up and down keys, and select the stash to save to with the enter key. There would also be a "new stash" option at the top of the page.

### Alternative Solution(s)
I can select multiple tabs to move to stash in the sidebar but that would take more time. I have lots of tabs to manage and want to do so more quickly.

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, thanks for reaching out! Your issue is already covered/duplicated by another issue, so please take a look at the original (and subscribe if you want updates):

* #30

**Comment by YousufSSyed** [comment]
One possible solution you could consider is to add HTML to the current page to show a menu. An example would be Simple Tab Groups. You click on the plugin then the gear icon > hotkeys > add hotkey > and set one for "move selected tabs to custom group". When you press it, it adds HTML to the current tab to select a group to move tabs to.
<img width="1123" alt="Screenshot 2023-08-25 at 10 09 15 AM" src="https://github.com/josh-berry/tab-stash/assets/42646062/c96822a6-7875-40b2-a2d1-a643c0c1048d">
