### ISSUE TITLE
Add an preference to choose a name when creating new stashes.

### ISSUE THREAD

**Issue by YousufSSyed** [josh-berry/tab-stash#388]
### Preferred Solution(s)
I want to have names for stashes up front rather than go to the sidebar to name it. There could be a preference to write a name for the stash when creating it. When you create a new stash, it would show a text box to write it in and save the stash with the name.

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
There is unfortunately not a way to show a pop-up text box like you're asking for, because Firefox doesn't give extensions a way to show UI elements outside of sidebars/tabs/extension popups (which I am already using for something else that would conflict with this). Sorry to be the bearer of bad news, here.

**Comment by YousufSSyed** [comment]
@josh-berry One possible solution you could consider is to add HTML to the current page to show a menu. An example would be [Simple Tab Groups](https://github.com/Drive4ik/simple-tab-groups). You click on the plugin then the gear icon > hotkeys > add hotkey > and set one for "move selected tabs to custom group". When you press it, it adds HTML to the current tab to select a group to move tabs to.
<img width="1123" alt="Screenshot 2023-08-25 at 10 09 15 AM" src="https://github.com/josh-berry/tab-stash/assets/42646062/c96822a6-7875-40b2-a2d1-a643c0c1048d">
