### ISSUE TITLE
Minimum version of Node not documented or encoded in metadata, causes syntax error on older versions

### ISSUE THREAD

**Issue by alphapapa** [josh-berry/tab-stash#396]
### System Details

- **OS Version:** Debian 11
- **Tab Stash Version:** Trying to build commit 9f3703a (current HEAD, v3.0)
- `npm --version` shows v12.22.12

### Describe the Bug

I ran `make rel` in the repo root, and the build proceeded until it got to this error:

```
make check
make[3]: Entering directory '/home/me/src/archive/tab-stash'
./node_modules/.bin/vue-tsc --noEmit
/home/me/src/archive/tab-stash/node_modules/typescript/lib/tsc.js:93
  for (let i = startIndex ?? 0; i < array.length; i++) {
                           ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at main (/home/me/src/archive/tab-stash/node_modules/vue-tsc/bin/vue-tsc.js:57:3)
    at Object.<anonymous> (/home/me/src/archive/tab-stash/node_modules/vue-tsc/bin/vue-tsc.js:67:3)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
make[3]: *** [Makefile:38: check-types] Error 1
make[3]: Leaving directory '/home/me/src/archive/tab-stash'
make[2]: *** [Makefile:134: build-rel] Error 2
make[2]: Leaving directory '/home/me/src/archive/tab-stash'
make[1]: *** [Makefile:61: rel-inner] Error 2
make[1]: Leaving directory '/home/me/src/archive/tab-stash'
make: *** [Makefile:55: rel] Error 2
```

I would wait for v3.0 to hit AMO, but their review process is so slow, and I'm very excited to try the new subgroups feature, so I decided to build it myself.  Unfortunately I'm hitting this problem, and I'm not an expert on Firefox extensions or Node, so I'm a bit lost.  The error would seem to suggest a language feature not present in the version of Node or TS that is being used, but I don't see a minimum version of Node or TS specified in the docs or metadata files, so I'm not sure how to verify that I'm using an appropriate version.

Thanks very much for your work on this extension.  After using Firefox since it was "Phoenix," and a number of other browsers, this is the first extension that's made it easy for me to keep the window and tab count low.  It accomplishes what no browser vendor has been able to deliver.  Please keep up the great work.

**Comment by alphapapa** [comment]
I installed a build of Node v18 with Guix, and that's solved this problem.  Sorry for the noise.

OTOH, it would be good to document the minimum version of Node, or encode it in the metadata so it's caught with a useful error before encountering the newer syntax.  :)  I'll leave this issue open for the sake of that suggestion.

Thanks again for your work.

**Comment by alphapapa** [comment]
By the way, after getting v3.0 installed and using it to organize my stashed tabs in subgroups, I am so pleased.  I've waited a long time for this feature, and it works great.  Thank you!

**Comment by josh-berry** [comment]
Thanks for letting me know you ran into trouble with the build, and sorry about that! I just pushed a commit that specifies the minimum versions of Node and npm, so this should now fail with a more intuitive error message.

And thanks very much for sharing your thoughts—I'm really happy to hear Tab Stash has been useful for you, and that 3.0 is working well! I haven't pushed it to AMO yet but I expect that to happen maybe as early as this weekend—it's been a long time coming, but it's just about as polished as I can make it. So you shouldn't have to run off of `master` for very long. I hope. :)
