### ISSUE TITLE
New Feature Request : Option to remove stashed tab when opening it by middle clicking.

### ISSUE THREAD

**Issue by Y0Mamma** [josh-berry/tab-stash#398]
### Problem Statement

Option to middle click a stashed tab that will open that tab in a new tab and remove the stashed tab from the list.

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, you can already do this in a single click using the yellow "Open tab and delete from group" icon to the right of the tab (when you're hovering over it).

Middle-click is already used for closing an open tab (in line with Firefox's behavior), so I'm afraid repurposing it won't be possible. Thanks for the request though, and I hope the above helps!

**Comment by Y0Mamma** [comment]
"Middle-click is already used for closing an open tab (in line with Firefox's behavior)"
As it stands now, if you middle click a stashed tab, it opens the tab in a new tab, at least that is what it does on my setup.
Also, on a regular link in FF, if you middle click it, it opens the tab in a new tab.

Yes, you can do the same thing as you described, but the button is so little it takes time to find and do and that is anoying.

**Comment by josh-berry** [comment]
> "Middle-click is already used for closing an open tab (in line with Firefox's behavior)" As it stands now, if you middle click a stashed tab, it opens the tab in a new tab, at least that is what it does on my setup. Also, on a regular link in FF, if you middle click it, it opens the tab in a new tab.

Yes—middle-click will toggle the tab. So if it's closed, the tab will open, and if it's already open, the tab will be closed.
