### ISSUE TITLE
Setting for "Tab and Memory Management" appears to do nothing.

### ISSUE THREAD

**Issue by spiralsam** [josh-berry/tab-stash#4]
Tab Stash v2.2
Firefox Quantum v65.0 64-bit

In the Extension options page there is "Tab and Memory Management (This Browser). I've tried the radio button for all three options. The only one that actually seems to work properly as its configured is the default: "Hide the tab and keep it loaded in the background".

The other two don't work as expected. For example, selecting "Close the tab immediately" and then stashing tabs will hide the tab and keep it loaded in the background, etc.

**Comment by josh-berry** [comment]
Yikes—thanks for bringing this to my attention. I was able to reproduce it here and will try to push a fix out soon.

In the meantime, if you find you're accumulating too many hidden tabs, you can Alt+Click (or Option+Click on Mac) on the "Close all open tabs" button (the one that looks like an "X" inside a box) to close all your hidden tabs, but leave your non-hidden tabs untouched.

**Comment by josh-berry** [comment]
The fix for this will be in the next Tab Stash release.
