### ISSUE TITLE
Basic theme support for the sidebar

### ISSUE THREAD

**Issue by Moustachey** [josh-berry/tab-stash#401]
### Problem Statement

The problem is more of a UI/UX improvement. Currently on my light theme the sidebar heading background is a murky brown/yellow which appears a bit poorly.

### Preferred Solution(s)

It would be great to support a basic list of theme presets or a colorpicker for both the Tab Stash sidebar heading area, the sidebar link colors and the sidebar body background.

### Alternative Solution(s)

Set a better suited background color for the sidebar header, e.g. the light grey shade that Firefox light theme uses.

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
![sidebar-header](https://github.com/josh-berry/tab-stash/assets/1203893/e026e775-3fac-4775-b70f-c9d4666f6d11)

Is this the header you're talking about? Unfortunately, this is controlled entirely by Firefox and the theme that you're using, not by Tab Stash.

**Comment by Moustachey** [comment]
Yes that is the header I'm talking about. It's odd that Firefox light theme displays that shade of grey in that usage. Is there no way to alter this value for Firefox's default Light theme?

**Comment by josh-berry** [comment]
Sadly there is not; not without messing around in Firefox itself. There might be other themes that color it differently, but TBH I haven't explored Firefox's themes much, so I'm afraid I don't have any that I can recommend. Wish I could help!
