### ISSUE TITLE
Tab Stash is showing blank page when opening stash list

### ISSUE THREAD

**Issue by ClementToche** [josh-berry/tab-stash#402]
### Crash Details

```text
OS : Windows 11
Browser : Firefox 117.0.1
Tab Stash version : 3.0
```

### Installed Extensions

- Bitwarden
- Dark Reader
- Floccus
- uBlock Origin

### Describe the Crash

I'm "almost" sure that the problem occurs since the plugin has been upgraded to version 3.0.

I'm no more able to access "stash-list" however the way I open it :
1. Clicking on the plugin icon (I change parameter to open stash-list instead of stashing open tabs when I click on it)
2. Opening on side bar
3. Opening manually in the main widow by providing URL (moz-extension://1bab84d8-4764-404a-86f1-14bbc003fe21/stash-list.html)

I open the stash list by providing direct URL (method 3 above), I have a blank page.
If I open the web developer tool, I have java-script errors (see error log attached).
[tab-stash_error.log](https://github.com/josh-berry/tab-stash/files/12642960/tab-stash_error.log)

I tried by closing / reopening Firefox and by deactivating all other plugins and nothing has permitted to get the plugin back again.

### Expected Behavior

Having the tab-stash list view fully operational with the list of stashed tabs displayed.

### Impact

I'm no more able to use tab-stash plugin since I can't access to the stashed tabs (beside the use of generic firefox bookmark menu)

**Comment by josh-berry** [comment]
Yikes, sorry to hear that! Thanks for sharing the crash log, that was super helpful. From what I can tell, Firefox is not reporting the order of the bookmarks in one of your folders correctly, and that's what's causing the crash.

You may want to try backing up and restoring your bookmarks using Firefox's bookmark manager. Once you restore, be sure to delete the OLD copy of your bookmarks (leaving only the copy that you restored).

Let me know if this helps! I'll look into making Tab Stash more resilient to this type of issue in the future.

**Comment by ClementToche** [comment]
Hi @josh-berry , thanks for your help and insight.
Since I have Floccus, I just removed all my bookmark and force a new synchronization.
All has been restored and tab-stash is now working properly again without losing my previous tab-stash category.
Thanks a lot, now I'm able to get tab-stash back again.

**Comment by josh-berry** [comment]
Got it, thanks for confirming, I'm glad to hear you were able to get things working again!

**Comment by gvlx** [comment]
confirmed error by removing extension and installing older 2.12.0.1 from [Firfox Add-ons Tab Stash version history](https://addons.mozilla.org/en-US/firefox/addon/tab-stash/versions/)

In the `about:debugging` page Firefox was complaining about `Warning processing page_action.theme_icons`

I still have to test the approach by @ClementToche

**Comment by gvlx** [comment]
This is the error the Firefox Debugging inspection now on the 3.0.

> Reading manifest: Warning processing page_action.theme_icons: An unexpected property was found in the WebExtension manifest.

Errors on consle:

> TypeError: newChildren[i] is undefined
[index.js:2274:11]
    setPosition moz-extension://f766e2e7-914a-40ed-a738-7a28235881bd/index.js:3451
    whenBookmarkCreated moz-extension://f766e2e7-914a-40ed-a738-7a28235881bd/index.js:3859
    whenBookmarkCreated moz-extension://f766e2e7-914a-40ed-a738-7a28235881bd/index.js:3862
    whenBookmarkCreated moz-extension://f766e2e7-914a-40ed-a738-7a28235881bd/index.js:3862
    whenBookmarkCreated moz-extension://f766e2e7-914a-40ed-a738-7a28235881bd/index.js:3862
    Model2 moz-extension://f766e2e7-914a-40ed-a738-7a28235881bd/index.js:3513
    logError moz-extension://f766e2e7-914a-40ed-a738-7a28235881bd/index.js:2274
    logErrorsFrom moz-extension://f766e2e7-914a-40ed-a738-7a28235881bd/index.js:2269

**Comment by gvlx** [comment]
Tested @ClementToche approach the following way:

1. suspend all synchronization (flocus, firefox, etc)
2. suspend synchronization extensions (flocus or others) and TabStash
3. open `bookmark manager`
4. save all bookmarks to file
5. remove "Tab Stash" folder
6. close firefox
7. open firefox
8. open `bookmark manager`
9. restore backup from file
10. enable TabStash --> now it is ok (it may ask the startup questions but will find all the bookmarks correctly)
11. you can now enable synchronization again (push first, in the case of flocus)

It does seem to be something strange if you sort too many things,
I'll have to try sorting and moving bookmarks with TS suspended to check if it is capable of re-reading the bookmarks on its own.

**Comment by josh-berry** [comment]
Since I haven't heard back, I'll go ahead and close this as a duplicate of #417, but do let me know if you're still seeing the issue on `master`. Thanks!
