### ISSUE TITLE
Enable GitHub Sponsor

### ISSUE THREAD

**Issue by azzamsa** [josh-berry/tab-stash#403]
### Question

Hi.

Tab-Stash is very helpful. 
Why don't you consider enabling GitHub sponsor?

Thanks a lot for Tab-Stash. 🏅

**Comment by josh-berry** [comment]
I'll look into it. :) Thanks for the note, I'm really glad to hear it's helpful!

**Comment by dec-mail** [comment]
Now that i know TS better, with the various 'hidden' functions (hint), it seems that i can use it as a good replacement for OneTab, which i had been thinking about reverse-engineering myself (and adding the several important basic functions that users have been waiting for years for with no support).

**Comment by josh-berry** [comment]
Alright, I've set up a sponsorship page on GitHub here: https://github.com/sponsors/josh-berry

There is absolutely no obligation, and Tab Stash will continue to be 100% free and open source. But if you do decide to leave me a tip, you have my thanks! 🙇
