### ISSUE TITLE
Feature request: Moving group of stashed links.

### ISSUE THREAD

**Issue by Dennismn** [josh-berry/tab-stash#405]
First of all, I want to say thank you for the most recent update. The new subgroup feature makes it great/almost perfect IMO. I would like to request the feature ability to be able to move stashed links into other groups/subgroups from the main window please. I think this will make it the 🐐 tab extension. Either by highlighting all the individual stashes and dragging them or via a menu option or something. I’m aware that you can do this if via Firefox’s bookmark organiser, but I think via Tab Stash will make it easier. I’ve included video to help illustrate. If possible, like if I wanted to move the links in the “Joggers” stash into the "Trousers" group _preferably_ just by dragging. But also without removing the ability to reorganise stash boxes. Thanks for all that you do. It’s much appreciated. 

https://github.com/josh-berry/tab-stash/assets/69481233/7ebfeb41-dddb-4982-8c94-f8f62168cb9b

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, thanks for the note and the video!

I thought pretty hard about how to make top-level groups and sub-groups work together—unfortunately, there are some problems that can happen if they are treated the same (for example, individual bookmarks getting lost if they're dragged up to the top level).

So the compromise I came up with is the "Convert to Child Group" menu option, which will turn a top-level group into a sub-group that you can then select and drag around just like you describe. 

<img width="326" alt="Screenshot 2023-09-28 at 18 16 52" src="https://github.com/josh-berry/tab-stash/assets/1203893/41bb9fbd-7be0-4895-acfd-5c8465d91dd0">

I'll keep thinking about how to make this a smoother experience, but in the meantime, I hope this helps!

**Comment by Dennismn** [comment]
Wow, I can't believe I didn't think to do that lol! This will deinitely suffice. Thanks!

**Comment by josh-berry** [comment]
Great, glad it helped!
