### ISSUE TITLE
Drag stashed tab into hidden group

### ISSUE THREAD

**Issue by alphapapa** [josh-berry/tab-stash#407]
### Problem Statement

While rearranging my stashed tabs, I start to drag one into a group, but that group is hidden (i.e. folded or collapsed), so I have to let go of the tab, unhide (i.e. unfold or expand) the group, and then drag it into the group.

### Preferred Solution(s)

It would be helpful if one or both of these were implemented:

- Tabs could be dropped onto folded groups to put the tab into the group.
- Groups would unhide/unfold/expand when an item being dragged is held over it.

I searched the tracker but couldn't find this issue mentioned; hopefully I didn't duplicate anything.

Thanks for your work on this excellent tool!

**Comment by josh-berry** [comment]
Hi Adam, nice to hear from you again! When you have tabs selected, you actually don't have to use drag-and-drop to move tabs into a group—you can click the blue "Stash" icon for the group to move selected tabs into that group.

That said, it's not possible today to drag-and-drop into a hidden group, but I'll definitely keep this in mind for the future—I can absolutely understand wanting to drag-and-drop into hidden groups.

Hope this helps in the meantime!

**Comment by alphapapa** [comment]
Thank you!

**Comment by dec-mail** [comment]
And i still do not under stand what Hidden tabs OR Groups are.
And if a Group is hidden, how can you see it?

**Comment by alphapapa** [comment]
> And i still do not under stand what Hidden tabs OR Groups are. And if a Group is hidden, how can you see it?

See my original comment:

> that group is hidden (i.e. folded or collapsed)

**Comment by josh-berry** [comment]
This will be available (along with some other improvements to drag-and-drop) in the next release!
