### ISSUE TITLE
Adding a button to create a new folder

### ISSUE THREAD

**Issue by mrnossiom** [josh-berry/tab-stash#409]
### Problem Statement

I often find myself factorizing my tabs in one folder, but then sometimes wants to split them again to better organize my stash. When splitting an existing folder, I need to create a new one and there are no obvious and simple solution.

### Preferred Solution

It would be maybe more practical to have a create new group button on the top menu bar, like a `+` button. This could also be applied to child groups, like a `+` button on group's menubar to quickly add a new child group.

### Alternative Solution

- Open the tab and stash it again to create a new folder
- Use the `Import...` functionality with this text: `## <Folder name>\n- [Dummy link](https://example.com)`
but both are workarounds and are not really made to create a new folder

### Additional Context

_Nothing here_

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, there is a `+` button in the "Open Tabs" / "Unstashed Tabs" section at the top that will create a new empty group.

![new group](https://github.com/josh-berry/tab-stash/assets/1203893/cf22bb52-cfa5-4ae7-994a-d0db9e606db1)

I know it's a bit hidden and I'm looking at ways of making it more clear, but I hope this helps in the meantime!

**Comment by mrnossiom** [comment]
Thanks you are right.
