### ISSUE TITLE
Sub-group icon colors

### ISSUE THREAD

**Issue by Bugrakca** [josh-berry/tab-stash#410]
### Problem Statement

It's hard to see what is a sub-group and what is not. The colored folder icons can solve this issue. This problem occurs to me when I drag the links around.

### Preferred Solution

I moved all my sub-groups to the top of the parent folder.  This makes it easier to see where I can put my links.

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Custom colors/custom properties are unfortunately not something that's supported by Firefox for bookmarks, so there is no way for Tab Stash to store information about what colors are used by what folders.

Sorry to be the bearer of bad news here, but I'll keep your point in mind about it being hard to tell folders apart from links. Thanks for letting me know!
