### ISSUE TITLE
"When the toolbar button is clicked": "Don't stash any tabs" is greyed out

### ISSUE THREAD

**Issue by devurandom** [josh-berry/tab-stash#411]
### Question

I look at the "Preferences" tab for "Tab Stash" on about:addons. Under "When the toolbar button is clicked" there is a drop down with three options: "Stash all (or selected) tabs", "Stash the active tab" and "Don't stash any tabs". I can select the first two, but the last one is greyed out.

How can I make "Tab Stash" not stash tabs when clicking the "Tab Stash" extension button?

### System Details

- **OS Version:** Fedora 38
- **Browser Version:** Firefox 118.0.2
- **Tab Stash Version:** 3.0

**Comment by josh-berry** [comment]
The "Don't stash any tabs" option is greyed out whenever the "don't show the stash" option is selected. You'll need to choose an option other than "don't show the stash" to enable "Don't stash any tabs".

Hope this helps!

**Comment by devurandom** [comment]
> The "Don't stash any tabs" option is greyed out whenever the "don't show the stash" option is selected. You'll need to choose an option other than "don't show the stash" to enable "Don't stash any tabs".

Thanks a lot! This helped a lot. Would be nice to have this information on the preference screen.

Or maybe you find a way to rearrange the options to avoid this entirely? Maybe: "when clicking the button: [only stash tabs, stash tabs and show, only show stashed tabs]"?

**Comment by josh-berry** [comment]
Glad to hear it! It does show up in the new-user / first-time setup screen, but if you had your settings configured before 3.0 was released, you probably wouldn't have seen this. I'll keep your point about the preferences page in mind for the future, though!
