### ISSUE TITLE
Stash all tabs to an existing group or subgroup

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [josh-berry/tab-stash#412]
There could be an option to stash tabs directly into a preferred group. Say it is shown as a list and we can click the item to stash directly into it. This is also similar to what  OneTab had (only that onetab is a mess compared to this).

**Comment by josh-berry** [comment]
Hi, you can already do this—simply use one of the blue "Stash" buttons that's present for each group to move all your tabs (or your selected) tabs directly into that group.

Hope this helps!
