### ISSUE TITLE
Tab Stash fails to start - bookmark DB errors

### ISSUE THREAD

**Issue by che-rusker** [josh-berry/tab-stash#417]
As the title says.
Not much more to add.

I see he addon active up right with the other addons. But right-click on a tab does not do anything.
No matter if the stash is configured to appear in the sidebar or in a new tab.

100% Dysfunctional.

None of the usual suspects is active here.

**Comment by josh-berry** [comment]
I use Tab Stash on a daily basis on Firefox 119 with no issues, and unfortunately there's not much to go on in your report—can you describe, step by step, exactly what you're trying to do and exactly what's not working? 

Also, can you please answer the questions that were in the original bug report form:

- OS and version
- Other installed extensions

Thanks!

**Comment by che-rusker** [comment]
I'll add some scrots.

- All addons - active or not
- right click on a tab - where Tab Stash *should* appear, but doesn't.
- The basic settings


![scrot_2023-10-29_213339](https://github.com/josh-berry/tab-stash/assets/67553563/34a0ddd4-c50e-46f4-a8c3-cff8fc2e0a75)
![scrot_2023-10-29_213132](https://github.com/josh-berry/tab-stash/assets/67553563/4ea4c38e-9afb-4f5d-9014-d84956499d19)
![scrot_2023-10-29_213054](https://github.com/josh-berry/tab-stash/assets/67553563/0f72e000-8f66-4918-ac87-93b93986e690)

This is w11.

**Comment by josh-berry** [comment]
Thanks! Can you check for error logs from the background page, as described here:

https://github.com/josh-berry/tab-stash/wiki/Collect-Error-Logs

This should hopefully shed some light on why the context menu is not appearing.

**Comment by che-rusker** [comment]
![scrot_2023-10-29_215117](https://github.com/josh-berry/tab-stash/assets/67553563/94bfa760-09a9-47fd-aba2-c27266fb6b3b)

Does this help you on?

Mic

**Comment by josh-berry** [comment]
It does, thanks. It's telling me Tab Stash is having trouble loading your bookmarks. My best guess is Firefox is reporting inconsistent information about which bookmarks are in which positions.

Did you start using any of the other bookmarks extensions (Auto-Sort or Bookmarks Organizer) recently? I've seen issues happen in the past where multiple extensions are trying to re-organize bookmarks at the same time, their updates conflict with each other, and it leaves your bookmark database in a bad state.

If you can avoid using extensions that _automatically_ make changes to your bookmarks, you can avoid this problem in the future. It's only when two extensions are trying to change things at once that you can run into problems.

My best suggestion would be to export your bookmarks from Firefox's built-in bookmark manager, re-import them, and then delete the old copy once you've verified the re-imported bookmarks look good.

<img width="282" alt="Screenshot 2023-10-29 at 14 10 18" src="https://github.com/josh-berry/tab-stash/assets/1203893/13ef12bf-3652-4a83-ade3-6a9240251e6c">

Then, once you've fixed up your bookmarks, restart your browser to get Tab Stash to restart, and hopefully everything should start working again.

Hope this helps, let me know how it goes!

**Comment by che-rusker** [comment]
Well, I do sort my bookmarks eventually. But not automatically.
Okay, I'll try the export/import thing. :)

I'll report back.

**Comment by che-rusker** [comment]
![scrot_2023-10-30_121027](https://github.com/josh-berry/tab-stash/assets/67553563/9583d8ce-33f4-4286-ba15-7c8bf5bf38b8)

Wohoo! 
Many thanks, Josh. That did the trick. 😊

I exported all bookmarks as json and as html, as I usually do on a regular basis.
AND I deleted them all in FF.
After re-import Tab Stash is working fine again!

I really like your addon, as it is extremely helpful when doing research or collecting recipes and stuff. I let the stashed items be presented in a tab AND make this tab sticky. This makes for an ideal workflow (for me).

Mic

**Comment by josh-berry** [comment]
Hi Mic, glad to hear things are working again! I'll keep this open and see if there's a way to make Tab Stash more resilient against this type of issue in the future, but I'm happy to hear the workaround worked for you!

**Comment by josh-berry** [comment]
Converting back into a bug since others are hitting this as well. Will look into doing a bugfix release for this.

# [🔗 This comment has a workaround to get Tab Stash working again 🔗 ](https://github.com/josh-berry/tab-stash/issues/417#issuecomment-1784227126)

For any new folks running into this, please see the linked comment above. (No need to leave a "Me Too" comment if this fixes it. But if the above doesn't work for you, it's probably a different issue, so please file a new bug, thanks!)

**Comment by josh-berry** [comment]
The above fix will at least prevent the crash from happening. However, bookmarks might show up in the "wrong" order and/or drag-and-drop might put things in the wrong places. There's unfortunately nothing to be done about this without a fix in Firefox itself. But this should at least keep Tab Stash usable if this happens in the future.

The fix will be included in the next release.
