### ISSUE TITLE
Add-on suddenly won't start

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [josh-berry/tab-stash#420]
The Tab Stash sidebar is just empty and the button for opening tabstash won't work. Any way to fix it? I tried reinstalling the addon and it doesn't work.

![image](https://github.com/josh-berry/tab-stash/assets/45887282/2adf8aad-0a9c-45e8-97fd-e6731510872f)

**Comment by josh-berry** [comment]
Good to know, I'll mark this as a duplicate, thanks!
