### ISSUE TITLE
youtube being annoying ( maybe ) 

### ISSUE THREAD

**Issue by w111ll123938** [josh-berry/tab-stash#422]
### Problem Statement
When I switch to my "Chill" tabs I open YouTube, I browse different videos for a bit, and then I stash everything that was open in said "Chill" tab away. And when I open it again, it comes up with the original YouTube tab that I started watching, when I intended for it to open the one I was just watching. As well as that, it stores both, so I need to delete the original one and then switch to the one I was watching.

### Preferred Solution(s)
an option, say a tick in a box next to the tab in the sidebar that allows me to update the tab in the stash as I'm using it I don't do coding, so I don't know if that would be difficult or just impossible

### Alternative Solution(s)
not to sure what to put here, I think the preferred was alright

### Additional Context
it is slightly annoying, and it may seem pointless, and it may already be a feature that I skipped over, if this is so, I am sorry.

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, sorry for the delay in getting back to you! Holidays got busy and I'm just catching up.

The way Tab Stash works is by associating tabs to their bookmarks via URL. So if you're watching a different video on YouTube, it will have a different URL, and Tab Stash will think it's a different tab. So when you re-stash to "Chill", Tab Stash is saving the "new" tabs and leaving the "old" ones in place so they don't get lost.

I think what you are asking for is the same as in #42, so I'll go ahead and mark this as a duplicate, but let me know if I missed something. Thanks!
