### ISSUE TITLE
Hidden tabs sometimes left open when bookmarks are removed from the stash

### ISSUE THREAD

**Issue by Cyb10101** [josh-berry/tab-stash#425]
### System Details

- **OS Version:** Ubuntu 22.04
- **Browser Version:** Firefox 120.0
- **Tab Stash Version:** 3.0 [check the Tab Stash entry in `about:addons`]

**Installed Browser Extensions:**

The only addon that would be possible is: Temporary containers
However, I use it extremely rarely and have never put a tab with it in the stash.

- https://addons.mozilla.org/de/firefox/addon/temporary-containers/

### Describe the Bug

I now have over 500 hidden tabs. Which in itself isn't surprising.

What surprises me is that there are enough old tabs that I thought should actually be gone. The example below is a tab from March 2023.

One guess is that if I move the bookmarks from the bookmarks folder "Tab Stash" to another area, the hidden tabs will no longer be closed?

The bookmark is neither in "Tab Stash" nor in "Tab Stash deleted", but a bookmark still exists in /Toolbar/Development/Weblink.

### Steps to Reproduce

1. Stash a tab
2. Move tab from /Toolbar/Tab Stash/Folder/Weblink /Toolbar/Development/Folder/Weblink
3. Tab should exists after months

### Expected Behavior

Shouldn't old tabs be removed?
Should the hidden tabs be closed if they are dragged from the Stashed folder or no longer exist?

### Additional Details

Extract tabs:

```bash
# Extract json
sudo apt install lz4json jq
cp ~/.mozilla/firefox/profileId/sessionstore-backups/previous.jsonlz4 ./
lz4jsoncat previous.jsonlz4 > previous.json

# Read json
jq '[.windows[].tabs[] | select(.hidden == true)]' previous.json | less
jq '[.windows[].tabs[] | select(.hidden == true)]' previous.json | vim -c 'syntax on' -c 'set syntax=json' -c 'set wrap!' -
```

Shrinked tab:

```json
{
    "entries": [{
        "url": "https://example.com/",
        "title": "Dashboard",
        "cacheKey": 0,
        "ID": 26245742,
        "docIdentifier": 3953,
        "persist": true
    }, {
        "url": "https://example.com/",
        "title": "Docs",
        "cacheKey": 0,
        "ID": 2925,
        "docIdentifier": 4039,
        "persist": true
    
    }],
    "lastAccessed": 1679358932341,
    "lastAccessed_converted": "Tue Mar 21 2023 00:35:32 GMT+0000",
    "hidden": true,
    "searchMode": null,
    "userContextId": 0,
    "attributes": {},
    "extData": {
        "hiddenBy": "tab-stash@condordes.net"
    },
    "index": 1,
    "scroll": {
        "scroll": "0,3113"
    },
    "userTypedValue": "",
    "userTypedClear": 0
}
```

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, sorry for the long delay in getting back to you on this—the holidays happened and somehow this must have fallen through the cracks.

Tab Stash is indeed supposed to close hidden tabs whenever they are removed from the stash by any means (even moving bookmarks/folders around manually). I've played around with this a little bit and it seems like the removal occasionally does not happen, though it's not clear to me just yet why.

I'll look into this further, thanks for reporting it!

**Comment by josh-berry** [comment]
This will be fixed in the next release.
