### ISSUE TITLE
Add the possibility of list 

### ISSUE THREAD

**Issue by akasico1** [josh-berry/tab-stash#428]
### Suggestion

 

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Afraid I have no idea what you mean. Can you please edit the description to explain further?
