### ISSUE TITLE
I have many save list and I would like to have a quick overview or index

### ISSUE THREAD

**Issue by akasico1** [josh-berry/tab-stash#429]
### Problem Statement
I have many save list and I would like to have a quick overview or index
 

### Preferred Solution(s)
 Create an automatic Index of the saved list 
 
 

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
I don't know what you mean by an "index". Can you explain further?
