### ISSUE TITLE
Add the possibility of postit notes

### ISSUE THREAD

**Issue by akasico1** [josh-berry/tab-stash#430]
### Problem Statement
 Sometimes I want to write notes about the web pages

### Preferred Solution(s)
add the possibility to have notes sync by Firefox in tab stash 

 
 

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, thanks for reaching out! Your issue is already covered/duplicated by another issue, so please take a look at the original (and subscribe if you want updates):

* #209
