### ISSUE TITLE
Create shortcuts

### ISSUE THREAD

**Issue by akasico1** [josh-berry/tab-stash#433]
### Problem Statement
To get quickly access to tab stash in a sidebar I have to press  (ctrl+H) so I have the history and later I change to tab stash side view
 
### Preferred Solution(s)
Create shortcuts ex f2
 

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Tab Stash already has keyboard shortcuts for opening the sidebar. You can see what shortcuts are assigned (and change them to use different keys if you prefer) following the instructions here:

https://github.com/josh-berry/tab-stash/wiki/Changing-Keyboard-Shortcuts

Hope this helps, feel free to leave a comment here if you have any more questions on this!
