### ISSUE TITLE
Tab stash as start page

### ISSUE THREAD

**Issue by akasico1** [josh-berry/tab-stash#434]
### Problem Statement
 I can Firefox add a custum url as a new page or home pages (doesn t work for the address in tab stash)

### Preferred Solution(s)
Add a function with this possibility 
 

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, thanks for reaching out! Your issue is already covered/duplicated by another issue, so please take a look at the original (and subscribe if you want updates):

* #93
