### ISSUE TITLE
Undo funtion 

### ISSUE THREAD

**Issue by akasico1** [josh-berry/tab-stash#435]
### Problem Statement
 Also another thing can be good to have the option of pin saved group or not deleted save group when this group because empty. Sometimes we have to deleted some bookmark and next week to added again

### Preferred Solution(s)
 Add the possibility to have empty groups
Add the possibility of undo
 
 

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
If you change the name of your group, the group will be preserved even if it's empty. You can also create new, completely empty groups using the "+" button that's to the right of "Unstashed Tabs" (or "Open Tabs").

Also, deleted items are saved for 180 days (by default) on the computer they were deleted on. So if you open the Tab Stash menu (next to the search bar in the Tab Stash UI) and choose "Deleted Items..." you should be able to find anything you deleted by mistake.

Hope this helps!
