### ISSUE TITLE
Feature to discard duplicate tabs

### ISSUE THREAD

**Issue by BeliefSuffering** [josh-berry/tab-stash#437]
### Problem Statement

Duplicate tabs are annoying; making a miss click when opening links which are displayed next to each other and failing to notice the duplicate can lead to tabs which I otherwise would have liked to save to be missed

### Preferred Solution(s)

The 'Silently reject duplicates' feature in OneTab is what I would like to be added as an option in Tab Stash. It essentially discards duplicate tabs, allowing only one of each to be saved. Unless there already is something similar which I potentially missed, I would like the same feature to be added to Tab Stash, perhaps as an option for Tab Stash as a whole or for individual groups

### Alternative Solution(s)

Alternatively, indicate duplicates immediately after they are saved to a stash and make removal of the excess tab(s) possible

### Additional Context

None

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, thanks for reaching out! This is already covered/duplicated by another issue, so please take a look at the original (and subscribe if you want updates):

* #334 

I think this is pretty similar to what you're proposing above, though I'm not totally sure I understand what you mean by:

> making a miss click when opening links which are displayed next to each other and failing to notice the duplicate can lead to tabs which I otherwise would have liked to save to be missed

I would think you would NOT want these tabs to be saved, no?

I'll mark this as a duplicate, but if I've misunderstood, please let me know!
