### ISSUE TITLE
Can't see my stashed links anymore! 

### ISSUE THREAD

**Issue by atakee72** [josh-berry/tab-stash#444]
A turned my laptop as always today, and the Firefox browser, but my stashed tabs are not there anymore, as if I installed the extension anew, it is empty, only in the bookmarks bar is the TabStash folder is there, that's really weird. I tried twice to import the links I had backed up a few days ago, but it seems to import them, however it gives an error after a while, saying some of the links cannot be imported, I click on OK, then all the imported ones disappear! What the ...!?!
Please help me out, I'd appreciate 

All the best

### System Details

- **OS Version:** Windows 10
- **Browser Version:** Firefox
- **Tab Stash Version:** 

**Installed Browser Extensions:** a lot

**Comment by josh-berry** [comment]
Sorry to hear that! Please give the steps outlined in the wiki a try and let me know if that helps: https://github.com/josh-berry/tab-stash/wiki/Problems-Locating-the-Tab-Stash-Bookmark-Folder

**Comment by atakee72** [comment]
Thank you for your reply.
I have uninstalled/installed the plugin again.
Then imported the links in parts, it works now.
BUT I still can't figure out why they disappeared like that. Scary! 
By chance, I had a backup.

**Comment by josh-berry** [comment]
Without more details it's hard to say—usually when this happens it's because a Tab Stash folder gets duplicated in your bookmarks somehow (and not because anything is actually lost). Regardless, I'm glad you were able to recover!

**Comment by atakee72** [comment]
Thank you for your attention! 
Advice for everyone: make regular backups!
