### ISSUE TITLE
Prevent stashed tabs to load when closing the last open tab

### ISSUE THREAD

**Issue by CarterSnich** [josh-berry/tab-stash#452]
### Question

When I close the last tab on the browser, it opens a stashed tab instead of just showing the Home page (which is how my Firefox is configured). How to prevent this?

![output](https://github.com/josh-berry/tab-stash/assets/52433531/d4f5814f-c91a-49f1-b149-ed938d8560e0)
As you can see, instead of showing the Firefox Home page after closing the last tab, it loads a different URL, which was a stashed tab.

### System Details

- **OS Version:** EndeavourOS
- **Browser Version:** Firefox 122.0.1
- **Tab Stash Version:** 3.0

**Comment by josh-berry** [comment]
Unfortunately this is just something Firefox does that's outside of Tab Stash's control; see #311 for more details. Sorry I can't be of more help!
