### ISSUE TITLE
Tab stash folder deleted!!!

### ISSUE THREAD

**Issue by joedeip** [josh-berry/tab-stash#454]
### Question

Hello, I'm panicking.  I kept my tab stash folder in my toolbar menu and my admin mistakenly deleted it.  It was years of tab stash links!!  I backup my PC regularly, what  is the name of the tab stash folder to search for, and where should I restore it to?  OR is there a utility that Tab Stash has to recover the stashed tabs?

### System Details

Tab Stash 3.0

- **OS Version:** Windows 10 22h2
- **Browser Version:** 124.0
- **Tab Stash Version:** 3.0

**Comment by joedeip** [comment]
joed@entisp.com

**Comment by josh-berry** [comment]
Fortunately, Firefox keeps automatic backups of your bookmarks—here's how to restore: https://support.mozilla.org/en-US/kb/restore-bookmarks-from-backup-or-move-them#w_restoring-from-backups

You may want to restart your browser after restoring, just to make sure Tab Stash sees the restored folder. (This probably isn't needed but I'd suggest it anyway just to be safe.)

Let me know if this works for you!

**Comment by josh-berry** [comment]
Thanks, glad to hear it!
