### ISSUE TITLE
Delete tab on click, like onetab.

### ISSUE THREAD

**Issue by AylaMeo** [josh-berry/tab-stash#456]
### Problem Statement

I'm switching from onetab and so far I'm really in love with tab stash already, it honestly feels like a straight up improvement, the one issue I'm having is you can configure onetab to delete a tab when it's opened and whilst tab stash has the feature, it isn't the default on click behavior like onetab can have.

### Preferred Solution(s)

Just a simple setting to invert the behavior so when you click on a tab it deletes it from the stash.

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, thanks, I’m really happy to hear you’re finding Tab Stash to be an improvement! This is already covered/duplicated by another issue, so please take a look at the original (and subscribe if you want updates):

* #135
