### ISSUE TITLE
Hoe to open multiple windows before filing with tabs

### ISSUE THREAD

**Issue by jimbir** [josh-berry/tab-stash#458]
### System Details

- **OS Version:** [e.g. Windows 10, or Ubuntu 18.04]
- **Browser Version:** [e.g. Firefox 60.0.2]
- **Tab Stash Version:** [check the Tab Stash entry in `about:addons`]

**Comment by josh-berry** [comment]
Sorry, I'm not sure I understand what you're asking here, can you explain a bit more about what you're trying to do and maybe give me some context on why? Thanks!

**Comment by jimbir** [comment]
Thanks for the quick response!
I have 4 windows open with multiple tabs open in them. Tab stash has them neatly stored them in a side bar. 4 groups. 1 for each window with the tabs in them. When I have to restart my computer, I have to manually open 4 windows in Firefox. I can then  refill each window using the command " open all tabs in this group" in the Tab stash side bar. I'd like to be able to open the 4 windows by only having to hit 1 or 2 or 3 keys.If this doesn't help, get back to me.


    On Saturday, April 6, 2024 at 01:29:28 PM EDT, Josh Berry ***@***.***> wrote:  
 
 


Sorry, I'm not sure I understand what you're asking here, can you explain a bit more about what you're trying to do and maybe give me some context on why? Thanks!

**Comment by josh-berry** [comment]
Got it, thanks for clarifying! Unfortunately, there's not currently a way to do this in Tab Stash, but if you are mainly concerned with keeping your open windows and tabs across browser restarts, Firefox itself can help with this.

In your Firefox settings, I would suggest turning on "Open previous windows and tabs":

<img width="643" alt="Screenshot 2024-04-07 at 08 02 46" src="https://github.com/josh-berry/tab-stash/assets/1203893/2d830bd6-fb63-4c34-8a55-dba611bc3f2c">

I hope this helps!

**Comment by jimbir** [comment]
Thanks tor the reply and the tip. I just enabled it in Firefox settings.


    On Sunday, April 7, 2024 at 11:04:43 AM EDT, Josh Berry ***@***.***> wrote:  
 
 


Got it, thanks for clarifying! Unfortunately, there's not currently a way to do this in Tab Stash, but if you are mainly concerned with keeping your open windows and tabs across browser restarts, Firefox itself can help with this.

In your Firefox settings, I would suggest turning on "Open previous windows and tabs":
Screenshot.2024-04-07.at.08.02.46.png (view on web)
I hope this helps!

**Comment by josh-berry** [comment]
Great, hope it helps! I'll close this out but let me know if you have any follow-up questions!

**Comment by jimbir** [comment]
Wilco - out...

    On Sunday, April 7, 2024 at 02:43:28 PM EDT, Josh Berry ***@***.***> wrote:  
 
 


Great, hope it helps! I'll close this out but let me know if you have any follow-up questions!
