### ISSUE TITLE
Import Onetab Data

### ISSUE THREAD

**Issue by dec-mail** [josh-berry/tab-stash#460]
### Problem Statement
Although I have had TS around for a while, i have only started actually using it in past few days (see separate Issues/Questions/Features) after the wonderful but flawed Onetab crashed and burned. I gave up trying to recover the 6,000 saved Tabs. :-(

### Preferred Solution(s)
Can we import Onetab data?
There is 'huge' interest in this as there is a lot of Comments from Onetab users about lost Tab data.

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Yes, it's possible to import data from OneTab. From the main Tab Stash menu, choose "Import..." and then paste in the exported list of tabs from OneTab.

(Note: if you are using the popup view of Tab Stash, you will have to open Tab Stash in a tab to see the main menu.)

Hope this helps, let me know if you have trouble finding it!

**Comment by dec-mail** [comment]
woo hoo. 
now i have to find some copy of tabs if i can
PS where is this in any documentation, espec as Onetab so used.

**Comment by josh-berry** [comment]
Glad to hear it! I unfortunately don't have much in the way of documentation, since in my experience, documentation is rarely read by users, and I'd rather spend the time on making thing usable without documentation. There is a tips and tricks page, though—I'll see if I can add something there: https://josh-berry.github.io/tab-stash/tips.html
