### ISSUE TITLE
Does anyone know how to locate Onetab data in FF Profile data for Importing?

### ISSUE THREAD

**Issue by dec-mail** [josh-berry/tab-stash#462]
### Question

Does anyone know how to locate Onetab data in FF Profile data?

(so that i can try to import)

### System Details

Win 10 
FF latest

**Comment by josh-berry** [comment]
The folks to ask would be the OneTab devs—this isn't a Tab Stash issue I can help with, unfortunately.

I can at least tell you it's likely somewhere in Firefox's profile directory—here's how to locate it: https://support.mozilla.org/en-US/kb/profiles-where-firefox-stores-user-data

**Comment by dec-mail** [comment]
Yeah, right. Onetabs Support has, as long as i have used it (years) been non-existent.
People only used it any way because it was so useful - if also so dysfunctional in many ways, and that never ever got fixed, which was so very frustrating for users because just a few fairly simple fairly obvious tweaks would have made it a fantastic browser app
