### ISSUE TITLE
Autoclose stash popup after clicking a tab.

### ISSUE THREAD

**Issue by runamonk** [josh-berry/tab-stash#465]
### Problem Statement

After clicking a tab in the popup stash window, the stash window popup stays on the screen.

### Preferred Solution(s)

if the stash clicked is a single tab and it's not directed to a background tab,  close the tab stash popup window.

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Unfortunately, this isn't possible to do for technical reasons—Firefox doesn't offer a way for extensions to directly control when the popup is shown or hidden. Sorry to be the bearer of bad news here.
