### ISSUE TITLE
TabStash Fixes: Sort Stashed Tabs Within Groups

### ISSUE THREAD

**Issue by dec-mail** [josh-berry/tab-stash#467]
### Problem Statement

Can't sort Stashed Tabs

### Preferred Solution(s)

Sort Stashed Tabs _within_ Groups by -
- URL
- Page Title
- Date

OR simply manually dropping & dragging individual Tabs.

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, thanks for reaching out! Your issue is already covered/duplicated by another issue, so please take a look at the original (and subscribe if you want updates):

* #194

**Comment by dec-mail** [comment]
josh
what i suggested is NOT covered by previous. please add to that fix

regards

don
