### ISSUE TITLE
TabStash Fix: Sort/Move Stash Groups

### ISSUE THREAD

**Issue by dec-mail** [josh-berry/tab-stash#468]
### Problem Statement

Can't Move or Sort Stashed Tab Groups

### Preferred Solution(s)

Drag & Drop Groups manually

SAVE Group order

(i assume that NEW Stashed Group are added to top of existing Stashed Groups)

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, you can drag and drop groups manually to move them around. Just drag them by their titles.

Hope this helps, let me know if you're still having trouble with this!

**Comment by dec-mail** [comment]
Hi josh
Good to know; but why isn't that indicated in some way???
(similarly the Rename function is not listed and i only found out about that by accident!!)

update: manually moving groups works very well

**Comment by josh-berry** [comment]
It's mentioned on the add-on page itself:

> **Features**
>
> - ...
> - Drag and drop items to re-organize them (multi-select supported)
> - ...
>
> <cite>— https://addons.mozilla.org/en-US/firefox/addon/tab-stash/</cite>

You can also see in the screenshots that groups can have custom names, so I'm not sure how to make this more obvious than it already is? Open to suggestions though!

**Comment by dec-mail** [comment]
Hi there Josh

First let me say that i find TabStash a very useful replacement to the unsupported and somewhat dysfunctional One Tab that was.

Now that i am somewhat more familiar with it, i have virtually no enhancements or fixes.

So eg moving single Tabs works very well, and moving single Groups works fine, if a little clunky.

But, the single biggest  issue is, despite the fact that you say, if i understand it, that i should be able to select and move (or delete) 'blocks' (multipole of tabs within TabSlash, i have been unable to do so despite trying multiple times in multiple ways.

So i am trying to do the following ...
Select and move _adjacent_ multiple tabs within an existing TabSlash Group to a new (or different) TabSlash Group.
I just cannot select multiple Tabs using either Ctrl-Enter or Shift-Enter.
So what's the (non-intuitive) trick? 
Or alternatively, why do the STD Ctrl and Shift actions not work?

Other small fixes/enhancements are (i can Post them separately if you like) -

1. Why does the std F2 not work for renaming?

2. Why does opening a single Tab with a Group ONLY have 'Open & DELETE'???? 
That is absolutely dysfunctional.

3. How to PIN a Group to top of TabSlash?

4. Why not always display the 'action' icons for each group/tab, instead of the dysfunctional mouse roll-over?

5. It would be very useful to have a Display/Admin option to display all TabSlash Tabs and Groups (expanded)  in a GRID to make it much easier to manage and arrange Tabs and groups.

And that is all that i can think of/remember that needs fixing in TabSlash. :-) The multiple Tab Select issue is the most important/urgent.

Believe me, that is an 'Excellent' Report Card. :-)

kind regards

Don

**Comment by josh-berry** [comment]
> Hi there Josh
> 
> First let me say that i find TabStash a very useful replacement to the unsupported and somewhat dysfunctional One Tab that was.

Thanks, I'm glad to hear you're finding it useful!
 
> So i am trying to do the following ... Select and move _adjacent_ multiple tabs within an existing TabStash Group to a new (or different) TabStash Group. I just cannot select multiple Tabs using either Ctrl-Enter or Shift-Enter. So what's the (non-intuitive) trick? Or alternatively, why do the STD Ctrl and Shift actions not work?

You should be able to click a tab's icon and then shift-click another tab's icon to select a whole range of tabs, so long as all tabs are within the same group (just like normal Mac/Windows multi-select).

> 1. Why does the std F2 not work for renaming?

This is a Windows-specific shortcut that isn't implemented in Tab Stash right now. (Better keyboard support is something I want to get to, just haven't had time.)

> 2. Why does opening a single Tab with a Group ONLY have 'Open & DELETE'????
>    That is absolutely dysfunctional.

You can simply click the tab title itself to open the tab. No need to both open AND delete.

> 3. How to PIN a Group to top of TabStash?

There's no way to do this currently—there's a feature request open here:

* #124

> 4. Why not always display the 'action' icons for each group/tab, instead of the dysfunctional mouse roll-over?

Because it would be extremely cluttered, visually, and make it a lot harder to find the tab/group you're looking for (especially since the action buttons would hide more of the group title).

> 5. It would be very useful to have a Display/Admin option to display all TabStash Tabs and Groups (expanded)  in a GRID to make it much easier to manage and arrange Tabs and groups.

Right-click on the Tab Stash icon in your toolbar, and choose "Show Stashed Tabs in a Tab". :)

You can also configure Tab Stash to open this view by default in the Tab Stash options.

**Comment by dec-mail** [comment]
1st let me say thank you and congratulate you on your excellent, timely, helpful, and friendly support. did i say excellent? ;-)

not that i agree at all with all yr UI design by any means ;-)

(btw can you make this text box bigger in the support app?)

"You should be able to click a tab's icon and then shift-click another tab's icon to select a whole range of tabs, so long as all tabs are within the same group (just like normal Mac/Windows multi-select)."

this is what i have tried repeatedly - doesn't work (for me) Win 10 FF

will check the Grid thing out and see if that is what i mean.

PS need any help? not that i am good for much. ;-)

cheers

don

**Comment by josh-berry** [comment]
> "You should be able to click a tab's icon and then shift-click another tab's icon to select a whole range of tabs, so long as all tabs are within the same group (just like normal Mac/Windows multi-select)."
>
> this is what i have tried repeatedly - doesn't work (for me) Win 10 FF

Hm, would it be possible to send a screen recording of what happens when you do this? Very strange that it's not working for you.

> 1st let me say thank you and congratulate you on your excellent, timely, helpful, and friendly support. did i say excellent? ;-)

And thanks—I do my best. :)
