### ISSUE TITLE
New tab default page + is this still maintened? 

### ISSUE THREAD

**Issue by ironhak** [josh-berry/tab-stash#470]
Hello, I see that on mozilla site this extension last update was +6months ago, is this still maintained? 

If so, I would liek to ask if the feature of having tab stash open every time I open a new tab (and with the link bar empty so I can rapidly search) is coming or not, many other similar extensions have this. 

Thank's :)

**Comment by josh-berry** [comment]
> Hello, I see that on mozilla site this extension last update was +6months ago, is this still maintained?

Yes. However, my pace of development has slowed because Real Life has gotten in the way for the time being. If a serious bug shows up, for example, it will be fixed in a timely fashion.

> If so, I would liek to ask if the feature of having tab stash open every time I open a new tab (and with the link bar empty so I can rapidly search) is coming or not, many other similar extensions have this.

This has actually already been asked for, so I'll close this as a duplicate, but see:
* #93
