### ISSUE TITLE
Automatically stash unstashed tabs on FF close/tab open/change

### ISSUE THREAD

**Issue by vguttmann** [josh-berry/tab-stash#472]
### Problem Statement
My Firefox occasionally crashes and loses all tabs, and they don't appear as recently closed tabs either

### Preferred Solution(s)
A way to automatically save tabs as bookmarks, even if they're not currently in a stash

### Alternative Solution(s)
Hoping that all the FF bugs get fixed. Not realistic

### Additional Context

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, thanks for reaching out! Your issue is already covered/duplicated by another issue, so please take a look at the original (and subscribe if you want updates):

* #392
