### ISSUE TITLE
Support for tree-style tabs

### ISSUE THREAD

**Issue by vguttmann** [josh-berry/tab-stash#473]
### Problem Statement
When I do research, I use Tree-style tabs to keep my tabs organized, however, there's no easy way to then save that whole tree as a stash, let alone keep its hierarchy

### Preferred Solution(s)
A way to save a root tab and its children (from TST) as a stash, preferrably retaining the hierarchy they were in.

### Alternative Solution(s)
Duplicating the stash function in TST, however, I feel like this would be a lot of redundant work

### Additional Context

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, thanks for reaching out! Your issue is already covered/duplicated by another issue, so please take a look at the original (and subscribe if you want updates):

* #94
