### ISSUE TITLE
[Feature] Sorting of stashed tabs

### ISSUE THREAD

**Issue by mdziczkowski** [josh-berry/tab-stash#474]
### Problem Statement

There is need of sorting of the stashed tabs in created categories.

Doing above manually (aspecially when there is a big amount of stashed tabs) is very tiresome and annoying.

### Preferred Solution(s)

It would be great if there would be a functionality to automate it and sort them with given by user criteria (mainly: by name)

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, thanks for reaching out! Your issue is already covered/duplicated by another issue, so please take a look at the original (and subscribe if you want updates):

* #194
