### ISSUE TITLE
Tab Display

### ISSUE THREAD

**Issue by dec-mail** [josh-berry/tab-stash#477]
Display Tab URL instead of Page Title

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Unfortunately I think most people would find this confusing; in my experience, titles are more descriptive and easier to distinguish, because the domain name takes up most of the space at the beginning of the URL. But thank you for the suggestion!

**Comment by dec-mail** [comment]
noted. ty.
