### ISSUE TITLE
Tab Retitle

### ISSUE THREAD

**Issue by dec-mail** [josh-berry/tab-stash#478]
Retitle Tab Title (instead of Page Title)

(see Add-on 'Tab ReTitle' by Lazyuki for excellent example)

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
You can edit titles in the stash today using the little pencil icon next to the pencil icon that appears on the right when you hover over the tab.

<img width="453" alt="Screenshot 2024-05-09 at 10 14 36" src="https://github.com/josh-berry/tab-stash/assets/1203893/bbc83f4f-7050-4789-b7b3-363c19507d77">

Hope this helps!

**Comment by josh-berry** [comment]
Gonna close this one but let me know if you still haven't figured out how to edit titles!
