### ISSUE TITLE
Click again to close sidebar

### ISSUE THREAD

**Issue by chung1905** [josh-berry/tab-stash#479]
This is my current config
![image](https://github.com/josh-berry/tab-stash/assets/16518833/31849aca-69c6-4bf1-a21a-bb67e8afc0a5)

For now, it will only open the sidebar on click, I would like to be able to close the sidebar if the current sidebar already is "Tab Stash" by clicking Tab Stash menu icon again

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Thanks for the suggestion, I'll keep this in mind!

**Comment by chung1905** [comment]
duplicated: https://github.com/josh-berry/tab-stash/issues/400
