### ISSUE TITLE
Emacs dev setup

### ISSUE THREAD

**Issue by clemera** [josh-berry/tab-stash#48]
I noticed that you mention Emacs in the docs. I'm a long time Emacs user but haven't used it for Javascript programming so far. I want to teach myself some Javascript by going through the code of some great exensions (like tab-stash). Now I wonder if you could share your Emacs setup for this project? 

I'm currently experimenting with [tide](https://github.com/ananthakumaran/tide) on Emacs 26.3. Just curious if you can share some tips for JS development with Emacs.

**Comment by josh-berry** [comment]
So I don't have too much that's javascript (or typescript) specific, but here are the ELPA packages I use that might be relevant to you:

* ag -- quick/friendly recursive grep (requires `ag` tool in your PATH)
* auto-complete
* fuzzy -- fuzzy matching for auto-complete
* flycheck -- point out syntax and other issues on-the-fly
* ido -- nicer/faster way to select from a list of options (e.g. for quickly choosing a file to open)
* ido-grid-mode -- nicer presentation than the default ido interface
* magit -- awesome frontend for Git
* treemacs -- nice directory-tree view in a sidebar
* treemacs-magit
* smex -- basically ido for M-x 

Specifically for Tab Stash, I have:

* typescript-mode (which IIRC also edits javascript, tide probably installs this one already)
* vue-mode (for editing .vue components, which embed both HTML and JS/TS)

Another thing you might want to experiment with is `lsp`, `lsp-mode` and `lsp-ui`; I haven't tried it myself with TypeScript, but supposedly Microsoft provides a language server for TypeScript, and lsp-mode which enables on-the-fly compilation/error checking, intelligent auto-completion, inline documentation, etc. using the actual TypeScript compiler (i.e. the "language server").

The cool thing about LSP is it's language-independent; it doesn't just work for JS/TS. For instance, it works very nicely with Rust (which is where I started using it), and there are language servers that have been developed for many other languages and work with lsp-mode and friends.

I haven't experimented with Tide, myself, but it sounds pretty intriguing and like it might do something similar to what LSP does in terms of completion/documentation.

Anyway, hope this helps and good luck!

**Comment by clemera** [comment]
Many thanks for your recommendations. I have worked with LSP in the past (and EGLOT too) and I think those are the future for supporting IDE features for any language in Emacs. LSP tries to deliver a great out of the box experience but I don't like their UI preferences. I will spend some time configuring it to my taste at some point but for Javascript I will go with tide for now which uses the same language server as VsCode as far as I know. 

I will install vue-mode now and the next few weeks I will learn some Vue and try to understand how your extensions works. Thanks!
