### ISSUE TITLE
Glaring Missing Function ... Open in New Window/Private Window

### ISSUE THREAD

**Issue by dec-mail** [josh-berry/tab-stash#481]
Hey Josh

one thing that that is constantly irritating me and wasting my time is that there is no option to open Tab Group (or Tab?) in a new Window.

I would have thought that would have been an obvious need?

So i am constantly having to move groups of tabs from one window into a new empty window.

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
It's been asked for already:

- #107
