### ISSUE TITLE
Option for bookmarks to be sorted by URL

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [josh-berry/tab-stash#483]
I currently see how tabs are sorted in the way they were put in the folder, but it would be a nice feature to have some dropdown option to sort them in the same way we can sort columns in the bookmark editor.

**Comment by josh-berry** [comment]
Hi, thanks for reaching out! Your issue is already covered/duplicated by another issue, so please take a look at the original (and subscribe if you want updates):

* #194
