### ISSUE TITLE
Stash this tab but do not close the current tab

### ISSUE THREAD

**Issue by jitendra002** [josh-berry/tab-stash#485]
### Question

Thank you for creating this extension. I am wondering if there is configuration where if I press "Stash this tab" button, then save the current tab into specific group and do not close the current tab.

Currently when I press "stash the tab" button then first it closes the current window and stash into open stashes group.

**Comment by josh-berry** [comment]
Hey Jitendra! It's been a minute since we last spoke, hope you're doing well. :)

There is not right now, but I think these two issues might cover (or be similar to) what you're asking for:

- #152 
- #144
