### ISSUE TITLE
Sm Fix: Tabstash Folder Date Name

### ISSUE THREAD

**Issue by dec-mail** [josh-berry/tab-stash#487]
### Problem Statement

I have started naming my TabStash Folders more from the generic default date name; but i would like to keep that date in the name (as a suffix or prefix) so i can tell when it was created, because i might have many tab folders (groups) with duplicate tabs/links and that would help me organise and know which are best to delete when i dedup (FF Extension simple easy 'Bookmark Dups' highly recommended); but atm the default date name is not included/editable.
 

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, thanks for reaching out! Your issue is already covered/duplicated by another issue, so please take a look at the original (and subscribe if you want updates):

* #463
