### ISSUE TITLE
Some stashed tabs open on browser start

### ISSUE THREAD

**Issue by infonut** [josh-berry/tab-stash#489]
### Question
Thanks for the detailed reporting form - helps. 😊

If FF (FireFox) crashes (and I think this also happens when I close it, forgetting at the moment - but definitely when is crashes) then I reopen it post crash, a whole slew of stashed tabs that I have in named folders open and are placed in "open tabs."
When I hover over them in the sidebar the 1st stashtab symbol to the far left says "This tab is stashed in XX".

Result desired:
When I open the browser the only tabs I want to come up in open tabs are the ones I had open when FF closed - not ones stashed in a file.
I don't know what I am doing wrong,
Do I need to change an option?
I do have checked "Once a tab has been stashed, hide the tab and immediately unload it" (hence perhaps why that tab opens up after a crash even though stashed) 
But I am thinking that relates to a tab where I right click "stash this tab" or click the symbol in my url box. To say, when I take a tab off my sidebar tab list "Open Tabs" and put it in a folder of stashed tabs I am assuming the tab is closed out since it is in the folder.
If that is not the case (and the reason why all these stashed tabs are popping  up post crash), then how do I have that option checked and move a tab from the sidebar to a folder. I can't close out the tab or it won't be in Open Tabs, where it has to be to move it over to the folder.

Thanks in advance!

### System Details

- **OS Version:**  Windows 10
- **Browser Version:** Firefox 127.0.2
- **Tab Stash Version:** 3.0

**Comment by josh-berry** [comment]
Very strange! How did you install Tab Stash—was it through the Mozilla site? Or are you running a development version you built yourself?

What you are describing should not happen unless you're running a development version and manually loading Tab Stash into Firefox on startup.

Can you try uninstalling and reinstalling Tab Stash and see if that fixes the issue? It's possible something in Firefox doesn't realize that Tab Stash should be keeping these tabs hidden on a browser restart, and this might be fixed by a reinstall. (Don't worry about losing your stashed tabs—they're in your bookmarks, which will be preserved even if you remove Tab Stash entirely.)

**Comment by josh-berry** [comment]
Hi, just wanted to see if you had any luck with uninstalling/reinstalling Tab Stash? Are you still finding that stashed tabs are opening themselves on browser restart?

**Comment by josh-berry** [comment]
Closing this since I haven't heard back, but if it shows up again, please let me know!

**Comment by StormDragon-64** [comment]
I had a similar issue. Zen Browser, Firefox 149.0, Tab Stash 3.4, Arch Linux (6.19.11 kernel).

I don't know if it is _all_ of my stashed tabs or not, but every time I reopen the browser, the tabs I had stashed are in the sidebar like any open tab again. They appear under the "Open Tabs" section in the tab stash menu as well, but they still have the icon that shows when they were stashed. So far, I have been re-stashing them every time, but this artificially increases the number of stashed tabs I have. (Note: doing this does not create duplicate instances of tabs when restarting the browser - it is just as if I had never stashed a tab in the first place).

After reinstalling as suggested, the exact same re-appearing issue is still occurring.

**Comment by josh-berry** [comment]
@StormDragon-64 Sounds like Zen may have a bug related to hiding tabs—in Tab Stash's options, I suggest you try choosing the option to "Close the tab immediately" under the "Tab and Memory Management" section and see if that resolves your issue.
