### ISSUE TITLE
Respect Firefox setting for new tab location

### ISSUE THREAD

**Issue by blukas** [josh-berry/tab-stash#490]
### Problem Statement

When clicking on an item in Tab Stash, it always open as the last tab in the current window, and does not respect the user settings in Firefox for where to place new tabs. I have Firefox set to open new tabs directly to the right of the current tab. The only way to get Tab Stash to respect this setting is to right-click an item in the list and choose to open tab through the context menu.

This makes it difficult to keep things organized for me, and I spend a lot of time having to move tabs that are opened with Tab Stash. When I have a window with 40 tabs, it's very disruptive to open a new tab at the end, far away from the group of tabs I want it placed in.

### Preferred Solution(s)

Tab Stash should allow the user to select if they want the default browser setting for new tab location, or to use the current setting that Tab Stash has for opening as last tab in current window.

### Alternative Solution(s)

Tab Stash doesn't need to have a setting for this. I think the default setting for Firefox is to open new tabs as the last one in the current window, which mirrors Tab Stash's settings. So, if Tab Stash follows whatever is set by the user, it will keep the current default for most users, but also respect the user setting if people have changed it.

### Additional Context

The setting in Firefox to change the new tab location is not in the standard settings, I currently have the browser.tabs.insertAfterCurrent setting in Firefox set to TRUE by installing this plugin: [Always Right](https://addons.mozilla.org/en-US/firefox/addon/always-right/). There are many plugins like this, and other users who install these plugins, or manually change the setting in about:config, are not having their settings choice respected by Tab Stash.

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, thanks for reaching out! Your issue is already covered/duplicated by another issue, so please take a look at the original (and subscribe if you want updates):

* #415
