### ISSUE TITLE
devDependencies version error

### ISSUE THREAD

**Issue by q962** [josh-berry/tab-stash#502]
Two packages involved:
- prettier
```
$ ./node_modules/.bin/prettier --ignore-path .gitignore --check .
Checking formatting...
src\components\oops-notification.vue[error] src\components\oops-notification.vue: SyntaxError: Unexpected closing tag "script". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (156:1)
[error] 154 | clearErrorLog();
[error] 155 | });
[error] > 156 | </script>
[error] | ^^^^^^^^^^
[error] 157 |
[error] 158 | <style module>
[error] 159 | .msg {
All matched files use Prettier code style!

$ ./node_modules/.bin/prettier --version
2.8.8
```
- vue-tsc
https://github.com/vuejs/language-tools/issues/4484

Solution, upgrade to the latest version

Although I develop on Windows, I think the package that gives the error doesn't differentiate between systems.

So I'm wondering. Why does everything work fine in your environment?

**Comment by josh-berry** [comment]
Honestly? No idea. I recommend building in WSL if you're on Windows; nothing in the build system is set up to support native Windows.

```
❯ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

❯ git rev-list -1 HEAD
ebf6855be23b42035583ebe0aa330a6c493ef4ab

❯ ./node_modules/.bin/prettier --version
2.8.8

❯ ./node_modules/.bin/prettier --ignore-path .gitignore --check .
Checking formatting...
All matched files use Prettier code style!
```

**Comment by josh-berry** [comment]
I have updated all of Tab Stash's dependencies (which I do periodically anyway) so you might want to give this another try. Again, though, I recommend building in WSL using the Makefile rather than trying to do things by hand. The build is (unfortunately) quite finicky thanks to the number of "frameworky" dependencies Tab Stash relies on (sigh).

**Comment by q962** [comment]
OK.

I use msys2 on Windows, which provides a similar experience.

Unless the project itself depends on native functionality, there are basically no problems.

Regarding the error with prettier, I can't find the same, only similar. And it seems to only happen on Windows.
