### ISSUE TITLE
[Feature Request] Option to hide address bar button to stash current tab

### ISSUE THREAD

**Issue by ayathedoggo** [josh-berry/tab-stash#503]
Option to remove "Stash this tab" button from the address bar.

I have little screen space and am very clumsy. Keeping my browser as minimalistic as possible is very important to me, which is why I find it quite frustrating indeed that the button for stashing the current tab inserts itself into every tab without an option to remove it.

I've never used this button; my workflow is heading to the extension page that I've set as Firefox Home to stash tabs. It's useless.

If I could remove this button, my address bar would be a lot cleaner, I'd have zero chance of hitting it accidentally and I'd have more screen space to watch funny cat videos or look at how just how long tracking links have gotten in this day and age.

Being able to change the default behavior of the button could also work for certain situations.

I love this extension very much, thank you.

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, thanks for reaching out! Your issue is already covered/duplicated by another issue, so please take a look at the original (and subscribe if you want updates):

* #153

**Comment by ayathedoggo** [comment]
Oh, oops, sorry. Thought it would have been super niche, but I guess we're all neurotic. Thank you again for all the hard work, and have a lovely rest of your day.

**Comment by josh-berry** [comment]
No worries, thanks anyway for the feature request and take care!
