### ISSUE TITLE
Review the "Clear your tabs, clear your mind." "slogan"

### ISSUE THREAD

**Issue by Chealer** [josh-berry/tab-stash#510]
[Tab Stash's AMO page](https://addons.mozilla.org/en-US/firefox/addon/tab-stash/) and its GitHub repository use the phrase _Clear your tabs, clear your mind_. I find that kind of slogan at best _unclear_, notably because ["clear" is such an ambiguous word](https://en.wiktionary.org/wiki/clear#English), and at least the _minds_ of non-native speakers may find using 2 different senses in the same sentence confusing.😁 Even "clearing a tab" [can specifically have a different sense](https://chromewebstore.google.com/detail/clear-new-tab/felphkbfjadmcejnibcmcncimlappdde).

Here are 2 suggestions (which are not necessarily exclusive):

1. To stick to the more common sense, the first part could be changed to "Clear your browser", or "Clear your desktop". Perhaps "Clear your desktop browser", or "Stash your tabs, strengthen your mind."?
2. Replace with (or add) a different "slogan", which some may also find unclear, but which geeks may appreciate:

    > A browser tab counter-proliferation tool

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Thanks for the suggestions. The goal of the slogan is not to be overly descriptive or precise, which is not possible in the space available for a slogan. It is instead to give people a first-order approximation of what problem Tab Stash can solve, invite them to investigate Tab Stash further, and be easy to remember and pin to (memetic, even). I think the current slogan accomplishes all these objectives quite nicely.

Also, I find it interesting you focused on the use of the word "clear"—that word choice, in particular, was quite deliberate, and intended to evoke basically all the definitions you linked to. So I think you have convinced me to stick with it even more. :)
