### ISSUE TITLE
Stash

### ISSUE THREAD

**Issue by dec-mail** [josh-berry/tab-stash#514]
Dear Josh.

Being a keen user of your app, and  even in past week/s discovering extra ways to use it, i have a suggestion

TabStash, is much more than a 'tab stash'.
Eg as you know it handles bookmarks and history.

btw, as i have discovered TS is built as a bookmark's container, i can manage/organise/integrate all the bookmarks/tabs in TS as part of using Manage Bookmarks, which in past few days i have done with all my 8,000 Bookmarks and Stashed Tabs.

my suggestion is that you rebrand in keeping with your app functions to just the simple **STASH**.

i have checked the available domains too, and there are some suitable ones still availale, but i can't avoid the $US39 to but for you. :-(.

i would suggest **stash.tools**

kind regards

don

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
I'm pretty happy with the branding, honestly, since the point is to marry bookmarks and tabs together more seamlessly. I think calling it "Stash" would also make it quite a bit harder to find since there are many other things out there just called "Stash". But I appreciate the thought!
