### ISSUE TITLE
The ability to Import Bookmarks

### ISSUE THREAD

**Issue by smcgrawDotNet** [josh-berry/tab-stash#518]
Would like you to add the ability to import bookmarks.

**Comment by josh-berry** [comment]
You can simply move (or copy) the bookmarks you want to import into the "Tab Stash" folder in your bookmarks, and everything should just work. If you're curious about how this works, this wiki page has more information:

https://github.com/josh-berry/tab-stash/wiki/Problems-Locating-the-Tab-Stash-Bookmark-Folder

Hope this helps!

**Comment by smcgrawDotNet** [comment]
Got it……………

 

Great extentions

 

Samuel McGraw III

Business Analyst & Solutions Architect

***@***.***

509 – 240 – 2115

linkedin.com/in/samuelmcgraw

**Comment by josh-berry** [comment]
👍 Glad I could help!

(BTW, just as a heads-up, the email signature that came through on your GitHub comment had your phone number in it, so I edited your comment to remove it 'cause I assume you wouldn't want it plastered on the open Internet. Thought you might like to know in case you're responding to any other GitHub issues via email.)
