### ISSUE TITLE
Ability To Search Stash Folders [both main & child]

### ISSUE THREAD

**Issue by Dennismn** [josh-berry/tab-stash#534]
### Problem Statement

In my experience, the search function on TS currently doesn't include names of stashed folders. It would be helpful to include the names of folders in the search and not only the individual bookmarks. Thanks for making Tab Stash. It's great.

### Preferred Solution(s)

It would solve the problem that I have when searching because I often label my stash groups.

### Vote for This Issue

- [X] _Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button below.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system._

**Comment by josh-berry** [comment]
Hi @Dennismn, search actually does look for folder names--it will check folder names, bookmark names, and bookmark URLs.

If you're not finding something that you expected to find, perhaps there is an accent character or similar in what you're searching for? Search isn't currently smart enough to differentiate between é and e, for example. (It is case-insensitive, however, so searching for "fred" will find "Fred", for example.)

**Comment by josh-berry** [comment]
I'm going to close this out, but feel free to leave another comment if you have any follow-up questions!
