### ISSUE TITLE
Automate tab stashing/unstashing

### ISSUE THREAD

**Issue by hexagonelle** [josh-berry/tab-stash#535]
### Problem Statement

Suppose I have a window open with some tabs. Then I stash all the tabs in that window to a new group, while keeping the tabs open. If I open some new tabs in that window, I can choose to stash _all_ tabs of the window to the group, and it will automatically remove duplicates. This basically has the effect of only adding _new_ tabs to the group. Nice!

But now, suppose I close some tabs in that window. There's not a one-button solution to _cull_ the closed tabs from the stash - I have to go through the stash, remember which tabs I closed, and manually remove each of them from the stash. When I'm working quickly on lots of things, doing that manually gets overwhelming fast.

### Preferred Solution(s)

It'd be great if there was an option to "sync" the open window with a stash: that way, _exactly_ the set of tabs I have open in that window completely overwrites the tabs in the chosen stash. (I guess coding-wise, you'd look for differences? i.e. what tabs are added/removed in the window compared to the stash)

Additionally - though this sounds harder - it'd be great to "pair" an open window with a stash, so that any changes to tabs in that window are _automatically_ mirrored to the stash. Not sure if that would be unwisely resource intensive, though.

### Alternative Solution(s)

None that I can think of, though I am open to alternative suggestions.

### Vote for This Issue

- [X] _Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button below.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system._

**Comment by josh-berry** [comment]
Thanks, I think this is similar to a couple other feature requests that are already open:

* #42 
* #224 

#42, in particular, seems very close to what you're asking for—a one button "replace the contents of the stash with the current set of open tabs". Would you agree?

**Comment by hexagonelle** [comment]
Oh yes, that sounds like just what I was looking for! Apologies for the duplicate post.

**Comment by josh-berry** [comment]
No problem at all! GitHub can be hard to search so I completely understand missing those. I just happened to remember seeing them before so I knew what to look for. :) I'll close this as a duplicate, but thanks again for the feature requests!
