### ISSUE TITLE
26g of swap used by plugin

### ISSUE THREAD

**Issue by timoc** [josh-berry/tab-stash#54]
### Describe the Bug
For some reason it was allocating ~26G of virtual memory. 

### Steps to Reproduce
No idea.

### Expected Behavior
Not using up all of my virtual memory

### Desktop (please complete the following information):
 - **kubuntu 19 **
 - **Firefox Browser Version:** 75.0

**Comment by josh-berry** [comment]
Hi, can you share a little more information? Why do you think Tab Stash is using memory (as opposed to some other page or extension in Firefox)? How did you measure it?

**Comment by josh-berry** [comment]
Hi, are you still seeing memory issues with Firefox and/or Tab Stash?
