### ISSUE TITLE
Not working- toolbar button and context menu

### ISSUE THREAD

**Issue by FabEditor** [josh-berry/tab-stash#541]
### OS Version

Windows 10 Home

### Browser Version

131.0 (64-bit)

### Tab Stash Version

3.1

### Number of Open Tabs

9

### Number of Stashed Tabs

25

### Total Number of Bookmarks

250

### Installed Extensions

- Bitwarden Password Manager
- YouTube Redux
- Webmail Ad Blocker
- Web Archives
- Violentmonkey
- Undo Close Tab
- uBlock Origin
- Tranquility Reader
- To Google Translate
- Simple Translate
- Reddit Enhancement Suite
- Old Reddit Redirect
- Notion Web Clipper
- MediumUnlimited
- Mate Translate – translator, dictionary
- Greasemonkey
- Gesturefy
- Disable Page Visibility API
- Dictionary Anywhere
- Definer - Popup Dictionary & Translator
- Cookie Remover
- ContextSearch web-ext
- Bypass Paywalls Clean

### Problem Description

When on a website and I click the toolbar button the tab does not stash and I can't open the the context menu

### Steps to Reproduce

I don't know

### Vote for This Issue

- [X] _Readers: If you are also experiencing this problem, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button below.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system._

**Comment by josh-berry** [comment]
Sorry to hear that! Can you double-check your settings for what is supposed to happen when the Tab Stash toolbar button is clicked?

1. Go to `about:addons`
2. Open Tab Stash
3. Click on the **Preferences** tab
4. Make sure the settings under "Tab Stash Behavior" are what you would expect.

If it's not a settings issue, can you try collecting error logs to see what might be wrong: https://github.com/josh-berry/tab-stash/wiki/Collect-Error-Logs

**Comment by FabEditor** [comment]
There is this warning: Warning details

Reading manifest: Warning processing page_action.theme_icons: An unexpected property was found in the WebExtension manifest.

**Comment by FabEditor** [comment]
When I turn off and on the extention - this crash message comes up

 Browser: Mozilla Firefox 131.0 20240923135042 (win x86-64)
Extension: Tab Stash 3.1 (normal)

bookmark-metadata: Port was disconnected while waiting for response
NanoPortError@moz-extension://63e897d7-e701-4692-b55a-31a50d3a4c6e/assets/oops-notification.js:168:1
NanoDisconnectedError@moz-extension://63e897d7-e701-4692-b55a-31a50d3a4c6e/assets/oops-notification.js:184:5
_flushPendingOnDisconnect@moz-extension://63e897d7-e701-4692-b55a-31a50d3a4c6e/assets/oops-notification.js:90:22
Port/<@moz-extension://63e897d7-e701-4692-b55a-31a50d3a4c6e/assets/oops-notification.js:27:12

favicons: Port was disconnected while waiting for response
NanoPortError@moz-extension://63e897d7-e701-4692-b55a-31a50d3a4c6e/assets/oops-notification.js:168:1
NanoDisconnectedError@moz-extension://63e897d7-e701-4692-b55a-31a50d3a4c6e/assets/oops-notification.js:184:5
_flushPendingOnDisconnect@moz-extension://63e897d7-e701-4692-b55a-31a50d3a4c6e/assets/oops-notification.js:90:22
Port/<@moz-extension://63e897d7-e701-4692-b55a-31a50d3a4c6e/assets/oops-notification.js:27:12

bookmark-metadata: Port was disconnected while waiting for response
NanoPortError@moz-extension://63e897d7-e701-4692-b55a-31a50d3a4c6e/assets/oops-notification.js:168:1
NanoDisconnectedError@moz-extension://63e897d7-e701-4692-b55a-31a50d3a4c6e/assets/oops-notification.js:184:5
_flushPendingOnDisconnect@moz-extension://63e897d7-e701-4692-b55a-31a50d3a4c6e/assets/oops-notification.js:90:22
Port/<@moz-extension://63e897d7-e701-4692-b55a-31a50d3a4c6e/assets/oops-notification.js:27:12

favicons: Port was disconnected while waiting for response
NanoPortError@moz-extension://63e897d7-e701-4692-b55a-31a50d3a4c6e/assets/oops-notification.js:168:1
NanoDisconnectedError@moz-extension://63e897d7-e701-4692-b55a-31a50d3a4c6e/assets/oops-notification.js:184:5
_flushPendingOnDisconnect@moz-extension://63e897d7-e701-4692-b55a-31a50d3a4c6e/assets/oops-notification.js:90:22
Port/<@moz-extension://63e897d7-e701-4692-b55a-31a50d3a4c6e/assets/oops-notification.js:27:12

bookmark-metadata: Port was disconnected while waiting for response
NanoPortError@moz-extension://63e897d7-e701-4692-b55a-31a50d3a4c6e/assets/oops-notification.js:168:1
NanoDisconnectedError@moz-extension://63e897d7-e701-4692-b55a-31a50d3a4c6e/assets/oops-notification.js:184:5
_flushPendingOnDisconnect@moz-extension://63e897d7-e701-4692-b55a-31a50d3a4c6e/assets/oops-notification.js:90:22
Port/<@moz-extension://63e897d7-e701-4692-b55a-31a50d3a4c6e/assets/oops-notification.js:27:12

favicons: Port was disconnected while waiting for response
NanoPortError@moz-extension://63e897d7-e701-4692-b55a-31a50d3a4c6e/assets/oops-notification.js:168:1
NanoDisconnectedError@moz-extension://63e897d7-e701-4692-b55a-31a50d3a4c6e/assets/oops-notification.js:184:5
_flushPendingOnDisconnect@moz-extension://63e897d7-e701-4692-b55a-31a50d3a4c6e/assets/oops-notification.js:90:22
Port/<@moz-extension://63e897d7-e701-4692-b55a-31a50d3a4c6e/assets/oops-notification.js:27:12

**Comment by josh-berry** [comment]
(I assume you didn't intend to close this, so I'm reopening it.)

hm, I think that crash is probably expected; Firefox will terminate things in its own way and that can sometimes cause these crashes to appear when disabling the add-on. Normally what should happen is it simply unloads the preferences page / UI, but if it happens to terminate the background page first, you'll see this crash.

The manifest warning is also expected. If that is the only thing you saw in the background page, it seems unlikely there were any crashes.

What did you find from your settings?

**Comment by FabEditor** [comment]
Can you see the images ? 

![tab stash part 1](https://github.com/user-attachments/assets/d3ad78f1-b14d-422f-b089-c8669982c5e6)
![tab stash part 2](https://github.com/user-attachments/assets/7c72f734-e9cc-4763-84c2-19da8f898b22)

**Comment by josh-berry** [comment]
I can, thanks for sharing. It appears you have actually turned off stashing in your preferences:

![screenshot](https://github.com/user-attachments/assets/bdf8dbdc-cbb5-4cbd-a47c-8f3c8bf59151)

**Comment by FabEditor** [comment]
Thank you for your response and I have changed the setting but it still crashing and not working. How do I stop it? Thank you for your time.

 Browser: Mozilla Firefox 131.0 20240923135042 (win x86-64)
Extension: Tab Stash 3.1.1 (normal)

favicons: Port was disconnected while waiting for response
NanoPortError@moz-extension://63e897d7-e701-4692-b55a-31a50d3a4c6e/assets/oops-notification.js:168:1
NanoDisconnectedError@moz-extension://63e897d7-e701-4692-b55a-31a50d3a4c6e/assets/oops-notification.js:184:5
_flushPendingOnDisconnect@moz-extension://63e897d7-e701-4692-b55a-31a50d3a4c6e/assets/oops-notification.js:90:22
Port/<@moz-extension://63e897d7-e701-4692-b55a-31a50d3a4c6e/assets/oops-notification.js:27:12

bookmark-metadata: Port was disconnected while waiting for response
NanoPortError@moz-extension://63e897d7-e701-4692-b55a-31a50d3a4c6e/assets/oops-notification.js:168:1
NanoDisconnectedError@moz-extension://63e897d7-e701-4692-b55a-31a50d3a4c6e/assets/oops-notification.js:184:5
_flushPendingOnDisconnect@moz-extension://63e897d7-e701-4692-b55a-31a50d3a4c6e/assets/oops-notification.js:90:22
Port/<@moz-extension://63e897d7-e701-4692-b55a-31a50d3a4c6e/assets/oops-notification.js:27:12

favicons: Port was disconnected while waiting for response
NanoPortError@moz-extension://63e897d7-e701-4692-b55a-31a50d3a4c6e/assets/oops-notification.js:168:1
NanoDisconnectedError@moz-extension://63e897d7-e701-4692-b55a-31a50d3a4c6e/assets/oops-notification.js:184:5
_flushPendingOnDisconnect@moz-extension://63e897d7-e701-4692-b55a-31a50d3a4c6e/assets/oops-notification.js:90:22
Port/<@moz-extension://63e897d7-e701-4692-b55a-31a50d3a4c6e/assets/oops-notification.js:27:12

bookmark-metadata: Port was disconnected while waiting for response
NanoPortError@moz-extension://63e897d7-e701-4692-b55a-31a50d3a4c6e/assets/oops-notification.js:168:1
NanoDisconnectedError@moz-extension://63e897d7-e701-4692-b55a-31a50d3a4c6e/assets/oops-notification.js:184:5
_flushPendingOnDisconnect@moz-extension://63e897d7-e701-4692-b55a-31a50d3a4c6e/assets/oops-notification.js:90:22
Port/<@moz-extension://63e897d7-e701-4692-b55a-31a50d3a4c6e/assets/oops-notification.js:27:12

favicons: Port was disconnected while waiting for response
NanoPortError@moz-extension://63e897d7-e701-4692-b55a-31a50d3a4c6e/assets/oops-notification.js:168:1
NanoDisconnectedError@moz-extension://63e897d7-e701-4692-b55a-31a50d3a4c6e/assets/oops-notification.js:184:5
_flushPendingOnDisconnect@moz-extension://63e897d7-e701-4692-b55a-31a50d3a4c6e/assets/oops-notification.js:90:22
Port/<@moz-extension://63e897d7-e701-4692-b55a-31a50d3a4c6e/assets/oops-notification.js:27:12

bookmark-metadata: Port was disconnected while waiting for response
NanoPortError@moz-extension://63e897d7-e701-4692-b55a-31a50d3a4c6e/assets/oops-notification.js:168:1
NanoDisconnectedError@moz-extension://63e897d7-e701-4692-b55a-31a50d3a4c6e/assets/oops-notification.js:184:5
_flushPendingOnDisconnect@moz-extension://63e897d7-e701-4692-b55a-31a50d3a4c6e/assets/oops-notification.js:90:22
Port/<@moz-extension://63e897d7-e701-4692-b55a-31a50d3a4c6e/assets/oops-notification.js:27:12

**Comment by josh-berry** [comment]
If you're not seeing any crashes from the background page ([here's the link again for how to find background page logs in case it helps](https://github.com/josh-berry/tab-stash/wiki/Collect-Error-Logs#to-collect-logs-from-the-background-page-tab-stash-sidebar-or-tab-stash-popup)), I have to admit I'm honestly stumped.

A few more things we can look into:

1. Can you try restarting Firefox without any saved session data: https://github.com/josh-berry/tab-stash/wiki/Restart-Firefox-Without-Saved-Session-Data
2. Try completely uninstalling and reinstalling Tab Stash (disabling it is not sufficient). You don't need to worry about losing any saved tabs since they are stored directly in your bookmarks.
3. Have you changed any of Firefox's privacy and security settings? For example, have you told Firefox to stop remembering history?

Also, you mentioned the context menu not working--if you right click in an open tab, do you see any Tab Stash context menu entries at all? Or are these completely missing?

If you can see the menu entries, does the "Show Stashed Tabs in a Tab" entry work at all?

<img width="509" alt="Screenshot 2024-10-12 at 13 50 13" src="https://github.com/user-attachments/assets/99f7a2d5-33a2-4f01-81bb-e775ce2f75d8">

If you can see the context menu, and clicking on the context menu entry doesn't work, it might be worth double-checking to see if there were any more crashes in the background page.

Let me know what you find!

**Comment by FabEditor** [comment]
Hi, I just did a reset on the firefox and it seems to works now. But it stop working when I change the History setting to custom and "always use private browsing mode". 

Why can't I change it to private browsing?

**Comment by josh-berry** [comment]
Got it—you can't do that because it completely disables all storage for extensions, which means Tab Stash has no way to store things like website icons, deleted items (for the undo feature), or even settings. So unfortunately it just breaks a lot of things Tab Stash depends on.

As a workaround, you can keep your history settings the same (turn off "Always use private browsing mode"), always use private-browsing windows, and turn on the "Run in Private Windows" setting in Tab Stash. This still allows Tab stash to store its settings and such, but still gives most of the private-browsing functionality otherwise.

Hope this helps!

**Comment by FabEditor** [comment]
Thank you very much for your help!

**Comment by josh-berry** [comment]
Sure thing! I'll close this out then.

(dup of #102)
