### ISSUE TITLE
Node already exists at index N - Firefox reporting duplicate bookmark indexes

### ISSUE THREAD

**Issue by taylortope** [josh-berry/tab-stash#542]
### Crash Details

```text
Browser: Mozilla Firefox 131.0 20240923135042 (win x86-64)
Extension: Tab Stash 3.1.1 (normal)

Node already exists at index 12
placeNode@moz-extension://61202bf3-8aaf-48b5-9869-63247e03a2d3/assets/oops-notification.js:724:11
_upsertNode@moz-extension://61202bf3-8aaf-48b5-9869-63247e03a2d3/assets/oops-notification.js:1312:48
loaded/<@moz-extension://61202bf3-8aaf-48b5-9869-63247e03a2d3/assets/oops-notification.js:923:38

Node already exists at index 12
placeNode@moz-extension://61202bf3-8aaf-48b5-9869-63247e03a2d3/assets/oops-notification.js:724:11
_upsertNode@moz-extension://61202bf3-8aaf-48b5-9869-63247e03a2d3/assets/oops-notification.js:1312:48
loaded/<@moz-extension://61202bf3-8aaf-48b5-9869-63247e03a2d3/assets/oops-notification.js:923:38
```

### Installed Extensions

- Enhancer for Youtube
- Evernote Web Clipper
- Readwise Highlighter 
- Search by Image 
- Simple Translate
- Swift Selection Search 
- uBlock Orgin
- Unpaywall 

### Describe the Crash

I put my computer to sleep last night, when I went to open tabstash today both the tab and sidebar were blank with the following message:

"Oops! Something went wrong. Tab Stash will try to recover automatically."

It will show open tabs, but if I try to stash them, they disappear and they don't show up in deleted tabs. My tab stash also lists 13+ groups (I had more than that before), but doesn't have any groups stashed. 

### Expected Behavior

To recover all the bookmarks and groups I had. 

### Impact

I went through the steps on the troubleshooting page, there was no change. 

### Vote for This Issue

- [X] _Readers: If you are also experiencing this problem, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button below.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system._

**Comment by josh-berry** [comment]
My first thought is that maybe you had some sort of sync conflict between browsers that is causing Tab Stash to become confused about where your bookmarks are stored. Can you read through this page and let me know if it helps?

https://github.com/josh-berry/tab-stash/wiki/Problems-Locating-the-Tab-Stash-Bookmark-Folder

Also, can you share the crash details from the "Oops!" error message?

**Comment by josh-berry** [comment]
Yeah, I took a closer look at this, and you're right @faralk, I think it's more likely to be a Firefox bookmarks database issue than a sync issue. Another way to work around this would be to export and re-import your bookmarks using Firefox's built-in bookmarks editor, which should fix the incorrect indexes.

I'll have to look at ways of making Tab Stash more resilient to this—it's unfortunately an issue in Firefox itself where sometimes the index (or position) of each bookmark in its parent folder gets messed up. I have seen it happen once in a while before, but not exactly in this way (where multiple bookmarks get assigned the same index).

@taylortope If re-creating the Tab Stash folder itself as @faralk describes doesn't help, I would suggest exporting and re-importing your bookmarks and see if that resolves the issue. Let us know what you find!

**Comment by taylortope** [comment]
So there wasn't a duplicate Tab Stash folder, but I was able to fix it by restoring my Firefox bookmarks from a saved backup.   Thanks for y'alls help!

**Comment by josh-berry** [comment]
Glad to hear it! I'll keep this open and give it a new title, so I have a reminder to look into how to make Tab Stash more resilient to this type of thing. Thanks for letting me know about the crash!

**Comment by josh-berry** [comment]
For future reference / anyone else who finds this bug, I've written up detailed instructions on how to rebuild your bookmarks database here: https://github.com/josh-berry/tab-stash/wiki/Rebuilding-Your-Bookmarks-Database

(And if you've already solved this with backup/restore and want to give me feedback on what I wrote, that's always appreciated!)

**Comment by josh-berry** [comment]
Should be fixed in the next release!

**Comment by teotikalki** [comment]
> Should be fixed in the next release!

Could you please push that release to the Firefox Extension store? It still only has 3.1 (as of Feb 16).

**Comment by josh-berry** [comment]
It's already in flight and waiting on Mozilla's review.
