### ISSUE TITLE
TABSTASH+BOOKMARK INTEGRATION

### ISSUE THREAD

**Issue by dec-mail** [josh-berry/tab-stash#543]
### Question

Hey there Josh.
Still using your great app constantly.

Having a few days ago tediously moving/merging all my many accumulated Tabstash Folders into all my many Bookmark Folders, it has occurred to me that maybe i should do it the other way around - move all my Bookmarks into Tabstash for a better more functional solution.

this solution would presumaably mean that i would leave my 'basic' Bookmarks in the Toolbar; but would move all teh other Bookmark Folders inrto Tabstash.

the end result would mean that i would not have both thousands of tabs/folders in Tabstash AND thousands of Bookmark/folders in Bookmarks.

and by being Tabstash-centric would mean i would always only be saving tabs and folders in Tabstash, and never have to manage and merge the two separate tab/bookmark functions.

what do you think?

PS Can you add a Tab Retitle to Tabstash for tabs not yet saved in TS? Same as old Tab Retitle used to do, but is too unstable now.

kind regards

don

**Comment by josh-berry** [comment]
Hi Don, nice to hear from you. :) You certainly can use Tab Stash as your bookmark organizer—and it's quite easy to try it out and revert back if you don't like it.

In Firefox's built-in bookmark organizer, all you have to do is move your bookmarks into the "Tab Stash" folder (under "Other Bookmarks"), and drag them back out again if you find it's not working out. Tab Stash is perfectly happy for you to use whatever other tools you'd like to organize things both inside and outside the "Tab Stash" folder—Firefox's bookmark editor, most other bookmark extensions, etc. should work just fine with Tab Stash.

For whatever it's worth, personally, I do something similar to what you're considering—I tend to keep things in Tab Stash related to projects that I'm actively working on, and use my browser toolbar folder for "frequently-used" things that I'm always referencing. For example, I might have links to my email, calendar, bank, etc. in my browser toolbar, and things I've saved related to a research project in Tab Stash. Then I can review what I have in Tab Stash regularly as a view into my active projects.

Of course, you can do whatever works for you, and certainly keeping everything in Tab Stash should work smoothly—I made some changes in version 3.1 to improve performance for really large stashes (10,000s of bookmarks). (I also keep all my archived/old bookmarks in Tab Stash, just so I will notice if any new performance issues show up.)

Hope that answers your question, let me know how it works out!

— Josh

**Comment by dec-mail** [comment]
Hey Josh

 

Before I got a chance to answer this, after implementing strategy of moving tabs/bookmarks from Bookmarks to Tabstash, and organising, I am now getting frequent crashes/errors.

 

See a recent one attached

 

Ideas?

 

Kind regards

 

don

**Comment by josh-berry** [comment]
Hi Don, unfortunately the attachments don't come through on GitHub. If you're trying to share a screenshot, it's best to reply through the GitHub UI. You can also just fill out the crash report here (copy/paste the crash details from Tab Stash): https://github.com/josh-berry/tab-stash/issues/new?assignees=&labels=i-bug&projects=&template=1-crash-report.yml

**Comment by josh-berry** [comment]
IIRC we got this one sorted out, so I'm going to close it, but let me know if you have any more questions!
