### ISSUE TITLE
Tab stash breaking top line of bordar pixils on firefox browser

### ISSUE THREAD

**Issue by Atmaweaponvi** [josh-berry/tab-stash#545]
### OS Version

Win 11

### Browser Version

131.0.3 64-bit

### Tab Stash Version

3.1.1

### Number of Open Tabs

15

### Number of Stashed Tabs

13groups, 110 tabs

### Total Number of Bookmarks

300

### Non-Standard Browser Settings

Not that i know of

### Installed Extensions

- u block
- unhook
- dark reader
- simple translate

### Problem Description

When tab stash is open it breaks the top border line of firefox in windowed mode. 

### Steps to Reproduce

Tuning on tab stash.
![broken](https://github.com/user-attachments/assets/96ed7857-698b-4de7-a086-3c8ee2a4fa23)
![unbroken](https://github.com/user-attachments/assets/11423e0f-a1a3-47cb-b7a6-03f2e6e5bb58)

### Impact

I have it isolated to tab stash, and it is a recent problem, not sure why it is happening. Nothing has changed in my setup that I could think would impact this.

### Vote for This Issue

- [X] _Readers: If you are also experiencing this problem, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button below.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system._

**Comment by josh-berry** [comment]
Hi, thanks for the report--this seems more likely to be a Firefox issue related to whether the sidebar is open or not. Tab Stash has no control over what happens outside the borders of its sidebar. Does this also happen with other sidebar views or extensions?

**Comment by Atmaweaponvi** [comment]
Hi, 

Yes you are correct, I just tested with another sidebar app and same issue. I'll try to report it to them. 

Great a app by the way, top tier! 




Oct 20, 2024, 12:37 by ***@***.***:

**Comment by josh-berry** [comment]
Thanks, I'm glad you're liking it! I'll go ahead and close this out but please do reach out again if you need any more help.
