### ISSUE TITLE
A Quick way to delete already deleted bookmarks

### ISSUE THREAD

**Issue by bwkrk** [josh-berry/tab-stash#546]
### Problem Statement

there is no (or at least i do not know about it) to clean up deleted history from tabstash;
It would be useful to have it.

right now, the only way is to go one by one and press _X button_, then press confirmation button _delete forever_
it might be working well for 1-10 items in the list, but if i have 100-1000 items it is very uncomfy.

<img width="330" alt="deleted items" src="https://github.com/user-attachments/assets/2a122062-8355-4c69-9cb8-6d39f6c2fc10">
<img width="547" alt="deleted" src="https://github.com/user-attachments/assets/95f721cc-cd7d-4da8-902e-0cc013f6019b">

### Preferred Solution(s)

simple button - clean all deleted items.

### Vote for This Issue

- [X] _Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button below.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system._

**Comment by josh-berry** [comment]
Thanks—you actually filed this one a while ago, as #249.

As a workaround, if you want to delete ALL deleted items, you can change the retention period in settings to 1 day, and then delete the remaining items by hand. Note that it might take a bit to get Tab Stash to delete the items after changing the setting, though you can speed this up by restarting your browser.

I'll go ahead and mark this as a duplicate, but I hope that helps!
