### ISSUE TITLE
Tabstash Bug/Crash

### ISSUE THREAD

**Issue by dec-mail** [josh-berry/tab-stash#547]
### Crash Details

```text
Win10x64
FF131.02
```

### Non-Standard Browser Settings

No.
It seems apparent that the most obvious immediate cause was, as discussed, my move of so many new Tabs/Bookmarks (say approx 6,000) into TS. It woud be a weird co-incidence otherwise.

But i need to upload screen shots.
![tabstash-error-25-10-2024 17-48-34](https://github.com/user-attachments/assets/4efd1b95-7182-4029-b84f-e707b0f1450d)
![tabstash-crash-25-10-2024 15-07-42](https://github.com/user-attachments/assets/7bd17875-b01f-4681-8915-aed8de375736)

### Installed Extensions

Not any listed or similar.

### Describe the Crash

Moving open Tab groups to TS.
1. Doesn't show the Tabs in open Group
and/or
2. Doesn't save Tabs

But sometimes, now, if we get this one error - it STILL seems to save the tabs

### Expected Behavior

Display/list open tabs
Save/migrate open tabs to TS

### Impact

Just worked around it or ignored it when error happens

### Additional Details

No.
It seems apparent that the most obvious immediate cause was, as discussed, my move of so many new Tabs/Bookmarks (say approx 6,000) into TS. It woud be a weird co-incidence otherwise.

### Vote for This Issue

- [X] _Readers: If you are also experiencing this problem, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button below.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system._

**Comment by josh-berry** [comment]
Thanks Don for sharing the crash details. The most important bit is in the detail screenshots you shared: `Node already exists at index 19`. This tells me it's most likely a problem with your bookmarks database.

Can you try the steps written here and see if they help to resolve the crash: https://github.com/josh-berry/tab-stash/wiki/Rebuilding-Your-Bookmarks-Database

You might be able to figure out which folder has the issue by moving them in and out one-by-one, but honestly, it's probably going to be faster just to import/export the whole set of bookmarks.

Let me know if this helps!

**Comment by dec-mail** [comment]
HEY JOSH

 

I eventually found them all 'stashed' 😉 under Other Bookmarks I think

 

And so I have moved the right ones I think and deleted the right ones I think 😉

 

Haven't tested anything yet - too busy trying to sort & organize all my Bookmark/TS Folders

 

I have made one more tweak to that arrangement.

 

Because stashing new tabs stacks them at the top of TS so that existing TS Folders keep getting pushed further down (unless you keep manually editing & moving), I have made an additional TS Folder at the root of TS, and moved all existing Folders there and organed them accordingly, but they are still inside the TS structure, so the named Folders still at the top and organised albeit under a separate sub-folder (called Library say), and, then at my convenience I can delete or file the new stashed tab folders ie 'saved …' into a new or existing Folder in the main 'Library' directory/

 

And then I fine-tune/organise my actual Tool bar if just a few most used tabs (plus I also have a 'Home' Tab at the start of the Toolbar which has other common Tabs.

 

That looks like it going to work ok

 

Attached.

 

Kind regards

 

don

**Comment by josh-berry** [comment]
Great, I'm glad to hear you've figured out a structure that works for you! Let me know if you're still having problems after re-importing.

I'll go ahead and close this but feel free to reply here anyway if you're still having trouble!

(dup of #542)
