### ISSUE TITLE
Stashed Links Duplicates Remover/Blocker

### ISSUE THREAD

**Issue by tigersof** [josh-berry/tab-stash#549]
### Problem Statement

It's really easy to stash links away and lose track of what you have.  It uses significant resources otherwise and can make it challenging to find what you're looking for too. 

### Preferred Solution(s)

It would be greatly improved if there was a way to prevent links already stashed once from being stashed multiple times.

### Vote for This Issue

- [X] _Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button below.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system._

**Comment by josh-berry** [comment]
Hi, thanks for reaching out! Your issue is already covered/duplicated by another issue, so please take a look at the original (and subscribe if you want updates):

* #334
