### ISSUE TITLE
User Named Sidebar Stash Groups to Quickly Stash Links On-The-Go

### ISSUE THREAD

**Issue by tigersof** [josh-berry/tab-stash#550]
### Problem Statement

I dislike having to scroll down only to have to scroll all the way back up, back and forth all the time. Tab Stash causes me to do this a lot, and I find I lack sufficient concentration and patience to deal with it. As a consequence, my tabs simply get dumped in the vague hope I'll be able to do something useful with them later. So far, that hasn't happened but I would like it to!  

### Preferred Solution(s)

When I open Tab Stash in the sidebar (or vertical tabs list), I'd like to see my user-defined Tab Stash groups which I've set up along themes and subjects I've chosen drop down into the side bar (or vertical tab list). Then I'd like to be able to drag tab links directly into these groups, while automatically closing those tabs.

I'd like to be able to open all the links in certain Tab Stash Groups, and then be able to stash them back just as easily when I'm done. 

This would help save more memory resources which browsers are notorious for consuming at the expense of performance elsewhere. I suffer the dreaded blue screens of death regularly, even now!

### Vote for This Issue

- [X] _Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button below.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system._

**Comment by josh-berry** [comment]
I'm afraid I'm a bit confused, because what you're asking for, Tab Stash already does:

- If you just want an overview of your groups, there is a "Collapse all groups" button to the right of the top search box
- You can rename groups by clicking on their titles and typing in the new name
- You can restore an entire group by clicking the green "Open all tabs..." button next to the group name
- You can save everything currently open into the group by clicking the blue "Stash all (or highlighted) tabs" button next to the group name

Can you explain a bit more specifically what's not working for you? That might hep me to understand a bit better.

**Comment by tigersof** [comment]
I get lost in the main page very easily. Hiding/Showing the groups there doesn't help me. It always ends up with excessive scrolling. I'd like to see a list of the group names in a sidebar/vertical tab bar (which I always use as it makes things so much easier). A right click over the group name for the tab I'm viewing could allow me to stash (and close) the tab directly into the group. Also, clicking a group name from a list in the sidebar, to view the stashed tabs, would be easier too.

Similarly for multi-selected tabs - a right click could stash them all at once in the appropriate group, perhaps with a context menu list of the groups dropping down. 

Users decide the names for the groups. 
HTH

**Comment by josh-berry** [comment]
It sounds like maybe you're only using the "show everything in a tab" view and not using the Tab Stash sidebar? The sidebar setup you're describing sounds a lot like this (where the highlighted blue icon is the "stash the current tab" button):

<img width="1089" alt="Screenshot 2024-10-28 at 21 11 33" src="https://github.com/user-attachments/assets/04e861d8-e21a-438e-8aa2-c528b76cf6dd"> 

You can then multi-select tabs from the "Unstashed Tabs" (or "Open Tabs") list to be stashed into a named stash like so:

<img width="1090" alt="Screenshot 2024-10-28 at 21 16 44" src="https://github.com/user-attachments/assets/d759b0d1-2ddc-4895-b08f-391962d628d8">

Or by using the blue drop-down that appears at the top of the sidebar, like so:

<img width="1090" alt="Screenshot 2024-10-28 at 21 17 25" src="https://github.com/user-attachments/assets/5d74b968-cd24-48c8-ab37-6f5ffb0b34f4">

This is admittedly not a right-click/context-menu type thing, but should be quite similar to what I think you're looking for.

Does that help at all?

**Comment by tigersof** [comment]
Hi,

Kind of, but no. I'd like to be able to simply multi-select tabs the 
normal way as you do in a horizontal bar (or vertical in my case). I 
don't want to be concerning myself with being precise about where I 
click on the tab descriptions. This already causes me problems when 
multi-selecting tabs in your Tab Stash, either in the sidebar or main 
page. The reason being, it's a narrow area and people have different 
abilities from an accessibility POV.

Whether in the main page or in the sidebar, I often miss the target 
area, which causes all the tabs already selected to become deselected 
and so I have to redo the whole exercise all over again. Often I have 
several attempts at it before I get it right. It can become quite 
painful (physically). The ensuing inevitable fatigue and worsening 
concentration will add to the effect.

As I can have hundreds, sometimes thousands of different tabs which I 
want to group differently all open at the same time in the same browser 
window, it doesn't eliminate the need to scroll back up and down a long 
way endlessly. A context menu would prevent much of this. The groups 
listed at the top would help this a little.

The other issue with Tab Stash for me is that I usually have my tabs 
open in a structured format (using TST for example), a bit like folders 
and things inside folders etc. Tab Stash destroys the layout that helps 
me navigate my vertical bar more easily. If we could collapse and expand 
unstashed tabs in their pre-existing tree while selectively stashing 
them, it would make it a lot easier to avoid so much scrolling. Tab 
Stash just flat lists them all, with no hint of the structure 
underneath. When I see too many words and no structure, I fail to see 
the wood for the trees. It's overwhelming as I can no longer easily pick 
things out and spend more time and effort I don't really have in a 
spiralling circle of inefficiency, while sending me googly-eyed.

I find the stash groups difficult to maintain, which is why everything 
just gets dumped into long lists of tab groups. Often, I'll end up 
duplicating a group name, along with duplicate tabs stashed inside them. 
This isn't very effective, nor I suspect good practice in terms of 
computer performance and resources. But it's all I can do at the moment.

I really like what your extension does. I just need it to be a bit 
easier to use. Its recent significant speed improvement (not sure if 
this is a mix of you improving things and Mozilla too - I've noticed 
firefox no longer hitting the 99% memory brick wall and maintaining a 
top level around 80% usage which is really helping all round 
performance) is such a delight.

I hope you can help! Thanks.



------ Original Message ------
From "Josh Berry" ***@***.***>
To "josh-berry/tab-stash" ***@***.***>
Cc "tigersof" ***@***.***>; "Author" ***@***.***>
Date 29/10/2024 01:19:20
Subject Re: [josh-berry/tab-stash] User Named Sidebar Stash Groups to 
Quickly Stash Links On-The-Go (Issue #550)

**Comment by josh-berry** [comment]
> Kind of, but no. I'd like to be able to simply multi-select tabs the normal way as you do in a horizontal bar (or vertical in my case). I don't want to be concerning myself with being precise about where I click on the tab descriptions. This already causes me problems when multi-selecting tabs in your Tab Stash, either in the sidebar or main page. The reason being, it's a narrow area and people have different abilities from an accessibility POV.
>
> Whether in the main page or in the sidebar, I often miss the target area, which causes all the tabs already selected to become deselected and so I have to redo the whole exercise all over again. Often I have several attempts at it before I get it right. It can become quite painful (physically). The ensuing inevitable fatigue and worsening concentration will add to the effect.

Gotcha. I hear what you're saying re. the accessibility issue. Unfortunately, allowing selection by clicking on the tab description would prevent people from opening a tab to see what's inside it while a selection is active (e.g. to decide whether to select it or not). But there might be other ways to make that target bigger, and/or make it so that missing the selection box wouldn't cost you your entire selection. I'll give this some thought.

> As I can have hundreds, sometimes thousands of different tabs which I want to group differently all open at the same time in the same browser window, it doesn't eliminate the need to scroll back up and down a long way endlessly. A context menu would prevent much of this. The groups listed at the top would help this a little.

Right, so like I said earlier, you can use the selection menu for this today:

<img width="258" alt="Screenshot 2024-11-02 at 11 41 30" src="https://github.com/user-attachments/assets/30717ece-978d-404b-8b1f-7fea3970888c">

It's always visible on the screen no matter how far down you've scrolled, and you can also search the list of groups in the menu itself, so you should never have to scroll to find the group you're looking for.

I know it's not a context menu--I deliberately avoid overriding the built-in browser context menu, because that would prevent people from using other extensions and/or built-in Firefox functionality with stashed tabs. But it hopefully gets most of the way there.

> The other issue with Tab Stash for me is that I usually have my tabs open in a structured format (using TST for example), a bit like folders and things inside folders etc. Tab Stash destroys the layout that helps me navigate my vertical bar more easily. If we could collapse and expand unstashed tabs in their pre-existing tree while selectively stashing them, it would make it a lot easier to avoid so much scrolling. Tab Stash just flat lists them all, with no hint of the structure underneath. When I see too many words and no structure, I fail to see the wood for the trees. It's overwhelming as I can no longer easily pick things out and spend more time and effort I don't really have in a spiralling circle of inefficiency, while sending me googly-eyed.
>
> I find the stash groups difficult to maintain, which is why everything just gets dumped into long lists of tab groups. Often, I'll end up duplicating a group name, along with duplicate tabs stashed inside them. This isn't very effective, nor I suspect good practice in terms of computer performance and resources. But it's all I can do at the moment.

Yeah, TST integration is an oft-requested feature. See #94. There are unfortunately some complications there--Firefox needs to roll out some fixes to make this work, first, and TST may need to make some updates on their side as well.  So unless/until both of those things happen (if they haven't already; I haven't checked recently), there's nothing I can do.

> I really like what your extension does. I just need it to be a bit easier to use. Its recent significant speed improvement (not sure if this is a mix of you improving things and Mozilla too - I've noticed firefox no longer hitting the 99% memory brick wall and maintaining a top level around 80% usage which is really helping all round performance) is such a delight.

I'm glad to hear it--and yeah, I made some performance improvements in 3.1 especially for big stashes and big bookmarks databases. I'm glad to hear they're helping!

**Comment by tigersof** [comment]
Hi Josh,

Thank your for your helpful response.

Are there display differences for Mac OS and Windows users? According to 
your screenshot, Screenshot.2024-11-02.at.11.41.30.png (view on web) 
<https://github.com/user-attachments/assets/30717ece-978d-404b-8b1f-7fea3970888c>, 
I should see a drop down with a search box in it. I use Windows with 
Firefox and don't see this. Instead, my drop down (in the same position 
as shown in your screenshot) displays as the following:

_______________________

   Options...
------------------------
   Import...
   Export...
------------------------
   Deleted Items...
   Fetch Missing Icons
------------------------
   Tips & Tricks
   Wiki
   Help & Support
------------------------
   What's New
   Sponsor
_______________________


I'll send a screenshot over later to show the differences when I can get 
the chance, although hopefully the above will be enough.


Re: "But there might be other ways to make that target bigger, and/or 
make it so that missing the selection box wouldn't cost you your entire 
selection. I'll give this some thought."

An immediate thought/suggestion I have is to try splitting the tab list 
pane in two vertically, with one half for selection and the other for 
clicking to view the tab page, via the creation of a 'selection 
overlay'. They can be delineated by subtle colouring/vertical line 
through the middle/both. I don't know how feasible this is, so I'll 
leave that for you to decide!

Re: "I know it's not a context menu--I deliberately avoid overriding the 
built-in browser context menu, because that would prevent people from 
using other extensions and/or built-in Firefox functionality with 
stashed tabs. But it hopefully gets most of the way there."

Not always, but Firefox navigation by speech has improved in that it is 
possible to voice-click menus and context menus, whereas it's still 
impossible to work with drop-downs by voice. Drop-downs tend to be 
flimsy in that if you click away, they disappear. It's difficult to 
avoid this when using Dragon because you typically can't voice-type 
directly into the search box (incompatible box), and Dragon is unable to 
maintain/pick up the link to the drop-down once focus temporarily moves 
to its built-in workaround the "dictation box", so it never works. A 
little food for thought, if you will!

Re: "I'm glad to hear it--and yeah, I made some performance improvements 
in 3.1 especially for big stashes and big bookmarks databases. I'm glad 
to hear they're helping!"

It was amazing really, positively on speed!


------ Original Message ------
From "Josh Berry" ***@***.***>
To "josh-berry/tab-stash" ***@***.***>
Cc "tigersof" ***@***.***>; "Author" ***@***.***>
Date 02/11/2024 15:57:12
Subject Re: [josh-berry/tab-stash] User Named Sidebar Stash Groups to 
Quickly Stash Links On-The-Go (Issue #550)

**Comment by josh-berry** [comment]
There are no differences between Mac and Windows, other than some minor cosmetic differences to blend in with each platform better. To get the selection menu to appear, you have to select a tab first in the Tab Stash UI. Then the regular drop-down menu will be replaced with a blue selection menu showing the number of items selected (the "1" in my screenshot). Hope this helps!

**Comment by josh-berry** [comment]
I'm going to close this out but feel free to re-open it if you have any more follow-up questions!
