### ISSUE TITLE
Tabstash Column Width

### ISSUE THREAD

**Issue by dec-mail** [josh-berry/tab-stash#552]
### Problem Statement

I can't seem to adjust the TS column width.

### Preferred Solution(s)

Adjust TS column width

### Vote for This Issue

- [X] _Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button below.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system._

**Comment by josh-berry** [comment]
True, this is not adjustable right now. It's automatically determined by the browser with some constraints applied to make it work well with any browser window size.

Adjusting the column width / number of columns is already captured in #126 (which had a partial/incorrect title), so I'll mark this as a duplicate.

**Comment by dec-mail** [comment]
Ha!

 

Sorry Josh, I have nothing but problems and glitches ever since I dragged all my BMs into TS.

 

See one the latest attached, and some others if I can find … prob some dups

 

Kind regards

Don

**Comment by josh-berry** [comment]
Hi Don, unfortunately attachments don't come through on GitHub. Did you try the suggestion I sent to you earlier? https://github.com/josh-berry/tab-stash/wiki/Rebuilding-Your-Bookmarks-Database

**Comment by dec-mail** [comment]
Hey Josh

 

I tried exporting/importing BMs; I can't seem to get it to work.

 

The export to HTML seems to work fine and is not empty; but when I go to import, and I select the file just exported - nothing seems to happen!

 

Nothing changes: it just sits there in BM Manager.

 

Cheers

 

Don

**Comment by josh-berry** [comment]
All of your imported bookmarks will show up at the very bottom of the "Bookmarks Menu" folder. (They will not go into the usual places in "Bookmarks Toolbar" / "Other Bookmarks".) Did you look there for them?
