### ISSUE TITLE
[Feature Request] Tabs Count Indicator Next to Stash Title

### ISSUE THREAD

**Issue by bolohori** [josh-berry/tab-stash#555]
### Problem Statement

As a frequent user of TabStash, I find it challenging to quickly assess the number of tabs contained within each stash. This information is quite relevant for efficient tab management when I have multiple stashes, especially if they're collapsed

Currently, to assess the tabs number in a stash, I have to:
- select all tabs in a stash and click move items to a different stash 
OR
- open each stash individually to see how many tabs are stored there. 

A visible count indicator next to each stash title would significantly streamline this process.

### Preferred Solution(s)

1. **Tabs Count Indicator**: 
   - Add a count indicator displaying the number of tabs next to each stash title in the TabStash sidebar or tab. This would allow users to quickly see how many tabs are in each stash without needing to open/select>move them.

### Alternative Solution(s)

1. **Hover Tooltip**:
	- Implement a tooltip that appears when hovering over a stash title, showing the number of tabs contained within that stash.

2. **Add items count in auto-generated stash title**
	- For example : dd/mm/yyyy, HH:MM - # items

3. **Sorting by Tab Count** 🫣🤯:
   - Allow users to sort their stashes based on the number of tabs, making it easier to prioritize and manage larger stashes.

### Additional Context

The addition of a tabs count indicator is a simple yet effective enhancement that could improve usability for many users. It would allow for quicker decision-making and organization of tabs without the need to navigate through each stash.

Thank you for taking the time to read this and considering this request!

Cheers,  
Horia

### Vote for This Issue

- [X] _Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button below.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system._

**Comment by josh-berry** [comment]
I have some good news for you—this tooltip already exists:

<img width="321" alt="Screenshot 2024-11-08 at 19 34 10" src="https://github.com/user-attachments/assets/43265fca-866f-434c-b3f8-009acdd07af2">

Just hover your mouse cursor over the stash title (or folder title) and you'll see the tooltip. Hope this helps!

**Comment by josh-berry** [comment]
Hope I was able to address this, I'll go ahead and close it, but feel free to re-open if you have any more follow-ups!
