### ISSUE TITLE
Let TS support smart bookmarks

### ISSUE THREAD

**Issue by exekutive** [josh-berry/tab-stash#557]
### Problem Statement

TS doesn't support smart bookmarks

### Preferred Solution(s)

I would love if TS could support smart bookmarks. They could appear as child folders.

### Additional Context

Examples of smart bookmarks the "Most Visited" folder. Or tag filters (created by copy-pasting them from the tags library, or using the 'place:tag=cuisine' location), or other custom queries (https://developer.mozilla.org.cach3.com/en/Places_query_URIs).

### Vote for This Issue

- [X] _Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button below.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system._

**Comment by josh-berry** [comment]
Unfortunately, Firefox itself would have to support this in their extension APIs first. There is currently no way for extensions to know anything about bookmark tags, or see the results of smart-bookmarks queries. While the `places:` URL in the bookmark itself is visible to Tab Stash, it appears just like any other (non-smart) bookmark in the API.

**Comment by exekutive** [comment]
ah that's too bad. Are there any upstream efforts to implement this in FF?

**Comment by josh-berry** [comment]
Not that I'm aware of, but I don't keep a close eye on Mozilla's bug database. I suspect they have a lot that's higher on their priority list at the moment, given they are trying to make some major UI improvements right now.

**Comment by exekutive** [comment]
Maybe some day. Thanks for replying.
