### ISSUE TITLE
Load groups on demand (exponential expansion or search by group name)

### ISSUE THREAD

**Issue by No3371** [josh-berry/tab-stash#560]
### Problem Statement

I've been using Tab Stash for years. This results in 9K+ stashed tabs. Tab Stash is pretty heavy to open for a html page. Ram usage surge to 10G with it opened and 6G with it closed if ever opened.

**I'm aware this is a user issue,** I probably won't ever use 1% of all the stashed tabs, but I still want to suggest this regardless, since the idea has been in my mind for several years.

The concept is simple: There's really no reason to load everything at once into the page (CPU overhead to open the page and memory overhead to keep it). Maybe even stop remembering group opened state (Reduce rendering overhead by default).

### Preferred Solution(s)

I'd suggest 2 new buttons: "Load More" and "Load All".
Load only the first row of groups collapsed. Double the row count for each click of "Load More".
This allows the page to always load with minimal overhead and expand on demand.

### Additional Context

I also want to take the chance to suggest "Export" in group context menu so if I am going to clear away all the old stuff I can easily export the recent ones.

### Vote for This Issue

- [X] _Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button below.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system._

**Comment by josh-berry** [comment]
Which version of Tab Stash are you using? All of what you are suggesting performance-wise has already been done as of version 3.1, so if you're still seeing high memory usage on 3.1 or later, that sounds more like a bug. You may not notice the auto-loading, however, because it's completely automatic and quite fast—on a fast-enough machine, the page elements are usually created before you can physically scroll them into view.

FWIW, I myself keep a stash of over 12k tabs precisely so I can keep an eye on performance and memory usage.

**Comment by No3371** [comment]
I have 3.1.1. I agree the page is not really that heavy.

I was saying loading up all the groups in the html by default (especially when they are left open) feels unnecessary. I can't be sure about others' user flow but personally I am not looking for the old groups for the most part when I see the Tab Stash page.

My perception of the performance could also be biased because 95% of times I see the page is when I stash a whole window, so TabStash seems extra busy.

Did some tests:
50 + 1 tabs in 2 windows:  about 1.4
Show Stashed Tabs in a Tab: about 4~5 GB

So it seems like the dedicated ~4G I logged (with about:memory) from TabStash when I was posting this is because there is something stuck in the memory after I stash a window.

BTW I did notice that the overall performance is much improved, especially the stashing is superb compared to the old days (it no longer blocks the window👍 )

**Comment by josh-berry** [comment]
> I was saying loading up all the groups in the html by default (especially when they are left open) feels unnecessary.

Right, I got what you meant. 👍 Tab Stash only creates enough HTML to fill the screen, and then automatically loads more when you scroll. Same story with collapsed groups—the contents aren't created until needed.

> So it seems like the dedicated ~4G I logged (with about:memory) from TabStash when I was posting this is because there is something stuck in the memory after I stash a window.

So one thing to be aware of is that `about:memory` will show you the memory usage for the whole set of Firefox processes, and different extensions will get mixed together in the same process. If you do want to dig more at the memory usage and measure what the Tab Stash UI itself is using, you can open the web inspector (right-click in the Tab Stash page -> Inspect), choose the "Memory" tab and take a snapshot. It will show you the total memory use of the page in the left sidebar (where it lists the snapshots you've taken). (It'll also give you a fine-grained way to dig into how the memory is used, but that's probably not helpful unless you like reading Tab Stash's code...)

The other thing to note is that if you're using the default Tab Stash settings for hiding tabs, the tabs themselves will not be unloaded for a bit, and so those pages themselves may continue to use memory until either Tab Stash or Firefox unloads them automatically. In Tab Stash's options under "Tab and Memory Management", you can tell it to "Hide the tab and immediately unload it" or "Close the tab immediately".

> BTW I did notice that the overall performance is much improved, especially the stashing is superb compared to the old days (it no longer blocks the window👍 )

Thanks! I did a lot in 3.1 to make things faster especially for large stashes, so I'm happy to hear it's been helpful!

And like I said, if you do find that you're still seeing heavy memory usage even on 3.1.1, I'd love to dig at it further with you to understand why. Will be curious to hear what the snapshot shows.

**Comment by No3371** [comment]
> Right, I got what you meant. 👍 Tab Stash only creates enough HTML to fill the screen, and then automatically loads more when you scroll. Same story with collapsed groups—the contents aren't created until needed.
Interesting, my concern is invalidated then, that's good!

> So one thing to be aware of is that about:memory will show you the memory usage for the whole set of Firefox processes, and different extensions will get mixed together in the same process.
I'm aware, I was talking about the memory record specifically for the stash-list.html, like:
> │  ├──2,669.12 MB (52.59%) -- top(moz-extension://24e5e19d-67e0-4f6b-840a-0fdbd43872e7/stash-list.htm

> The other thing to note is that if you're using the default Tab Stash settings for hiding tabs...
Sure, I always explore options available on everything I can configure. It's set to unload immediately long since.

I guess I'll wait for the next time I am going to stash a fat window and observe then, and get back to you if anything seems off. For now let's close this, sorry for bothering!
