### ISSUE TITLE
Shortcut(s)

### ISSUE THREAD

**Issue by Interleace** [josh-berry/tab-stash#561]
### Problem Statement

I look around but couldn't find a way to set a shortcut for anything.
At least for opening and closing the Tab Stash sidebar.

### Preferred Solution(s)

Ability to set at least one shortcut: toggle Tab Stash sidebar 

### Additional Context

Important for keyboard-oriented people

### Vote for This Issue

- [X] _Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button below.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system._

**Comment by josh-berry** [comment]
Keyboard shortcuts are documented here: https://josh-berry.github.io/tab-stash/tips.html

Hope this helps!
