### ISSUE TITLE
Sort by site

### ISSUE THREAD

**Issue by ERNAZAR02** [josh-berry/tab-stash#566]
### Problem Statement

Current tab stash is more about manual effort so why dont we make it half-automate.

### Preferred Solution(s)

Automatic sort by site would be time saver. when ever i have to group the sites, it just messy

### Vote for This Issue

- [X] _Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button below.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system._

**Comment by mark-addams001881** [comment]
Hello, we tried to solve the issue.

This is what we did:

Implement automatic sorting of tabs by site in the Tab Stash extension. This includes adding a new option in the settings, modifying the stashing process to group tabs by site, and updating the UI to reflect this new functionality.

You can review changes in this commit: https://github.com/mark-addams001881/josh-berry-tab-stash-566/commit/0f98e421686e05887a93498bb9f0cc4970806363.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by josh-berry** [comment]
Hi, thanks for reaching out! Your issue is already covered/duplicated by another issue, so please take a look at the original (and subscribe if you want updates):

* #194
