### ISSUE TITLE
Stash Tabs to the Left/Right

### ISSUE THREAD

**Issue by Cyuonut** [josh-berry/tab-stash#6]
I would love to have the option to stash all tabs to the left and right. Many times I have important tabs (that I don't want to pin) in the left, and extraneous tabs have started piling up in the right. Choosing "Stash Tabs to the Right" from the last one I'd like to keep would be great! Occasionally I've also needed to stash the left ones, and some other people might find it more useful.

If you need help implementing this, please let me know.

**Comment by josh-berry** [comment]
Hey, thanks for the feature request—I've occasionally found myself wanting the same thing, especially if I get interrupted and/or distracted and have a bunch of tabs for different things I was working on mixed together in the same window.

I think my approach would be to add two additional menu items to the Firefox tab bar's context menu—something like "Stash all tabs to the left [or right] of this tab". Does this match what you're thinking?

---

I think this would be pretty straightforward to implement, and I'll add it to my backlog. That said, I'm always happy to review and accept patches, so if this is something you're interested in helping out with, please feel free to send a pull request. :)

If you do decide to implement it, all the menus are defined in `src/index.js`. I think mostly what's needed is to add a couple extra entries to `commands`, and corresponding menu items to the relevant `menu()` calls. There may be one additional complication of dealing with the case where a user right-clicks on a tab that isn't the front-most/active tab—I don't know if Firefox provides enough info in the menu event to determine which tab the user clicked on.

**Comment by Cyuonut** [comment]
Thanks for the reply! Yes, your approach was what I was looking for, and similar to what's implemented in Tab Unloader extension (https://addons.mozilla.org/en-US/firefox/addon/tab-unloader-we/). I'd go and copy their solution, as it also supports targeting an inactive tab.

I just realized, now that Firefox supports selecting multiple tabs, that stashing selected tabs would be nice, too! Just like bookmarking tabs. If only one is selected, the menu option would be "Stash This Tab", and if multiple, "Stash Selected Tabs".

I might try to get this done, and will follow your commits to see if you got it made first!

**Comment by josh-berry** [comment]
I just pushed a commit to add support for Firefox multiple tab selection, so you can shift/ctrl+click on tabs in your Firefox tab bar, hit any stash button (that ordinarily stashes multiple tabs), and Tab Stash will grab only the selected tabs.

I'm going to test this out myself for a bit (along with some other fixes), but assuming everything goes well, this will be in the next release!

**Comment by josh-berry** [comment]
Tab Stash 2.3 has just been released, which contains the aforementioned support for multiple tab selection (so you can shift+click to select all tabs to the left or right of the active tab, and then click the "Stash" button in the toolbar to stash everything you selected).
