### ISSUE TITLE
Is there any way of renaming the title of a stashed tab?

### ISSUE THREAD

**Issue by zinahe** [josh-berry/tab-stash#60]
### Question

Is there any way of renaming the title of a stashed tab? (not the group)

### System Details

- **OS Version:** [Ubuntu 19.10]
- **Browser Version:** [FireFox 75]
- **Tab Stash Version:** [2.6]

**Comment by josh-berry** [comment]
Not in the UI right now, but as a workaround, you can open the Firefox bookmarks manager and manually rename the bookmark saved in the Tab Stash folder.

As long as the tab is not open, Tab Stash will show the bookmark name. When a tab with the same URL as the bookmark is opened, Tab Stash will show the tab title instead, but it does not actually rename the bookmark. So once the tab is closed again, the bookmark will still have the name you gave it.

**Comment by josh-berry** [comment]
Going to close this out but please do let me know if the above didn't answer your question, thanks!
