### ISSUE TITLE
Blank favicon on old stashed tabs

### ISSUE THREAD

**Issue by EmmanuelMess** [josh-berry/tab-stash#63]
### System Details
- **OS Version:** Ubuntu 20.04
- **Browser Version:** Firefox 77.0.1
- **Tab Stash Version:** 2.6

### Describe the Bug
Old stashed tabs' favicons are blank.

### Expected Behavior
Old expired fabicons should be rerequested.

### Steps to Reproduce
1. Stash a tab
2. Sync with Firefox account
3. purge Firefox
4. Resync

### Impact
Not much, just a small glitch

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, sorry for the inconvenience—Tab Stash 2.6 changed the way favicons are cached to use a more accurate method that takes into account the entire URL, and this is an expected side-effect of that change. The icons will repopulate themselves (and should stay repopulated) as you visit each site.

Alternatively, you can fetch all your favicons again using the "Fetch Missing Icons" menu option in the Tab Stash UI. This is unfortunately a rather expensive operation, so it's not something that should be done automatically. (It requires loading each site in a tab and checking the tab's icon—the favicon can be set in any number of ways, including with JavaScript, so there's unfortunately no good shortcut for doing this.)

**Comment by EmmanuelMess** [comment]
> It requires loading each site in a tab and checking the tab's icon

Why? If you want to know what icon was set shouldn't you just parse the we page? Without showing anything I mean.

**Comment by josh-berry** [comment]
No, that's not sufficient—as I explained, some sites set their icons with JavaScript, and figuring out the favicons for those sites would require executing arbitrary code.

Plus, even if it were sufficient, allowing Tab Stash to make arbitrary HTTP requests to fetch any site requires significantly elevated permissions which I don't feel are reasonable to ask for.

**Comment by EmmanuelMess** [comment]
> No, that's not sufficient—as I explained, some sites set their icons with JavaScript, and figuring out the favicons for those sites would require executing arbitrary code.

What I mean was that executing code as if the webpage was being loaded for viewing but not actually making any calls for rendering anything should get the favicon without being too expensive (aside from the network request costs).

> Plus, even if it were sufficient, allowing Tab Stash to make arbitrary HTTP requests to fetch any site requires significantly elevated permissions which I don't feel are reasonable to ask for.

Oh, I didn't know that. No workarounds?

**Comment by josh-berry** [comment]
The only workaround I'm aware of would be to use a Google or similar service to fetch a site's favicon (which I think does something similar to what you are describing behind the scenes), but that would require sending your site URLs to a third-party provider, which I also don't want to do for privacy reasons.

**Comment by josh-berry** [comment]
Ideally favicon fetching is something I think Firefox itself should provide; unfortunately there are no WebExtension APIs for this. There is an open bug here though: https://bugzilla.mozilla.org/show_bug.cgi?id=1315616

**Comment by EmmanuelMess** [comment]
> The only workaround I'm aware of would be to use a Google or similar service to fetch a site's favicon

Can't another extension be used? Something that _does_ ask for the required permissions, if the extension is installed, use it, if not, show empty favicon.

**Comment by josh-berry** [comment]
I suppose it's possible—I think WebExtensions can communicate with each other provided they explicitly agree to do so. But from a user perspective it seems overkill to ask users to install a second, highly-privileged extension just for corner cases where icons don't happen to be in the cache (e.g. because the tab was saved on a different computer, or the cache was cleared, or whatever). There is certainly benefit, I'm just not sure if there's _enough_ benefit to make the trade-off worthwhile for most people.

That said, if such an extension for Firefox already exists, I'd certainly be willing to look into integrating with it.

**Comment by EmmanuelMess** [comment]
> That said, if such an extension for Firefox already exists, I'd certainly be willing to look into integrating with it.

That's what I meant. Do you think there is an integration mechanism for Firefox extensions?

**Comment by josh-berry** [comment]
I know Firefox provides APIs for sending data to/from other extensions, provided the extension explicitly opts in to receive/send such data. But I don't know of any extension that does what you are suggesting with favicons.

**Comment by josh-berry** [comment]
Going to close this out since I think most people are on 2.6 by now, and should have gone through this transition already. But if you run into any other favicon-related problems, please feel free to open a new issue. Thanks!
