### ISSUE TITLE
Are Stashed Tabs Kept "Open" in Memory?

### ISSUE THREAD

**Issue by themorgan** [josh-berry/tab-stash#65]
Hi!

I love Tab Stash, thank you for creating and supporting it!

I have a question that I wasn't able to find answered in the documentation. The tabs that are stashed, are they still "open" in Firefox and thus consuming memory? So, if I have 100 tabs stashed, it would use the same memory as if all 100 tabs were just open normally in Firefox?

I had always assumed that they were not open, and thus it wouldn't effect the performance of Firefox (in fact, it would speed it up since my 100 tabs would be stashed haha!). But just now, a stashed tab with a Youtube player was playing the video, so that led me to think that the tabs might be open. Note that it could be that this tab started playing when open (because I had just stashed it a minute before) so it could also be that this video playing was an edge case of some sort.

Thank you very much!!!!!
morgan

**Comment by josh-berry** [comment]
Hi Morgan, yes they are—up to a point. Tab Stash will automatically unload stashed tabs if you start to accumulate a lot of them, so your browser doesn't take up a lot of memory or CPU resources. The defaults are tuned such that you shouldn't have to worry about this most of the time—except, as you've noticed, things like YouTube might continue to play in the background. :)

That said, you can control this behavior in the Tab Stash options (from the stash, click the menu icon to the left of the search box, and choose "Options"). If you don't want tabs to remain loaded/running but still want to be able to restore them quickly, the middle option ("Hide and immediately unload") might be a good choice for you. But if you still find your browser is slowing down too much, you can also have Tab Stash close the tab entirely once it's stashed.

Hope this helps, and I'm glad you're enjoying Tab Stash!

— Josh

**Comment by themorgan** [comment]
Josh this is perfect. I just updated that option right now. THANK YOU!!!!
