### ISSUE TITLE
"Stash selected tabs"?

### ISSUE THREAD

**Issue by EmmanuelMess** [josh-berry/tab-stash#66]
### Question
What is a "selected" tab?

### System Details

- **OS Version:** Ubuntu 20.04
- **Browser Version:** Firefox 77.0.1
- **Tab Stash Version:** 2.6

**Comment by josh-berry** [comment]
Any tab that is highlighted in your browser's tab bar (e.g. by Ctrl+ or Shift+Clicking on the tab). Here's a screenshot from the add-on page for Tab Stash showing an example: https://addons.cdn.mozilla.net/user-media/previews/full/238/238907.png?modified=1590902158

If only one tab is "selected" (which is true most of the time—just the active tab is "selected"), the stash button will stash all tabs. But if you multi-select tabs like what's shown in the screenshot, only the selected tabs will be stashed.

**Comment by EmmanuelMess** [comment]
I never knew this existed haha!
