### ISSUE TITLE
The export UI is hard to figure out for first-time users

### ISSUE THREAD

**Issue by themorgan** [josh-berry/tab-stash#67]
Hey :)

Another super quick question: is there a way to export all the tabs to a text file? I just happen to be really paranoid and am always worried they'll be lost and I have 100+ etc.

Thank you!!!! :)
Morgan

**Comment by josh-berry** [comment]
Yes! Just added in the most recent release, there are Import and Export options in the menu. You can choose from a variety of formats for how you want to save. If you're just looking to keep a simple text file with the names of your stashes and URLs, I recommend choosing "List of URLs". You can copy/paste that list into a text file, and then paste it back in to the Import menu to restore. (Tab Stash will find the titles for you.)

That said, if you DO end up losing anything and it seems like it's Tab Stash's fault, please do file a bug. :)

— Josh

**Comment by themorgan** [comment]
Hey Josh!

I don't see this in the menu option, and Firefox says I have the latest version :( I'm not quite sure what the problem is (unless the latest version on Git isn't the same as the latest version via the Mozilla Addons site)? Or maybe there's another options screen somewhere I should look at?

FYI, Firefox says I have version 2.6 released on May 27th. The options in the extension I see are (if I'm looking in the right place): Show stashed tabs in a tab, show stashed tabs in a sidebar, stash tabs, copy tabs to stash, manage extension, remove extension, report extension, pin to overflow menu, remove from toolbar, bookmarks toolbar, customize. 

Thank you and sorry for these trivial questions!
morgan

**Comment by josh-berry** [comment]
Hi Morgan, no problem! I think I should have clarified _which_ menu, sorry about that!

In 2.6, there is a new menu in the Tab Stash UI itself. So if you choose one of the "Show Stashed Tabs..." options in the right-click menu you found, it opens the UI. Right next to the search bar at the top is a Tab Stash icon—clicking it will open the menu with import/export. I've added a screenshot to the add-on listing for Tab Stash so you can see what I mean:

https://addons.cdn.mozilla.net/user-media/previews/full/240/240098.png?modified=1592684817

Hope this helps!

**Comment by themorgan** [comment]
Found it -- and I exported them perfectly. Thank you.

For an unsolicited suggestion: once I did find it, I was really confused, because at first it wouldn't export -- and then I realized I had to select all. And then, when I selected all and copied, it kept on copying only the names, not the URLs, so I was confused. Eventually, I figured out that you have to choose the list of URLs from the menu then select all then copy. My suggestion would be, since exporting all the URLs would be the overwhelmingly common use-case for this (a list of names without the URLs isn't really useful for an export) maybe to have it default to URLs and default to all-selected by default :) 

Thank you, this is an awesome extension!!!! :)

**Comment by josh-berry** [comment]
Thanks, that's great feedback!

The way this is normally supposed to work is, the "Formatted List" mode actually gives you clickable links. So if you want to send an email to somebody or save some references into a document, you can copy/paste the "Formatted List" into your email window or document, and the list of names should (still) be clickable links when you paste them. But not every application supports formatted text, which is where the other export formats come into play.

But I totally get your point that it might be confusing for a first-time user to figure out what's going on there, and I especially like your idea of doing select-all by default. I'll see what I can do to make this easier.

**Comment by themorgan** [comment]
Great, thank you!!! You're awesome :)

**Comment by josh-berry** [comment]
I've added some polish and additional explanation to the import/export pages based on what we talked about above, and it will be available in the next Tab Stash release. Enjoy!
