### ISSUE TITLE
Add option for "Tab Stash toolbar button" to just show the stashed tabs

### ISSUE THREAD

**Issue by TheRealBax** [josh-berry/tab-stash#68]
Hi

**Problem**

It happened to me quite often, that I accidentally left click the "Tab Stash Toolbar button" expecting it to show my stashed tabs, but instead it stashed all open tabs. 

**Preferred solution**

It would be very helpful to give some options in the settings:

Behavior left click on "tab Stash toolbar Button":
1. Stash all tabs
2. Show stashed tabs in sidebar
3. Show stashed tabs in tab

Love the extension!
Bax

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, thanks for the feature request, and I'm glad you're enjoying it! This is actually the same as #21 , so if you could add any additional thoughts to that issue and give it a vote (click the smiley face icon on the first post in #21 and give it a thumbs-up), that would help me keep things organized and prioritize it accordingly.
