### ISSUE TITLE
Pin search box to top of sidebar

### ISSUE THREAD

**Issue by JimBreton** [josh-berry/tab-stash#69]
Not sure if this is possible, but it would be great if the Search box in the sidebar could be pinned/frozen to the top so it would remain visible/usable even whilst scrolled down into a long list of tabs.

Thanks for a great extension!

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, I don't think it will be too hard, I'll take a look when I get a chance!

**Comment by josh-berry** [comment]
This will be in the next release. Enjoy!
