### ISSUE TITLE
The program doesn´t work

### ISSUE THREAD

**Issue by serram2019** [josh-berry/tab-stash#7]
The program simply doesn´t work with my Firefox. It open an empty panel and keeps stashing for a very long time, and never really ends this process. This screenshot is after two hours of the program working.

![Screen Shot 04-24-19 at 06 09 PM](https://user-images.githubusercontent.com/49122314/56694206-8c957280-66bc-11e9-8e26-d4aa8795a51a.PNG)

I use Windows 10 64 bits, and Firefox Quantum 66.0.3. I don´t know if there´s some relation between the two issues, but I can´t work well with the Favorites on Firefox, the menu doesn´t obey to commands and it never saves alterations, even though I have done everything that is said in their support to solve the problem.

**Comment by josh-berry** [comment]
Hi, thanks for your report and sorry to hear you're having trouble. It's quite possible that whatever is causing the problems with your favorites is also affecting Tab Stash. I have a couple questions and some steps to try to collect some more information so we can see what's going wrong.

First, a couple questions:
* After you try to stash something, if you close and re-open the sidebar (Ctrl+Shift+S is the keyboard shortcut), do you see the same "Stashing..." message, actual bookmarks/stashed tabs, or something else?
* If you open the Firefox bookmarks browser (Menu > Library > Bookmarks > Show All Bookmarks), and navigate to the "Tab Stash" folder and look at your stashes, do you see the same "Stashing..." message or do you see actual bookmarks?

Second, can you try to reproduce the problem and collect some console messages? The steps to do this are:

1. Open a few tabs in your browser (they should be pointing to actual websites, not just empty tabs).
2. Right-click anywhere in your browser window, go to "Tab Stash" and choose "Show Stashed Tabs in a Tab". This will open a new tab showing your stash.
3. Right-click anywhere inside the "Tab Stash" tab and choose "Inspect Element". This will open the Firefox developer tools.
4. Choose the "Console" tab in the developer tools.
5. In the "Tab Stash" tab (NOT the firefox toolbar), click the "Stash only the unstashed tabs..." button underneath "Unstashed Tabs". (It looks exactly like the Firefox toolbar button.)
6. Copy and post any errors that appear in the console (or attach a screenshot showing any errors, whichever is easiest for you).

This will hopefully shed a little more light on what's going on with your system.

**Comment by serram2019** [comment]
Hi, Josh, thanks for your ready answer. I was busy these days, so just now
I have the time to answer to you.

>>After you try to stash something, if you close and re-open the sidebar
(Ctrl+Shift+S is the keyboard shortcut), do you see the same "Stashing..."
message, actual bookmarks/stashed tabs, or something else?<<
No, it just opens an empty panel, no matter how many times I close and
reopen the program

>>If you open the Firefox bookmarks browser (Menu > Library > Bookmarks >
Show All Bookmarks), and navigate to the "Tab Stash" folder and look at
your stashes, do you see the same "Stashing..." message or do you see
actual bookmarks?<<
I see the "Stashing" message for all the bookmarks


   1. <<Open a few tabs in your browser (they should be pointing to actual
   websites, not just empty tabs).
   2. Right-click anywhere in your browser window, go to "Tab Stash" and
   choose "Show Stashed Tabs in a Tab". This will open a new tab showing your
   stash.
   3. Right-click anywhere inside the "Tab Stash" tab and choose "Inspect
   Element". This will open the Firefox developer tools.
   4. Choose the "Console" tab in the developer tools.
   5. In the "Tab Stash" tab (NOT the firefox toolbar), click the "Stash
   only the unstashed tabs..." button underneath "Unstashed Tabs". (It looks
   exactly like the Firefox toolbar button.)
   6. Copy and post any errors that appear in the console (or attach a
   screenshot showing any errors, whichever is easiest for you).>>

All keeps white, the tab, the tab stash panel. Didn´t appear the option to
"Stash only the unstashed tabs" and the Console tab is empty, too.
I really don´t know what´s happening with my Firefox, I just know that the
program has been every  time worse since a few years, keeps failing and not
working well and the part of Bookmarks don´t work for a long time now. I
downloaded your extension in the hope of solving these problems.

Thanks in advance,
Sérgio R. de A. Marcondes
Doutorando em História das Ciências e da Saúde - COC-Fiocruz
Tel.: (21) 98400-7434; (21) 2576-1573


Em qui, 25 de abr de 2019 às 01:18, Josh Berry <notifications@github.com>
escreveu:

**Comment by josh-berry** [comment]
Hi Sérgio,

From what you're describing, if both Tab Stash AND the built-in Firefox tools are having trouble updating bookmark entries, it sounds like something might be wrong in your bookmarks database itself. Firefox keeps all bookmarks, history information, etc. in a single "places" database, and if that database is corrupt somehow, it might be responsible.

Have you already tried refreshing your Firefox? This will delete and re-create your entire Firefox profile (containing your settings, bookmarks, history, extensions, etc.), and copy over bookmarks, history, passwords, etc. to the new profile.

Instructions for refreshing Firefox are here: https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings

If refreshing Firefox doesn't work, we can try manually exporting your bookmarks, and manually deleting/recreating the profile. But let me know how the refresh works, and if it doesn't help, I'll see if I can find the instructions to do it manually.

— Josh

**Comment by josh-berry** [comment]
Hi Sérgio, were you able to reset your Firefox, and did that help?

**Comment by serram2019** [comment]
Hi Josh.

I reset the Firefox, and in the first time that I used the program, it all
worked well, including Tab Stash. But when I turned on the computer on the
following day, the program had the same problems again: I can´t do any
action with the Favorites, like delete, move the bookmarks from one file to
another etc. And Tab Stash keeps the same message, actualizing in all
windows. So I just deleted the extension and I´m using Google Chrome, for
at least there I can organize my bookmarks.

Sérgio R. de A. Marcondes
Doutorando em História das Ciências e da Saúde - COC-Fiocruz
Tel.: (21) 98400-7434; (21) 2576-1573


Em sex, 24 de mai de 2019 às 00:02, Josh Berry <notifications@github.com>
escreveu:

**Comment by josh-berry** [comment]
I'm sorry to hear that, but I'm glad Chrome has been working for you.

I'm not sure if you're using Firefox Sync, but if you ever want to revisit this, you might try resetting and/or deleting your Sync account, and then resetting your browser again so you are starting with a completely fresh state (no bookmarks/favorites, history, etc.). Based on the fact that it worked fine to begin with and then stopped working again, I wonder if there is some bad Sync data in your Firefox Sync account which is confusing Firefox.

Given that you've moved to Chrome and aren't using Firefox anymore, I'll go ahead and close this issue, but if you ever decide to try Firefox and need help with Tab Stash again, feel free to re-open this issue or open a new one.
