### ISSUE TITLE
no stask icon

### ISSUE THREAD

**Issue by selster** [josh-berry/tab-stash#72]
I have win 10 and installed stash but cannot see the icon.  Have tried reinstalling both stash and firefox
Thanks, Steve

**Comment by josh-berry** [comment]
Hi Steve, can you give me a little more information: Which icon are you referring to--the icon in the Firefox toolbar? Which version of Firefox are you using? Is this in a private browsing window or a regular window?

**Comment by josh-berry** [comment]
Hi Steve, any updates on this? Can you answer the questions above or let me know if you have resolved the issue?
