### ISSUE TITLE
Saved groups/tabs are occasionally lost/moved out of the stash

### ISSUE THREAD

**Issue by josh-berry** [josh-berry/tab-stash#8]
There is a known issue related to Firefox Sync and Tab Stash where, on rare occasions, saved tabs and groups might suddenly disappear from your stash. When this happens, it usually involves groups/tabs that were saved, moved or renamed recently.

If this happens to you, follow these steps to locate and restore your missing bookmarks/tabs:

1. Open the Firefox menu (the three horizontal lines in your toolbar)
2. Choose "Library", then "Bookmarks"
3. Choose "Show All Bookmarks" at the very bottom
4. Find and open the "Other Bookmarks" folder in the sidebar. If any stashed folders appear there, drag them back into the "Tab Stash" folder.
5. If any bookmarks associated with stashed tabs appear in the "Other Bookmarks" folder, create a new folder for them, drag the bookmarks into the new folder, and drag the new folder into the "Tab Stash" folder.
6. Find and open the "Tab Stash" folder. If any bookmarks appear there, drag them into the appropriate folder underneath "Tab Stash". (You can create a new folder for these "orphaned" bookmarks if you prefer.)

As of right now, I believe this is a Firefox issue, not a bug in Tab Stash (but please do not comment on the Firefox bug—linked below—unless you have some technical details to add). However, I'm opening this issue to track possible mitigations/workarounds that could be applied in Tab Stash itself.

ref: https://bugzilla.mozilla.org/show_bug.cgi?id=1549648

**Comment by josh-berry** [comment]
This appears to be a Tab Stash issue after all—or at least, a poor interaction between Firefox Sync and Tab Stash which can happen when multiple synced browsers are running at the same time (even on different computers).

I'm about to push some commits to address it which will go into the next Tab Stash release—take a look at the commit messages for all the gory details.

**Comment by josh-berry** [comment]
Going to keep this issue open for a while (maybe even past the next release) to verify the fix actually works and we don't see any more instances of missing tabs.

**Comment by selster** [comment]
Might it be easier to have a save my stashes to a local file, one that could be restored when needed?

**Comment by josh-berry** [comment]
Firefox actually does this for you already with the backup/restore bookmarks functionality (it will automatically make periodic backups of all your bookmarks to a local file), and that's going to be more comprehensive/play nicer with other browser features such as Sync than what Tab Stash can do as an extension.

In any case, in my experience it's just been easier to drag the wayward bookmarks back to where they belong, rather than go through a full restore. (And the fix for this particular issue will be released very soon anyway.)

**Comment by josh-berry** [comment]
Tab Stash 2.3 has just been released with a fix for this. I'll leave the issue open for a bit to give everyone a chance to (auto-)upgrade, but this issue should be resolved.
