### ISSUE TITLE
Broken "show stashed tabs on new tab"

### ISSUE THREAD

**Issue by EmmanuelMess** [josh-berry/tab-stash#83]
### System Details
- **OS Version:** Ubuntu 20.04
- **Browser Version:** Firefox 78.0.1
- **Tab Stash Version:** 2.6

### Describe the Bug
Broken "show stashed tabs on new tab"

### Steps to Reproduce
1. Right click tab stash button
2. "Show stashed tabs in a tab"

### Impact
High

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by EmmanuelMess** [comment]
Related:
Sidebar's buttons for unstashing/stashing tabs don't do anything.

**Comment by josh-berry** [comment]
Hi, can you please try the steps outlined here and see if that fixes the problem: https://github.com/josh-berry/tab-stash/wiki/Restart-Firefox-Without-Saved-Session-Data

If that doesn't help, can you please share any error logs: https://github.com/josh-berry/tab-stash/wiki/Collect-Error-Logs

**Comment by EmmanuelMess** [comment]
Fixed!
