### ISSUE TITLE
Highlight current tab

### ISSUE THREAD

**Issue by bluecub3d** [josh-berry/tab-stash#89]
### Current Tab Not Highlighted
I'm coming from a tree tab extension and I tend to use the Tab Stash to navigate.

It would be great to see the current focused tab highlighted in the tab stash to allow easy identification for selection and dragging into existing groups.

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment]
Hi, thanks for the suggestion, I'll keep it in mind!

**Comment by amk1208** [comment]
I second (well, third) that! I love tab stash and the only reason I still sometimes use the tabs addon is simply that I find my current tab at once, because it's highlighted.

**Comment by josh-berry** [comment]
This will be available in the next release!
