### ISSUE TITLE
keywords

### ISSUE THREAD

**Issue by selster** [josh-berry/tab-stash#9]
**Ask your question**
Please be as clear and specific as possible. The more information you provide up-front, the easier it will be for us to respond to your question quickly and accurately.

**Supporting Details (please complete the following information if relevant):**
 - OS: [e.g. Mac, Windows, Linux]
 - Firefox Browser Version: [e.g. 60.0.2]

**Comment by josh-berry** [comment]
I saw your issue #10 and replied there. :)
